### ISSUE TITLE
Can't install this plugin in Android Studio

### ISSUE THREAD

**Issue by mwajeeh** [jimkyndemeyer/js-graphql-intellij-plugin#1]

**Comment by jimkyndemeyer** [comment]
The plugin depends on two other plugins: NodeJS and JavaScript. The JetBrains repository upload page indicates that this makes it incompatible with Android Studio.

A large part of the plugin deals with Relay.QL JavaScript/TypeScript string templates. Were you looking for "just" the .graphql query editor?

**Comment by DungFu** [comment]
It would be great to have just the graphql query editing in a separate plugin that doesn't need the node.js/javascript plugins and could be installed in android studio, etc.

**Comment by mwajeeh** [comment]
Yes I am looking for just graphql syntax highlighter/validator. I had this (https://plugins.jetbrains.com/plugin/8038?pr=androidstudio) plugin but the guy stopped development on it and is pointing to your repo.

**Comment by jimkyndemeyer** [comment]
Okay. I'll investigate whether this is feasible.

Out of curiosity, are you using GraphQL to provide native Android components with JSON data? I was expecting GraphQL development on Android to be on ice until Relay gets support for React Native.

**Comment by jimkyndemeyer** [comment]
I've just added an experimental version of the plugin to the android-studio branch at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio

Can you guys take it for a spin and let me know if there's any issues.

**Comment by DungFu** [comment]
Seems to work well for me so far, thanks for adding this!

**Comment by mwajeeh** [comment]
Working fine for me as well. Good job. Thanks

**Comment by jimkyndemeyer** [comment]
I've updated README.md in master, so I'm going to close this for now.

This is definitely an area that could use additional contributors since I don't develop for Android.

**Comment by mwajeeh** [comment]
Now I am getting this error while installing and I don't remember how I solved it last time. Any help please?
<img width="478" alt="screen shot 2016-03-29 at 4 43 03 pm" src="https://cloud.githubusercontent.com/assets/6572067/14106893/ccf7fd06-f5cd-11e5-9d94-eb730dc35909.png">

**Comment by jimkyndemeyer** [comment]
@mwajeeh The android studio version is not published to the JetBrains plugin repository. You have to download and install it manually from https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio#faq

**Comment by mwajeeh** [comment]
@jimkyndemeyer I am able to install it manually but after its installed it gets disabled and I get above mentioned error which is "Plugin JS GraphQL depends on unknown plugins NodeJS, JavaScript".

**Comment by jimkyndemeyer** [comment]
@mwajeeh The version for android doesn't depend on those plugins. I looks like Android Studio may have gotten confused after having the JS/node version of the plugin installed.

Here are the steps that I just followed with Android Studio 1.5.1 to install the plugin successfully:

- Uninstall the plugin completely
- Restart and verify the plugin is no longer present
- "Install plugin from disk" using the jar downloaded from https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/raw/android-studio/android-studio/0.1.0/js-graphql-intellij-plugin.jar
- Verify that the plugin appears as follows, with the "- Android Studion" postfix in its title:

![android-studio](https://cloud.githubusercontent.com/assets/15837712/14117015/ff5e43bc-f5e2-11e5-872e-c82b0b247b25.png)

Let me know if that works for you.

/Jim

**Comment by mwajeeh** [comment]
It worked, thank you so much.
