### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by nitingupta910** [jimkyndemeyer/js-graphql-intellij-plugin#102]
My graphql endpoint is over https with self signed certificate. With this setup, I'm getting following error from plugin, probably when it's trying to do introspection query. Can you please provide workaround/solution for this? 

I see similar issue here for graphql-app (https://github.com/skevy/graphiql-app/issues/27) for which suggested workaround is:
```
app.commandLine.appendSwitch('ignore-certificate-errors');
```
but I'm not sure how to do it for this intellij plugin.

For reference, here is the trace I'm getting in clion console:
```
JS GraphQL listening on http://127.0.0.1:62779/js-graphql-language-service
Setting Project Dir '/Users/ngupta/src/myproject'
Watching '/Users/ngupta/src/myproject/graphql.config.json' for changes.
Error loading schema from 'https://localhost:4000/graphiql' { Error: self signed certificate
    at TLSSocket.<anonymous> (_tls_wrap.js:1108:38)
    at emitNone (events.js:105:13)
    at TLSSocket.emit (events.js:207:7)
    at TLSSocket._finishInit (_tls_wrap.js:638:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:468:38) code: 'DEPTH_ZERO_SELF_SIGNED_CERT' } { url: 'https://localhost:4000/graphiql',
```

**Comment by jimkyndemeyer** [comment]
Hi Nitin.

Thanks for using the plugin.

The language service use `then-request` to perform the request, and unfortunately it appears that it doesn't have any options to ignore certificates.

For your use case you need to use the `file` option in your `graphql.config.json`.

The file can be your schema expressed as GraphQL Schema language (with version 1.6 of the plugin), or it should point to the JSON result of an introspection query. To perform the [introspection query](https://github.com/graphql/graphql-js/blob/eb01a23c578d949ccea2fa2b350e65a3893e6895/src/utilities/introspectionQuery.js#L15-L105), you can add a script to your project in your language of choice, and make it work with the certificate. You would then run the script when the schema changes.

Hope this helps. Let me know if you have any questions.

**Comment by nitingupta910** [comment]
Thanks for creating the plugin. I will try using the file method.
