### ISSUE TITLE
`GraphQL: Can't create process handler: No Node.js interpreter found on system path.` on Android Studio

### ISSUE THREAD

**Issue by rnitame** [jimkyndemeyer/js-graphql-intellij-plugin#106]
I can't find this setting on Android Studio 3 beta 6
https://www.jetbrains.com/help/webstorm/configuring-node-js-interpreters.html#d29699e59

Is there any other solution? :(

**Comment by jimkyndemeyer** [comment]
Hi Ryo.

Please see the [android-studio](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio) branch for a version that works with Android Studio. Installation and download instructions are mentioned in the FAQ of that branch.

Hope that gets you up and running.

/Jim.

**Comment by rnitame** [comment]
Thank you for reply!
but, I have already installed from android-studio branch 😢

**Comment by jimkyndemeyer** [comment]
Can you double-check that it's the jar from https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/raw/android-studio/android-studio/0.1.0/js-graphql-intellij-plugin.jar that you installed? First remove the GraphQL plugin, restart Android Studio, then add using the jar file.

If the plugin still fails to start, please include the stack trace by clicking on the red error icon in the bottom right of the status bar.

/Jim.

**Comment by rnitame** [comment]
Yes, I can. I've checked.
Stack trace is here ↓
![image](https://user-images.githubusercontent.com/4950792/31163735-d43bbe6c-a91e-11e7-9203-fc675e117b61.png)

**Comment by jimkyndemeyer** [comment]
Ok, so it looks like you don't have the node.js binary in your system path. See https://nodejs.org/en/download/ for download and installation instructions.

Once you've installed, you should be able to run the following from a command line:
```
node --version
```

When that works, restart Android Studio and it should be able to locate the node.js binary.

**Comment by rnitame** [comment]
mmm... (´・ω・｀)
not solved...

![image](https://user-images.githubusercontent.com/4950792/31222485-34f0799e-aa02-11e7-9d5b-e829c0989122.png)

**Comment by jimkyndemeyer** [comment]
Please try the node version command from the terminal window inside Android Studio.

I suspect that it doesn't have the Node.js binary in its path for some reason on your system. I just verified locally that it works as expected with beta 7 of Android Studio 3.

**Comment by rnitame** [comment]
Fixed !!!
Because my path setting is wrong 😭 

Thanks @jimkyndemeyer !!

**Comment by jimkyndemeyer** [comment]
Glad you got it working. I'll go ahead and close the issue.
