### ISSUE TITLE
unknown directives on relay modern

### ISSUE THREAD

**Issue by sibelius** [jimkyndemeyer/js-graphql-intellij-plugin#108]
Relay modern has a bunch of new directives like this one:

- [ ] @arguments
- [ ] @argumentDefinitions
- [ ] @connection
- [ ] @relay(plural: boolean)
- [ ] @relay(mask: boolean)

and this one https://facebook.github.io/relay/docs/relay-directives.html

**Comment by jimkyndemeyer** [comment]
I'm merging this and related issues into #121
