### ISSUE TITLE
emoji in schema description breaks this plugin

### ISSUE THREAD

**Issue by unlimitedsola** [jimkyndemeyer/js-graphql-intellij-plugin#110]
just get the github-api's graphql schema by following guide
https://developer.github.com/v4/guides/intro-to-graphql/#discovering-the-graphql-api

then it breaks the highlighting and code completion
![image](https://user-images.githubusercontent.com/3632663/32032136-19403f04-ba38-11e7-9765-2bff1a5e5845.png)

after removing the emoji it works fine.

**Comment by jimkyndemeyer** [comment]
Fixed in #216 with the upcoming v2 alpha-8.
