### ISSUE TITLE
support graphcool framework

### ISSUE THREAD

**Issue by smmoosavi** [jimkyndemeyer/js-graphql-intellij-plugin#111]
in graphcool framework we can see `@model`, `@isUnique` in schema file. which not supported with graphql plugin

https://github.com/graphcool/framework

![screenshot from 2017-10-27 09-54-04](https://user-images.githubusercontent.com/1582954/32090575-ed043c0e-bafc-11e7-8126-8e3e06a94000.png)

```
# The following types define the data model of the example service
# based on which the GraphQL API is generated

type User @model {
  id: ID! @isUnique
  name: String!
  dateOfBirth: DateTime

  # Uncomment below - you can declare relations between models like this

  # posts: [Post!]! @relation(name: "UserPosts")
}


# Uncomment the model below as well

# type Post @model {
#   id: ID! @isUnique
#   title: String!
# 
#   # Every relation also required a back-relation (to determine 1:1, 1:n or n:m)
#   author: User! @relation(name: "UserPosts")
# }
```

**Comment by smmoosavi** [comment]
maybe this link can help: https://www.graph.cool/docs/reference/database/data-modelling-eiroozae8u/#graphql-directives

**Comment by flux627** [comment]
Maybe the ability to add arbitrary white-listed directives to configuration would be a catch-all solution for things like this.

**Comment by jimkyndemeyer** [comment]
I'm merging this and related issues into #121
