### ISSUE TITLE
Disable unknown directive warnings for sdl

### ISSUE THREAD

**Issue by timsuchanek** [jimkyndemeyer/js-graphql-intellij-plugin#114]
When defining a schema in the schema definition language (sdl) in a `.graphql` file, you get errors for missing directives:
![image](https://user-images.githubusercontent.com/1094804/32723195-e0ec258a-c86c-11e7-8bb7-472d20ac4538.png)

These errors don't come when having a `.graphqls` file. This is a convention, that is new to me.
Is this already adopted in the wider community?
We at Graphcool recommend people to write their schema in a `.graphql` file.
It would be great to either find a consensus on this or make this configurable :)

Thanks!

**Comment by tamlyn** [comment]
Related #111

**Comment by jimkyndemeyer** [comment]
I'm merging this and related issues into #121
