### ISSUE TITLE
How to import & use generated queries?

### ISSUE THREAD

**Issue by spentak** [jimkyndemeyer/js-graphql-intellij-plugin#116]
First off - fantastic work on this. I will say the readme is a little short :)

We have a GraphQL server and It's pulling in the schema just fine. And what is more is I get that nice  "GraphQL Schemas" at the bottom of the project. But it is un-useable.

How in the world do I have it generate that same file for me in a specified location so I can use it with React/Typescript ie:

`import { slopes } from './queries.graphql';`

Instead of having to manually create queries (before I found the plugin):

`export const SLOPES_QUERY = gql{ slopes { name orderNumber skillTracks { name orderNumber } } };`

In the past I've used:

` #apollo-codegen generate **/*.graphql --schema schema.json --target typescript --output types.ts`

And was hoping the plugin did the same thing, but not a line of instruction anywhere specifying how to do this. 

Could you point me in the right direction?

**Comment by jimkyndemeyer** [comment]
Hi Mark.

Thanks for using the plugin.

The plugin focuses on the GraphQL language and makes no assumptions about how you will be accessing the GraphQL scheme types in your code, other than the use of `gql`, `Relay.QL`, and `graphql` tagged templates which activates the plugin.

Some people use JS, some with Flow, others use TypeScript. So it's up to you how and if to use code generation. Using apollo-codegen should work fine in combination with the plugin. In my own team, we use an internal tool to generate a `Schema.ts` based on the GraphQL schema, and that also works fine with the plugin. In our React components we simply import the relevant types from Schema.ts and use that when accessing the GraphQL types.

I hope this makes things more clear.

**Comment by spentak** [comment]
Ok, so this plugin does _not_ automate the generation of code for the languages that apollo-codegen supports. Got it. Well now I'm wondering of of the advantage of the plugin and writing pure GraphQL models, mostly because Apollo Client does a ton of the heavy lifting. I thought it would be pretty awesome to hit a url, and then have code generated for the client project.

Can you help me understand why and when this plugin would be useful? For instance, on our API we have our schemas created in our TypeScript code, attached to mongodb models.

```
export const slopeType = new GraphQLObjectType({
    name: 'Slope',
    description: 'Slope',
    fields: () => ({
	    id: { type: GraphQLID },
        name: { type: GraphQLString },
	    orderNumber: { type: GraphQLInt },
        skillTracks: {
	        type: new GraphQLList(skillTrackType),
	        resolve(parentValue, args) {
				return getSkillTracksForSlope(parentValue.id);
	        }
        },
    }),
});
```

Can you help me understand how your plugin can add value to our workflow?
