### ISSUE TITLE
Directives declared in schema aren't recognized

### ISSUE THREAD

**Issue by acjay** [jimkyndemeyer/js-graphql-intellij-plugin#117]
I tried to define the following directive:

```graphql
# Nullable because the lookup can fail to find the value for the given
# parameters.
directive @nullableLookup on FIELD
```

and then use it on a field like such:

```graphql
type query {
  item(id!: String): Item @nullableLookup 
}
```

But the plugin is reporting that the directive isn't found. I think I'm declaring it and using it correctly, but I'm not sure.

**Comment by jimkyndemeyer** [comment]
Hi Alan.

This appears to be related to a breaking change in the GraphQL spec for directives.

I'm merging this and related issues into #121
