### ISSUE TITLE
filter is not supported?

### ISSUE THREAD

**Issue by spentak** [jimkyndemeyer/js-graphql-intellij-plugin#119]
I get the error:

`Unknown argument "filter" on field "slopes" of type "Query"`

What am I missing?

```
query GetSlopeByName($name: String) {
    slopes(filter: {
        name: $name
    }) {
        ...basicSlopeData
        skillTracks {
            name
            orderNumber
        }
    }
}
```

**Comment by jimkyndemeyer** [comment]
Hi Mark.

The message here indicates that you don't have a filter argument on the slopes field per your schema.

For general questions about GraphQL, please see http://graphql.org/community/

I'm closing the issue on this basis, as there appears to nothing actionable for the plugin. If that's not the case, ie. you found a bug, please re-open this issue with details to reproduce.

/Jim
