### ISSUE TITLE
ignoring errors in a specific project

### ISSUE THREAD

**Issue by rosskevin** [jimkyndemeyer/js-graphql-intellij-plugin#122]
I pulled and am sending PRs to react-apollo.  I've found they have no schema in the project so my Webstorm is blowing up with errors and makes it difficult to discern typescript errors from graphql errors.

![ts-errors](https://user-images.githubusercontent.com/136564/33853852-1a49fe46-de85-11e7-98be-168636afef33.png)

I don't want to disable the plugin, because that kills it globally, and I quite like this plugin for my application and libraries.

Is there any way to disable this on a per project basis?

**Comment by jimkyndemeyer** [comment]
Hi Kevin.

Thanks for using the plugin.

Unfortunately, there's no way to disable the annotator at the moment. The change required here would be a new settings page which persists its settings to the workspace xml. I'm open to a PR that adds this.

I'm thinking that it would make sense to create a `.graphqls` file to express the schema that tests use. I realise the schema isn't always necessary for a specific test case, but you would gain the autocompletion, find usages, error highlighting etc. while writing the test cases.

**Comment by rosskevin** [comment]
Thanks Jim. I am all for a schema for tests, but in some cases, I'm just trying to PR a fix to some dependent project. I am not ready to cleanse the world of schema-less projects, so I do think an off switch is worthwhile. 

A simpler case would be to add it to the config file instead of a UI preferences pane. While the UI would be nice, it isn't totally necessary to meet the need.

**Comment by NaLLiFFuNT** [comment]
This would be great to have an approach to ignore some files in project by this plugin. 
I have one unit test in my app which is not supposed to use current schema and plugin is constantly alerting me that this file contain some errors. 
```

**Comment by vepanimas** [comment]
In the plugin 3.0 version, you could disable errors either globally or on the project level by configuring GraphQL inspections.
![graphql-inspections](https://user-images.githubusercontent.com/10243762/139599662-1fbdc76d-b822-4970-b795-649d6cf8c8b5.png)

Also, you could suppress a specific error via a default comment-based inspection suppression mechanism.
