### ISSUE TITLE
Fix UTF-8 support in output

### ISSUE THREAD

**Issue by sitnin** [jimkyndemeyer/js-graphql-intellij-plugin#123]
Is it possible to show endpoint reply with UTF-8?

![2017-12-28_20-39-53](https://user-images.githubusercontent.com/115604/34418473-5e8ee2c8-ec0f-11e7-8d2f-f78149140527.png)

**Comment by jimkyndemeyer** [comment]
Hi Gregory.

Thanks for using the plugin.

I've just tried a unicode response using https://launchpad.graphql.com/qmx3nw0n8p and that works as expected.

Can you check that your endpoint response includes the content-type header with utf-8 as charset?

Thanks,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing this as it doesn't appear to be an issue with the plugin.

Please add a comment if you're unable to make it work.

/Jim.
