### ISSUE TITLE
Editor tab loaded on background thread during startup causes dispatch thread assertion error

### ISSUE THREAD

**Issue by Mindavi** [jimkyndemeyer/js-graphql-intellij-plugin#124]
After installing this plugin and restarting the IDE, it crashed on startup. 
This does not seem to occur after a new restart.

I'm on Windows 10.0.16299, using PhpStorm 2017.3.2
Build #PS-173.4127.29, built on December 22, 2017
JRE: 1.8.0_152-release-1024-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

The error message is this: 

> Access is allowed from event dispatch thread only.

[Stacktrace-js-graphql.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/1599731/Stacktrace-js-graphql.txt)
[threadDump.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/1599732/threadDump.txt)

  
[Installed-plugins.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/1599739/Installed-plugins.txt)

**Comment by jimkyndemeyer** [comment]
Hi Rick.

Thanks for reporting this.

It appears to only happen if an editor tab is loaded in the background (not on the Swing UI dispatch thread). I'll include a fix in an upcoming release.

Thanks,
Jim.

**Comment by jimkyndemeyer** [comment]
Hi Rick.

I've fixed this for the upcoming 1.7.0 release which I plan on releasing shortly.

Best regards,
Jim.
