### ISSUE TITLE
Support for getFragment with variables

### ISSUE THREAD

**Issue by janmeier** [jimkyndemeyer/js-graphql-intellij-plugin#126]
Relay.QL relies heavily on getting fragments from other components. Sometimes you have to explictly pass arguments to one of the fragments, like this:

```graphql
fragment on foo {
  ${Screen.getFragment('viewer')}
  ${AccountFilterURL.getFragment('viewer')}
  ${PostSearchFilterURL.getFragment('viewer', {
    accounts: variables.accounts
  })}

  allPosts: posts(first: 1) {
    total
  }
}
``` 

![image](https://user-images.githubusercontent.com/1210224/34874110-05628350-f798-11e7-922d-92eeeb981d6c.png)

The interpolation between ${} can contain any valid javascript, but this plugin is failing to parse it if you pass an object as the second parameter to `getFragment`.

With some guidance I'd like to try to fix this. I guess that the interpolation parts should actually be validated by the regular JS gramar instead of trying to replicate that in this module

**Comment by jimkyndemeyer** [comment]
Hi Jan.

As part of the 2.0 release I added support for tagged template literal placeholders directly in the grammar of the GraphQL parser. It now properly parses and highlights the following:

![image](https://user-images.githubusercontent.com/15837712/56093337-c0f07e00-5ec7-11e9-82af-6aa7c1c96c01.png)

Completion also works as expected.

Best regards,
Jim.

**Comment by janmeier** [comment]
Sweeet! :tada:
