### ISSUE TITLE
Apollo Link State queries not supported

### ISSUE THREAD

**Issue by anselmdk** [jimkyndemeyer/js-graphql-intellij-plugin#129]
[Apollo Link State](https://github.com/apollographql/apollo-link-state) (client state handling for Apollo) uses the `@client` directive for queries that query the local state. They can look like this:

```graphql
query {
  amount @client {
    amount
  }
}
```

These seem to not be supported in the plugin, see attached:

![2018-03-02_10h53_22](https://user-images.githubusercontent.com/1316533/36893338-f51d8c56-1e07-11e8-9e9f-36c85b3d230e.png)

**Comment by stonecold123** [comment]
Is it possible to temporarily ignore the errors from these Apollo Link State's queries ?

**Comment by anselmdk** [comment]
It's just underlining them with red, beyond that everything's fine.

**Comment by scottburch** [comment]
I would argue that underlining them in red is not fine.  That causes the IDE to label the code as invalid.  I rely on that indicator heavily while coding to find syntax mistakes.  Reading the commit comments it looks like a fix for this is in progress?

**Comment by Lavoaster** [comment]
If you add the following into your GraphQL schema, it should prevent this from showing as an error.
```
directive @client on FIELD
```

**Comment by Lavoaster** [comment]
I use [this](https://gist.github.com/zhenwenc/09c9e78faefa4c35bdff6280a010ab810) from [here](https://github.com/apollographql/apollo-codegen/issues/366#issuecomment-372140830).

My slightly modified one is [this](https://gist.github.com/Lavoaster/00d027ebe96dc523e56a876f95300c06), because the source uses the https module and I had a http introspection endpoint.

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha follows the latest GraphQL language draft spec as of June 2018.

As part of that, the plugin will pick up any client fields and directives that you declare as part of your client schema using GraphQL SDL.

Use the `extend` keyword to extend your existing server schema types with client fields.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
Schema directives fixed in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3
