### ISSUE TITLE
Use this plugin on AppCode

### ISSUE THREAD

**Issue by rnitame** [jimkyndemeyer/js-graphql-intellij-plugin#132]
I couldn't find this plugin ... 😂 

![image](https://user-images.githubusercontent.com/4950792/37242048-23ac3532-24a6-11e8-8ad9-f0ecc01871d8.png)

Do you have to use [xcode-graphql](https://github.com/apollographql/xcode-graphql) instead? (´・ω・｀)

**Comment by jtoce** [comment]
Did you try to download the plugin and install manually from disk? You can find it here:
https://plugins.jetbrains.com/plugin/8097-js-graphql
* Note you also need to install the NodeJS plugin which is available.

**Comment by rnitame** [comment]
I could install manually from disk 🙇 
Thanks! @jtoce !
