### ISSUE TITLE
Indenting for aliases looks wrong

### ISSUE THREAD

**Issue by joshstrange** [jimkyndemeyer/js-graphql-intellij-plugin#133]
When I use an alias in my graphql query it auto-formats to this:

````
let myQuery = gql`
    {
        myAlias: MyObject {
        id
        name
    }
    }
`;
````

when I expect it to look like this:
````
let myQuery = gql`
    {
        myAlias: MyObject {
            id
            name
        }
    }
`;
````

Am I missing a setting or something that would allow for my expected formatting?

**Comment by jimkyndemeyer** [comment]
Hi Josh.

Thanks for reporting this.

This appears to be related to shorthand queries. If you use the query keyword the indentation works as expected, e.g.

```
let myQuery = gql`
    query {
        myAlias: MyObject {
            id
            name
        }
    }
`;
```

I'll include a fix in an upcoming release.

**Comment by joshstrange** [comment]
@jimkyndemeyer Thank you! I'll use query {} to fix this for now. Thank you for your fast response!

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha follows the latest GraphQL language draft spec as of June 2018.

It should indent aliased fields correctly.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
Confirmed this indents correctly with v2 alpha-7.
