### ISSUE TITLE
Plugin Installation Error

### ISSUE THREAD

**Issue by ForsakenHarmony** [jimkyndemeyer/js-graphql-intellij-plugin#136]
Just updated the plugin and it doesn't work anymore

![](https://i.imgur.com/3HZ75g7.png)

**Comment by ForsakenHarmony** [comment]
it keeps on happening

**Comment by jimkyndemeyer** [comment]
Then it's likely an issue with the 2018.1 EAP of WebStorm. The plugin doesn't delete the installation directory, so I suggest you try with a stable version of WebStorm.

**Comment by ForsakenHarmony** [comment]
Oh wait nvm, some stale node process was apparently still using the folder

**Comment by jimkyndemeyer** [comment]
Glad you got it working.

I could have clarified that by "restart" I meant Wndows and not just WebStorm, since restarting Windows ensures file locks and unexpected processes are closed down.

**Comment by ForsakenHarmony** [comment]
Oh yeah makes sense 🙈
