### ISSUE TITLE
support extending interfaces

### ISSUE THREAD

**Issue by mattkrick** [jimkyndemeyer/js-graphql-intellij-plugin#137]
Graphql can extend interfaces as well as types, eg `extend interface Person`. This was added just a short while ago: https://github.com/graphql/graphql-js/pull/1222 

i think all that's needed is to move the case up here, but I could be wrong: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/accd108621006da46a0d1bea72b8efde3b1beda3/src/main/com/intellij/lang/jsgraphql/parser/JSGraphQLParser.java#L364

Thank you for the plugin! It's constantly saving me from myself.

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha follows the latest GraphQL language spec as of June 2018.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.
