### ISSUE TITLE
Support plain JS strings and force plugin support

### ISSUE THREAD

**Issue by slorber** [jimkyndemeyer/js-graphql-intellij-plugin#138]
Hi,

Just wondering how to tell your plugin to parse a string as GraphQL when there is no tag/interpolation like `graphql` or `gql`.

Someone mentionned it may be possible in WebStorm to add a comment like `//language=GraphQL` but it does not seem to work in Intellij

Note that a workaround I've found is to create your own string interpolation that does nothing, as it seems any interpolation with `graphql` name will make the plugin parse the string.

```js
const graphql = ([str]) => str;

const getAllTagsQuery = graphql`
    query MyQuery {
        allItems {
            ....
        }
    }
`;

```

Is there any better solution?

See also original twitter discussion: https://twitter.com/sebastienlorber/status/975381321655693314

**Comment by jimkyndemeyer** [comment]
Hi Sébastien.

Thanks for using the plugin.

The best approach here is to declare your own tagged template literal function as you did. This allows the plugin to enable all the features of language injection, including indentation, completion, error highlighting etc. Other approaches such as the language comment only activates syntax highlighting.

My team has a similar approach where we've added a graphql function to our graphql API to enable the plugin.

Best regards,
Jim.

**Comment by slorber** [comment]
thanks :) and thanks for the plugin too
