### ISSUE TITLE
Schema editor marks all as invalid symbols

### ISSUE THREAD

**Issue by GrigoryPtashko** [jimkyndemeyer/js-graphql-intellij-plugin#14]
Hello.

I wanted to create a graphql schema in a scratch file. So I'm opening a GraphQL Schema scratch and input a simple Node interface:

```
interface Node {
    id: ID!
}
```

But the editor marks all except `id` and `ID` as invalid.
Here's the screenshot:

![screenshot 2016-06-19 11 13 51](https://cloud.githubusercontent.com/assets/2768788/16176183/3a4fecee-3618-11e6-8546-91a4dc0ed3ee.png)

Why is that?

Thank you.

**Comment by jimkyndemeyer** [comment]
Hi Grigory.

Thanks for using the plugin.

The schema language isn't supported yet for editing scenarios. The schema scratch file option appears to be an unintended side-effect of introducing support for traditional GraphQL scratch files.

Here more background regarding the schema language support from an earlier issue:

> As it stands, the .graphqls support is considered read-only and requires that a valid parse tree can be created for syntax highlighting. It was added as a means of showing the currently loaded schema that the plugin uses for completion, error highlighting, and for providing find usages etc.
> 
> I logged graphql/codemirror-graphql#14 a short while ago since schema editing would be a useful addition. Until that issue is implemented, you should edit your schema file with another file extension to prevent the errors-as-you-type from popping up the console.

For now, I'll see if the schema scratch file option can be removed until it's fully supported. This should avoid confusing users.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Released in v1.3.2.
