### ISSUE TITLE
Save Schema if pulled from URL

### ISSUE THREAD

**Issue by joshstrange** [jimkyndemeyer/js-graphql-intellij-plugin#140]
Is there anyway currently (or would it be hard to implement) to have the schema pulled via URL saved into the schema file? My problem is that my graphql endpoint requires authentication (api token) the expires every hour. This means that if I check out my code in a new location I need to grab a new token and plop it down in the headers in the config file so that the plugin stops complaining about my queries not being valid.

I can write a script to grab a token and throw it into the config file (for when my schema changes) but I would love it if when you first checkout code it would use the last fetched (and committed to git) schema.

**Comment by fetis** [comment]
This would be nice. In general, authorization topic is not well covered in the plugin. So would like to have a prompt or local variable to provide a token for authorization. #72 relates to this issue.

**Comment by fetis** [comment]
as a temporary workaround, I can suggest a solution to use
`apollo-codegen introspect-schema` to get the schema and story it as .json. You can specify auth header in this command. The plugin must be configured to get the schema from a local file. This works for my case.


Another thing, locally stored schema also can be used for types generation from a schema. So it's not only auth about.

**Comment by joshstrange** [comment]
Thanks, I ended up just writing a script that would have auth and download of schema file and switched over to using file instead of URL-based fetching. https://gist.github.com/joshstrange/3130d1edf0b414b997f75219defc9da6

**Comment by jimkyndemeyer** [comment]
See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

There is now an "Execute introspection query and print GraphQL SDL" line marker next to endpoint urls which saves the schema to the `schemaPath` configured in the `.graphqlconfig`.

**Comment by jimkyndemeyer** [comment]
Hi Josh.

See [remote-schema-introspection](https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection) for how v2 of the plugin supports your use case. You can specific API tokens via environment variables in the `.graphqlconfig` file as described in the  [graphql-config documentation](https://github.com/prisma/graphql-config/blob/master/specification.md#configuring-graphql-endpoint).

If you'd like to help test v2 the releases are found at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases

Best regards,
Jim.
