### ISSUE TITLE
Add Restart Language Service Button to Console

### ISSUE THREAD

**Issue by ibigpapa** [jimkyndemeyer/js-graphql-intellij-plugin#142]
I find i need to switch between the Errors tab and console tab to ensure that the schema gets loaded from the remote correctly.  

It'd be nice if this button was on the same screen where  you can validate that it was loaded correctly.

**Comment by jimkyndemeyer** [comment]
Hi Troy.

The 2.0 alpha shows a "Schemas and Project Structure" panel that features a "Restart schema discovery" button next to the current schema status.

See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases for how to get it.

Best regards,
Jim.
