### ISSUE TITLE
Can't execute queries

### ISSUE THREAD

**Issue by Lughino** [jimkyndemeyer/js-graphql-intellij-plugin#143]
Hi,
thanks for this great plugin.
I'm having some trouble to configure this plugin properly..
This is my current `graphql.config.json` file:

```json
{
  "schema": {
    "file": "packages/graphql-server/src/schema.graphql"
  },
  "endpoints" : [
    {
      "name": "Default (http://localhost:4000)",
      "url": "http://localhost:4000",
      "options" : {
        "headers": {
          "user-agent" : "JS GraphQL",
          "Accept" : "application/json"
        }
      }
    }
  ]
}
```

When I try to execute a query I always receive this error in the query result: `The Query definition is not executable.`

This is my `schema.graphql`:
```graphql
type Query {
    members: [Member!]!
    member(id: ID!): Member!
}

type Member {
    _id: ID!
    firstName: String!
    lastName: String!
    memberName: String!
    email: String!
    title: String!
    phoneNumber: String!
}
```
I don't understand how to configure this plugin in order to execute queries in Intellij 2018.1

**Comment by jimkyndemeyer** [comment]
Hi Luca.

It sounds like you're including the "type Query" part of your graphql schema when you're submitting a query to your endpoint. You should create your executable query in a separate graphql file. The scratch file feature is useful for this if you don't want to save a graphql file in your project for testing out queries.

**Comment by Lughino** [comment]
Hi Jim,
yes I figured out that I was trying to exec a queries inside the wrong file!
Thanks.
