### ISSUE TITLE
Add support for Rider

### ISSUE THREAD

**Issue by waterfoul** [jimkyndemeyer/js-graphql-intellij-plugin#146]
I've installed you plugin (via installing the .zip) into rider and it works great. Since it contains the same features as webstorm and the other ides could you open the repo version to rider?

https://www.jetbrains.com/rider/

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for the heads up. I've enabled it now. You should be able to search for it once you've uninstalled the zip file.

Best regards,
Jim.
