### ISSUE TITLE
The graphql logo is rather large in ts files

### ISSUE THREAD

**Issue by waterfoul** [jimkyndemeyer/js-graphql-intellij-plugin#147]
Looks like this

![image](https://user-images.githubusercontent.com/2756150/38381000-105bca18-38cb-11e8-9162-f7d173708455.png)

Very annoying and occupies tons of space
I've temp solved it by removing the codeInsight.lineMarkerProvider line from the plugin.xml

**Comment by jimkyndemeyer** [comment]
It appears to have picked up the svg version of the icon for the marker.

Which version of IntelliJ are you seeing this in?

**Comment by jimkyndemeyer** [comment]
Fixed in 1.7.1, pending JetBrains approval in the plugin repo.
