### ISSUE TITLE
execute query from file with graphql template string

### ISSUE THREAD

**Issue by dontsave** [jimkyndemeyer/js-graphql-intellij-plugin#149]
Currently it is possible to execute queries in .graphql files, but template string queries (within tsx files for example) while recognized as graphql by the plugin, cannot be executed with control-enter. Would it be possible to add this functionality? The use case I'm working with (Gatsby) does not currently support .graphql files. Queries in Gatsby must be within template strings.

**Comment by jimkyndemeyer** [comment]
Hi dontsave.

Thanks for using the plugin.

IntelliJ has an intention that let's you edit injected languages. With my bindings it's Alt+Enter which calls the "Show intention actions" command. This show something similar to the following.

![image](https://user-images.githubusercontent.com/15837712/38938012-ddafaa26-4324-11e8-93c3-57eb59a65572.png)


Note that as you edit the fragment in the new tab, the text also updates inside the tagged templated.

Let me know how it works out.

Best regards,
Jim.

**Comment by dontsave** [comment]
oh wow. didn't know that. that's fantastic thanks!
