### ISSUE TITLE
"input" does not seem to be supported

### ISSUE THREAD

**Issue by scottburch** [jimkyndemeyer/js-graphql-intellij-plugin#151]
Thanks for this plugin, it has been very helpful.

I am finding that anytime I have a mutation where one of the fields is an input type using gql I get an "unknown type" error.  In the case below, it will be on SomeInputType.

Everything works fine so the input is probably defined properly.

```
const SOME_MUTATION = gql`
    mutation updateSomething($id: ID, $foo: SomeInputType!) {   <-- here is where it will show "unknown type"
        updateSomething(id: $id, foo: $foo) {...}
`;
```

```
input SomeInputType {
    num: Int!
}
```

**Comment by jimkyndemeyer** [comment]
Hi Scott.

Thanks for using the plugin.

Please give the 2.0 beta-1 release a go. Instructions at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Let me know if there's any issues.

Best regards,
Jim.
