### ISSUE TITLE
Multiple graphql-files making up the schema?

### ISSUE THREAD

**Issue by zth** [jimkyndemeyer/js-graphql-intellij-plugin#152]
I'm using Relay Modern, which allows you to define both a server schema and a client schema. These two schema parts are then merged to a single schema used by the Relay compiler. 

Is there any way to make this plugin read and merge multiple schema files into one single schema? I'm not talking about multiple schemas with independent versions like other issues described on the tracker, but rather just having 2 (or more) separate schema files in the same root that are merged and treated as one.

Thanks!

**Comment by jimkyndemeyer** [comment]
Hi Gabriel.

Thanks for using the plugin.

There's no built-in support for this at the moment, but the use case is similar to Apollo Link State. 

You should be able to merge the two schemas based on the discussion at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/129#issuecomment-378680798

Once merged, you can update `graphql.config.json` to point at the combined schema.

Best regards,
Jim.

**Comment by zth** [comment]
Thank you for your reply!
