### ISSUE TITLE
support reading schema from .graphql files

### ISSUE THREAD

**Issue by ilackarms** [jimkyndemeyer/js-graphql-intellij-plugin#155]
so far it looks to me as though this plugin requires rewriting graphql schema syntax to json... is this correct?

**Comment by jimkyndemeyer** [comment]
Hi Scott.

GraphQL IDL is already supported with the `file` option in `graphql.config.json`. See the readme: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/230ba7eb4fe93c7244e91f6f9d1f0258d0935553/resources/META-INF/graphql.config.json#L6

It was added to support Relay Modern projects.

**Comment by ilackarms** [comment]
thanks!
