### ISSUE TITLE
Support descriptions

### ISSUE THREAD

**Issue by estaub** [jimkyndemeyer/js-graphql-intellij-plugin#157]
[The graphql spec](http://facebook.github.io/graphql/draft/#sec-Descriptions) describes how a quoted string (including block quotes) can be used as a description.

graphql-cli now emits block-quoted descriptions in schema.

**Comment by SPAHI4** [comment]
I also have a syntax error on it with `relay-compiler`

**Comment by tamlyn** [comment]
Duplicate of #118

**Comment by jimkyndemeyer** [comment]
Supported in v2. Closing as duplicate of #118
