### ISSUE TITLE
Fragments from external file are not recognized

### ISSUE THREAD

**Issue by lehresman** [jimkyndemeyer/js-graphql-intellij-plugin#159]
We're using graphql-tag/loader to parse and load the graphql queries with webpack.  This plugin works great, except it doesn't recognize the external fragments.

<img width="473" alt="screen shot 2018-05-22 at 8 42 36 pm" src="https://user-images.githubusercontent.com/96005/40397459-ea79e22a-5e00-11e8-9960-2261b055c5ef.png">

Is this a bug, known issue, or am I just doing something wrong?  Alternatively, is there a way to disable that error message?

**Comment by jimkyndemeyer** [comment]
Hi Luke.

Thanks for using the plugin.

See #43 for an existing discussion of this.

It might make sense to add an option to ignore the unknown fragments for projects that use a build setup that the plugin doesn't recognize, so I'll keep this issue open.

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha release resolves fragments using Intellij/WebStorm "Scopes". By default, it should locate all fragments in your project.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
Please try https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

It resolves all fragments available in a project.

Let me know if you have any issues.

Best regards,
Jim.
