### ISSUE TITLE
Conflicts with TypeScript syntax highlight

### ISSUE THREAD

**Issue by Axure** [jimkyndemeyer/js-graphql-intellij-plugin#16]
When this plugin is enabled, many of TypeScript syntax highlights do not function normally.

See this issue: [WEB-22021 TypeScript is not highlighted correctly.](https://youtrack.jetbrains.com/issue/WEB-22021)

**Comment by jimkyndemeyer** [comment]
Thanks for reporting this.

I've just confirmed that removing the TypeScript annotators from plugin.xml resolves the conflict. It's unclear why it's a conflict, but I'll investigate further.

/Jim.

**Comment by jimkyndemeyer** [comment]
Logged https://youtrack.jetbrains.com/issue/WEB-22416 with JetBrains. Appears that simply adding an additional TypeScript annotator somehow breaks existing functionality.

**Comment by jimkyndemeyer** [comment]
This is fixed by JetBrains in [WEB-22416](https://youtrack.jetbrains.com/issue/WEB-22416) for Webstorm/IntelliJ 2016.2.2.
