### ISSUE TITLE
Anonymous operation definitions with variable definitions do not parse

### ISSUE THREAD

**Issue by Yogu** [jimkyndemeyer/js-graphql-intellij-plugin#165]
Affects 2.0.0-alpha-3.

```graphql
query($id: ID!) {
  test(id: $id) {
    id
  }
}
```

This [should be a valid GraphQL document](http://facebook.github.io/graphql/June2018/#OperationDefinition), but generates the error `<definition> expected, got 'query'`. graphql-js parses this just fine. It [looks fine in the antlr definition of graphql-java](https://github.com/graphql-java/graphql-java/blob/master/src/main/antlr/GraphqlOperation.g4#L6), but maybe it's a bug there anyway.

**Comment by jimkyndemeyer** [comment]
Thanks for this.

The fix will be in the next alpha.
