### ISSUE TITLE
[v2] Support extending input types

### ISSUE THREAD

**Issue by PiotrSzlagura** [jimkyndemeyer/js-graphql-intellij-plugin#167]
When I try to type:
```graphql
extend input InputTypeName {
  ...
}
```
the plugin sees it as an error, even though it is a valid operation in graphql.

Is it possible that I have to change some configuration etc, or it's just that it is not supported by the plugin yet?

**Comment by jimkyndemeyer** [comment]
Extend is supported in v2 which is currently in alpha: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3
