### ISSUE TITLE
Tool window always shows on startup

### ISSUE THREAD

**Issue by vjpr** [jimkyndemeyer/js-graphql-intellij-plugin#171]
It should not show the tool window on startup.

**Comment by sztadii** [comment]
This is very annoying, because each time I have to close it 😞

**Comment by camsjams** [comment]
I thought I was the only one annoyed by this. If you open up *any* file with a `*.js` extension, the GraphQL tool window opens up.

**Comment by jimkyndemeyer** [comment]
Version 2 of the plugin no longer has this behaviour. See installation instructions at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Best regards,
Jim.

**Comment by camsjams** [comment]
Awesome! Thanks!
