### ISSUE TITLE
[Feature] Add "Restart Language Service" intention?

### ISSUE THREAD

**Issue by hailwood** [jimkyndemeyer/js-graphql-intellij-plugin#172]
Hey @jimkyndemeyer,

I was wondering if we could add a new intention to restart the language service on any "cannot query field..." errors in a graphql file?

90% of the time when I'm bringing up the console it's simply to restart the language service because I added a new field, would be great if I could just quickly do it from the error itself!

I know I could add a keyboard shortcut, but I love contextual intentions better.

**Comment by jimkyndemeyer** [comment]
Hi Matthew.

Have you tried the v2 alpha of this plugin yet? Query completion and error highlighting updates instantly based on schemas authored using GraphQL SDL.

See #164 and https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

**Comment by hailwood** [comment]
Hey @jimkyndemeyer,

I'm glad you pointed that out, I hadn't up until this point used the v2 alpha,
I've now logged a separate issue against it :)

In my case this projects schema isn't written in SDL, which is probably going to be quite common for using this plugin as https://github.com/webonyx/graphql-php is the main backbone of a lot of the integrations. Meaning that schema introspection is the only way to get the SDL.

Unfortunately with the v2 rewrite, this has actually become more of an issue, as I now need to navigate to my .graphqlconfig file, and click the "run" arrow in the gutter to update the schema. 

So for v2, would it be possible to add the intention to rerun the introspection query?

**Comment by jimkyndemeyer** [comment]
Hi Matthew.

The latest v2 alpha features an action to re-run the latest introspection query. See the double green arrow button in the GraphQL "Schemas and Project Structure" panel. You can bind a keyboard shortcut to this action.

Also, if you set `"introspect": true` in your config: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/075f238474bd01eaea0e2ce6e5bd37bdbd4ca4dc/resources/META-INF/.graphqlconfig#L5-L11  the plugin will show a notification at project startup that allows you to perform the introspection query.

It should make it much easier to work with remote schemas.

Best regards,
Jim.
