### ISSUE TITLE
[feature] Extension points for directives

### ISSUE THREAD

**Issue by olivernybroe** [jimkyndemeyer/js-graphql-intellij-plugin#174]
Hello,
We have a plugin which is using SDL for making a graphQL server in PHP called [Lighthouse](https://github.com/nuwave/lighthouse).
For this we would like to make a plugin to support our architecture, but we would like to depend on your system. 
Is there an way we can inject directives into your system? Like with an extension point or something similar?

**Comment by jimkyndemeyer** [comment]
Hi Olivier.

I'm not sure I follow.

What do you mean by "inject directives into your system"? I think a more concrete use case or example of what you need the plugin to do can help me understand what you mean.

**Comment by olivernybroe** [comment]
@jimkyndemeyer So our package to PHP uses SDL with server side directives.
We want to be able to add support for our server side directives when using your plugin.

These directives are dynamic, so they can change depending on some php class files. Of course we know that this means we need to make our own plugin and use this plugin.

However how can we add these server side directives into your system? Is there a way to do it already?

**Comment by olivernybroe** [comment]
Yep the `completion.contributor `and `annotator` is prob. the way to go :) Thanks!
