### ISSUE TITLE
How to split one schema file into multiple files?

### ISSUE THREAD

**Issue by yaquawa** [jimkyndemeyer/js-graphql-intellij-plugin#177]
Hi.

I'm using the `#import` comment to split my schema file into chunks.

```
#import ./user-types.graphql
#import ./scalar-types.graphql

...
```

But this cause the plugin throw errors unless I merge them into a single file.
Is there any way to make this work correctly?
Thanks!

**Comment by yaquawa** [comment]
I'm so sorry… I found this actually works‥ !

**Comment by jimkyndemeyer** [comment]
Closing this as no action is required.
