### ISSUE TITLE
Improve handling of local GraphQL Servers

### ISSUE THREAD

**Issue by fforw** [jimkyndemeyer/js-graphql-intellij-plugin#179]
When working with projects that create a GraphQL endpoint, I always run into the problem that at the time the IDE starts the plugin, the GraphQL service that is configured is clearly not running yet, so the schema can't be fetched.

Then when I start the project's server, I can refresh the plugin and it works.

My question is, couldn't it be done to skip the "refresh" step? If you have a situation where you have no valid schema because attempts to fetch it failed, why doesn't the plugin just try to refetch the schema before executing a query or opening the human-readable schema document?

It seems that, with the way GraphQL works as "API for your app", this situation has to occur quite often.

**Comment by jimkyndemeyer** [comment]
Hi Sven.

Thanks for using the plugin.

v2 of the plugin changes the server "fetching" workflow to be either a schema that is defined in the project, or a graphql file that is saved based on running an introspection query. This way, the project works as expected.

More info about v2 at #164 

You can get the v2 (currently in alpha) from https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

**Comment by jimkyndemeyer** [comment]
Hi Sven.

The v2 alpha features a notification during project startup that asks whether to perform the introspection now. Once you've clicked the action to perform the introspection, you can re-run it easily later using the re-run action in the "Schemas and Project Structure" panel. The action can be bound to a keyboard shortcut of your preference.

See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases for how to get v2 release.

I hope that solves your use case.

Best regards,
Jim.
