### ISSUE TITLE
Plugin broke on the latest update of the Intellij IDEA

### ISSUE THREAD

**Issue by GrigoryPtashko** [jimkyndemeyer/js-graphql-intellij-plugin#18]
Here's the version

![screenshot 2016-08-12 13 37 45](https://cloud.githubusercontent.com/assets/2768788/17620416/45d0a798-609d-11e6-887c-b74481e51f26.png)

Here's what's showing

![screenshot 2016-08-12 13 37 20](https://cloud.githubusercontent.com/assets/2768788/17620426/52b25178-609d-11e6-94e7-07e8d373fd34.png)

That's a pity :(

**Comment by jimkyndemeyer** [comment]
Hi Grigory.

Thanks for catching this. I'll take a look.

/Jim.

**Comment by jimkyndemeyer** [comment]
@GrigoryPtashko I do see an exception in the EAP when the Kotlin plugin tries to access the schema file, but I'm still able to expand the "GraphQL Schemas" tree node.

Can you add a stack trace? It should be available from the blinking red error icon in the right-hand side of the IntelliJ IDEA status bar.

**Comment by jimkyndemeyer** [comment]
I just released v1.3.3 which should fix the compatibility issue.

@GrigoryPtashko Let me know if the fix doesn't work. I couldn't replicate the behaviour shown in your screenshot.
