### ISSUE TITLE
Fix UTF-8 support in output

### ISSUE THREAD

**Issue by bokgun** [jimkyndemeyer/js-graphql-intellij-plugin#181]
#123 

i saw that issue.
but, the content-type of `application/json` is fixed to UTF-8.
and doesn't allow a charset parameter

http://tools.ietf.org/html/rfc7158#section-11

**Comment by WinjayYu** [comment]
I also encountered this problem.

**Comment by jimkyndemeyer** [comment]
Fixed in v1.7.3 pending JetBrains approval.
