### ISSUE TITLE
Introspection Query not being run

### ISSUE THREAD

**Issue by Tam** [jimkyndemeyer/js-graphql-intellij-plugin#182]
## Version and Environment Details
__Operation system__:  macOS High Sierra

__IDE name and version__: WebStorm 2018.2.3

__Plugin version__: 1.7.2

## Expected Behaviour
Introspection Query should be run and schema file should be updated.

## Actual Behaviour
Nothing happens.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
I was using a local schema file, but I switched to using the introspection query to save me having to update the schema file every time there was a change.

My `graphql.config.json` file:
```json
{
  "schema": {
    "request": "[...]/graphql",
    "method": "POST",
    "postIntrospectionQuery": true
  },
  "endpoints": [
    {
      "name": "API",
      "url": "[...]/graphql"
    }
  ]
}
```

The console output:
```
/usr/local/bin/node --no-deprecation "/[...]/Application Support/WebStorm2018.2/js-graphql-intellij-plugin/js-graphql-language-service.dist.js" --port=51815
JS GraphQL listening on http://127.0.0.1:51815/js-graphql-language-service
Setting Project Dir '/[...]'
Watching '/[...]/graphql.config.json' for changes.
```
I've tried pressing the "Restart JS GraphQL Language Service" button but nothing seems to happen.

**Comment by jimkyndemeyer** [comment]
Hi Tam.

Thanks for using the plugin.

The "request" configuration field is expected to be an object. See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/32d6739161077e95cc2b91937cb221c3553ee2ee/resources/META-INF/graphql.config.json#L10-L20

I'm closing this but feel free to comment if this doesn't resolve the issue.

**Comment by Tam** [comment]
Ahhh yep, thanks!
