### ISSUE TITLE
Dynamic headers

### ISSUE THREAD

**Issue by kcrimi** [jimkyndemeyer/js-graphql-intellij-plugin#184]
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/32d6739161077e95cc2b91937cb221c3553ee2ee/resources/META-INF/graphql.config.json#L31

Hi I have to pass up a user's session as a Cookie header to my api in order to authenticate the user. I'm currently just placing this in the `headers` object in the `graphql.config.json` which is working but I was wondering if you had any ideas for doing this more dynamically to accomplish 1 or both of the following:
1. I'd like to hit a login endpoint and use the value returned from that
2. I'd like to have a way to parameterize the `graphql.config.json` so I don't have to edit it so often and possibly commit it to the repo

thanks!

**Comment by jimkyndemeyer** [comment]
Closing this now that the plugin supports graphql-config with environment variables that it preserves while a project is open.

Best regards,
Jim.
