### ISSUE TITLE
With Goland 2018.2 and 2018.3 editor has just one color!

### ISSUE THREAD

**Issue by frederikhors** [jimkyndemeyer/js-graphql-intellij-plugin#187]
With Goland 2018.2 and 2018.3 editor has just one color!

In 2018.2 sometimes doesn't work, sometimes works! Random!

**Comment by jimkyndemeyer** [comment]
Seems related to #158.

If you experience this kind of behaviour, please give the v2 alpha a try:

- #164 
- https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases

**Comment by jimkyndemeyer** [comment]
Fixed in v1.7.3 as part of #158 pending JetBrains approval.
