### ISSUE TITLE
Schema won't be fetched from endpoint due to unicode characters in path

### ISSUE THREAD

**Issue by jantajov** [jimkyndemeyer/js-graphql-intellij-plugin#188]
Following configuration is used to fetch schema from endpoint:

```
{
  "schema": {
    "request": {
      "url" : "http://192.168.210.22:81",
      "method" : "POST",
      "postIntrospectionQuery" : true
    }
  }
}
```

It doesn't fetch anything. I tried to restart service multiple times. always ends with
```
JS GraphQL listening on http://127.0.0.1:55409/js-graphql-language-service
Setting Project Dir xyz
```

## Version and Environment Details
__Operation system__: 
Windows 10

__IDE name and version__: 
WebStorm 2018.2.5

__Plugin version__: 
1.7.2

## Expected Behaviour
Fetch schema successfully or throw an error

## Actual Behaviour
Does not fetch schema at all and gives no error

**Comment by jimkyndemeyer** [comment]
Hi Jan.

Thanks for using the plugin.

Can you create and link to a minimal project that reproduces this? Otherwise this really isn't actionable.

Thanks,
Jim.

**Comment by jantajov** [comment]
[test-řšč.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/2579644/test-rsc.zip)

Just extract and open. Unicode character in folder name will break it.

**Comment by jantajov** [comment]
Hi Jim.

Is this issue scheduled to be fixed in the upcoming 2.x version of the plugin?

**Comment by jimkyndemeyer** [comment]
Hi Jan.

I't very likely that this should work just fine in v2 but I haven't had the chance to verify it yet.

If you'd like to help test it, please take a look at the v2 release in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Hi Jan.

I took a look at the zip file you attached, and it works without issue in my testing of 2.0.0-alpha-8.

Best regards,
Jim.
