### ISSUE TITLE
All queries marked as @deprecated

### ISSUE THREAD

**Issue by vasilich6107** [jimkyndemeyer/js-graphql-intellij-plugin#189]
## Version and Environment Details
__Operation system__: MacOS Mojave 10.14

__IDE name and version__: Intelij IDEA Ultimate 2018.2

__Plugin version__: 1.7.2

## Expected Behaviour
Schema displayed as it defined in repository https://tppr.me/vu5IA

## Actual Behaviour
All items are marked as @deprecated https://tppr.me/n2KCi

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Private repo, sorry

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for using the plugin.

Given that this hasn't been reported by other developers, It's likely that the schema information that is passed to the plugin contains the deprecated directives on the fields.

To make this issue actionable, please attach your `graphql.config.json` file.

**Comment by jimkyndemeyer** [comment]
Closing this until actionable. Feel free to add additional comments with steps to reproduce.
