### ISSUE TITLE
Support for @includes annotation

### ISSUE THREAD

**Issue by brene** [jimkyndemeyer/js-graphql-intellij-plugin#19]
![image](https://cloud.githubusercontent.com/assets/4989523/17642841/3cd83246-6156-11e6-95a3-cf4da2fc7b51.png)
Currently if I use the @includes notation, the parser says that the notation is wrong even though it shows no issues during runtime.

**Comment by jimkyndemeyer** [comment]
Hi Rene.

Thanks for catching this. I'll take a look.

/Jim.

**Comment by jimkyndemeyer** [comment]
This appears to be related to [graphql/pull/152](https://github.com/facebook/graphql/pull/152).

It looks like a potential fix is to update graphql-js in the language service to the latest version, but there's been API and spec changes since 0.5.0.

I'll let you know how it goes.

/Jim.

**Comment by jimkyndemeyer** [comment]
Fixed in #22 for release in v1.4.0
