### ISSUE TITLE
support for "graphql-import"?

### ISSUE THREAD

**Issue by victory1908** [jimkyndemeyer/js-graphql-intellij-plugin#192]
Hi, is there support for `graphql-import`? like bellow in schema.graphql?

`# import UserConnection from 'generated/prisma-client/prisma.graphql'`

got the following error: 

`Unable to load GraphQL schema from "/Volumes/Data/OneDrive/Learning/GraphQL/Code/prisma-examples-master(20181027)/typescript-graphql-auth-advanced/src/schema.graphql": Type "UserConnection" not found in document.`

GraphQL server is still working fine. That means import by `graphql-import` is working normally

**Comment by jimkyndemeyer** [comment]
Hi Vinh.

Thanks for using the plugin.

There's an increasing number of different approaches to imports in the ecosystem, but none of them have been adopted into the GraphQL Specification which this plugin aims to support.

With your setup I recommend that you use an introspection query against your running GraphQL server to let the plugin know how your schema is structured. Use the following options in your `graphql.config.json`: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/32d6739161077e95cc2b91937cb221c3553ee2ee/resources/META-INF/graphql.config.json#L10-L14

Given that there are already open issues on supporting imports I'm closing this issue. Let me know if you have any issues or questions regarding the introspection query configuration.

Best regards,
Jim.
