### ISSUE TITLE
Schema export

### ISSUE THREAD

**Issue by flyhigh-hifi** [jimkyndemeyer/js-graphql-intellij-plugin#193]
Hi! I'm working with GraphQL and see benefits from export to .graphqls you've made to track diff between schemas. But it's built-in in IDE and I cannot add a kind of pre-commit hook for it or run in terminal. Are there any ways to run it as separate tool?

Apollo has [issue](https://github.com/apollographql/apollo-tooling/issues/194) on exporting to .graphql but it doesn't seem to be active or developed.

**Comment by jimkyndemeyer** [comment]
Hi Mark.

Thanks for using the plugin.

If I'm understanding your use case correctly, you have a running GraphQL endpoint, but the schema is not expressed using Schema Definition Language (SDL).

If that's the case, take a look at https://blog.apollographql.com/three-ways-to-represent-your-graphql-schema-a41f4175100d which describes how to convert between the different schema representations. Based on that you should be able to setup a script for a pre-commit hook.

As an alternative, v2 alpha of the plugin can create a `.graphql` file which describes your schema using SDL by running an introspection query against your endpoint. If you'd prefer that approach, see https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3 but note that doesn't allow for integration with git hooks.

Let me know if you have any questions.

Best regards,
Jim.
