### ISSUE TITLE
Unknown directives

### ISSUE THREAD

**Issue by mghaigh** [jimkyndemeyer/js-graphql-intellij-plugin#194]
Hi, I suspect I am missing something simple but all the Relay directives I am using are being marked as unknown; I have seen issue #108 which indicates the directives should work. I am using v 1.7.2 of your plugin with WebStorm. Any suggestions gratefully received.
Thanks, Martin

**Comment by jimkyndemeyer** [comment]
Hi Martin.

Thanks for trying the plugin.

I realize it's not easy to follow the thread of linked closed issues, but v1 still shows the directives as unknown. 

V2, currently in Alpha, will support directives such as those used by Relay natively based on built-in schema discovery and directives expressed using the GraphQL Schema Definition Language.

I hope to release a v2 Alpha with built-in Relay support within a couple of weeks. You can follow the progress at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/164#ref-commit-75c4386

Best regards,
Jim.
