### ISSUE TITLE
Android Studio installation failed due to nodejs dependency

### ISSUE THREAD

**Issue by ollie72** [jimkyndemeyer/js-graphql-intellij-plugin#195]
I tried following these installation instructions with Android Studio v3.2 Mac:

```
1. File | Settings | Plugins
2. Search for: nodejs and graphql
3. Install both plugins and Restart
```

I installed the plugin from the Android Studio branch ok, but on searching the Android Studio plugins for `nodejs` I cannot see that plugin listed. If I download it from the web repository and try to install from disk I see "Plugin NodeJS is incompatible with this installation". Node is installed and working on the command line.

The plugin then fails at IDE-start with:

```
Plugin Error
Problems found loading plugins:
Plugin "JS GraphQL" was not loaded: required plugin "JavaScript" not installed.
```

I cannot see a plugin in the Android Studio plugins repository called "JavaScript".  It looks like a plugin included with many editions of IntelliJ, but apparently not Android Studio. The IDE plugin looks awesome and I'd really appreciate being able to use it from Android Studio but cannot see what needs doing in order to get it up and running.

**Comment by jimkyndemeyer** [comment]
Hi Ollie.

Thanks for trying out the plugin.

You have two options for using the plugin from Android Studio:

- Experimental support for Android Studio is available in the [android-studio](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio) branch. Download it from there via the links at the bottom of the page. Note that this is a pretty old version, and somewhat limited.
- v2 which is currently in Alpha doesn't have a dependency on JavaScript and Node.js, so it also works in Android Studio. See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-3

Best regards,
Jim.
