### ISSUE TITLE
[v2] Incorrect type redefine inspection

### ISSUE THREAD

**Issue by wutsch0** [jimkyndemeyer/js-graphql-intellij-plugin#197]
Hi,
I am using v2.0alpha since a few weeks now and it works great.
The only bug I encountered so far is that one of our defined types is reported as redefinition of an existing type although it is not true.
![type-redefined-inspection](https://user-images.githubusercontent.com/5646364/49812901-b5991480-fd66-11e8-9ab7-0562aac1a00e.png)

The project contains only one GraphQL schema file (schema.graphql), and the line 36 in which the redefined type should be is actually empty. If I edit the schema by putting random type definitions before line 36, the inspections keeps reporting line 36 as the reference.

## Version and Environment Details
__Operation system__: Xubuntu 16.04
__IDE name and version__: PhpStorm 2018.3.1
__Plugin version__: v2.0.0-alpha-3

**Comment by jimkyndemeyer** [comment]
Hi Sebastian.

Thanks for helping test the alpha.

Can you make a minimal reproduction of this as I haven't seen the issue locally.

Best regards,
Jim.

**Comment by wutsch0** [comment]
Hi Jim,

sorry for bothering you.
I found there is another schema file of an external dependency in our project which contains
```
union Feed = Story | Article | Advert
```
 in its line 36
