### ISSUE TITLE
Help getting started (tutorial possible?)

### ISSUE THREAD

**Issue by spencersmb** [jimkyndemeyer/js-graphql-intellij-plugin#199]
Hello,
I'm new to GraphQL and I'm having issue with my setup and wondering if there is a walkthrough or tutorial to make sure I've done it correctly. I'm using react-apollo and my backend is completely separate from my front-end so I'm not 100% sure on how to tell my frontend about the structure of the schemas. Any help greatly appreciated!
 
-Spencer

**Comment by jimkyndemeyer** [comment]
Hi Spencer.

Thanks for trying the plugin.

The following is for v1 of the plugin available in the JetBrains plugin repository.

With v1, the easiest way of getting started is to activate the plugin by viewing or editing GraphQL. This can be done by creating a GraphQL scratch file, or using tagged templates such as `gql` or `graphql` in your React components. From there the plugin should ask you to create a graphql.config.json file that allows you to point the plugin towards your endpoint to discover your schema.

The faq at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq should help you from that point.

Hope that helps.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing this based on v2 docs at https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/getting-started
