### ISSUE TITLE
Support of gql tagged template strings

### ISSUE THREAD

**Issue by geshido** [jimkyndemeyer/js-graphql-intellij-plugin#20]
Hello,

Apollo's 'react-apollo' module allows a developer to write queries in HOC parameter tagging them as gql``.
Is it possible to automatically parse these strings as graphql queries?
An example of component wrapped by react-apollo's connect HOC:

```js
import React from 'react';
import {connect} from 'react-apollo';

class MyComponent extends React.Component {
....
}

export default connect({
  mapQueriesToProps: () => ({
    data: {
      query: gql`
             query MyComponentQuery($param: String!) {
                someData(param: $param) {
                   someNestedData
                }
             }
      `,
      variables: {
         param: 'value'
      }
    }
  })
})(MyComponent);
```

**Comment by geshido** [comment]
Sorry, as a workaround I can add comment just above query string to turn injection on:
```
// language="GraphQL"
```

**Comment by jimkyndemeyer** [comment]
@geshido Just a heads up that v1.4.1 now supports gql out of the box (#25)

/Jim.
