### ISSUE TITLE
Doesn't support template strings with generic types (TypeScript)

### ISSUE THREAD

**Issue by RevanScript** [jimkyndemeyer/js-graphql-intellij-plugin#200]
## Version and Environment Details
__Operation system__: OS X (10.14)

__IDE name and version__: WebStorm (2018.3)

__Plugin version__: 1.7.2

## Expected Behaviour

Should highlight the code with generic types as well:

```typescript
gql<string>`
    query getNotifications($offset: Float!) {
        notifications(scopes: [ASSISTANT], status: [READ, UNREAD], offset: $offset, limit: 10) {
            id,
            title,
            description,
            created,
            status
        }
    }
`
```

## Actual Behaviour

It doesn't. Code looks like a simple string:

<img width="827" alt="2018-12-30 16 24 09" src="https://user-images.githubusercontent.com/5047628/50548087-70724f00-0c4f-11e9-8e9f-d2a06852c4c7.png">

Everything works fine if I remove generic type `<string>`:

<img width="827" alt="2018-12-30 16 27 48" src="https://user-images.githubusercontent.com/5047628/50548105-dc54b780-0c4f-11e9-96b9-cdc0f84a5885.png">

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

Install TypeScript ~ V3. Support for generics in template strings was implemented recently.

**Comment by jimkyndemeyer** [comment]
Hi Eugene.

Thanks for catching this. It's fixed in the upcoming 2.1.1 release.

Best regards,
Jim.
