### ISSUE TITLE
[v2] Merged schemas conflict. Query type tried to redefine existing Query type.

### ISSUE THREAD

**Issue by ph55** [jimkyndemeyer/js-graphql-intellij-plugin#201]
Updated to latest version for string literals.
But now getting error for `Query` override.

I'm using different schemas files that then being merged by `grpahql-tools` .

## Version and Environment Details
__Operation system__:  `macOS 10.14.2`
__IDE name and version__:  `PhpStorm 2018.1.7`
__Plugin version__:  `2.0.0-alpha-3`

## Expected Behaviour
Shouldn't throw error

## Actual Behaviour
`user.gql`
![image](https://user-images.githubusercontent.com/1386622/50642618-6795bc00-0f74-11e9-9aee-b30b2ecda788.png)

![image](https://user-images.githubusercontent.com/1386622/50642182-06211d80-0f73-11e9-94bd-8891c1fcad41.png)

Probably conflicting `config.gql`:
```gql
scalar JSON

type Query {
  config(name: String): JSON
}
```

---

Doesn't work neither with `.graphqlconfig`:
```json
{
  "includes": [ "*.gql" ]
}
```

Nor with scope:
![image](https://user-images.githubusercontent.com/1386622/50645931-746add80-0f7d-11e9-98ba-e9dc6c9b4a11.png)

**Comment by ph55** [comment]
> The plugin appears to have discovered a definition of the Query type in more than one location.

Exactly.

But this shouldn't be the issue.
Because there is such thing as schema stitching.
You could have many `Query` types in separate files that merged.
https://www.apollographql.com/docs/graphql-tools/schema-stitching.html

Here the repo:
https://github.com/ph55/js-graphql-intellij-plugin-201

**Comment by jimkyndemeyer** [comment]
Hi Alex.

Ah, I didn't catch that schema stitching was involved.

For this use case the plugin can't automatically discover what your effective schema is using GraphQL files containing SDL since schema stitching can rename types, move fields etc.

What you'll need to do is to use introspection to let the plugin discover your fully stitched schema, and ensure that your config only includes the files where you will be consuming the stitched schema, e.g. in your components.

So, depending on your project structure you may need .graphqlconfig files for:
- Schema "A" if you'd like the plugin to help with completion, errors etc. inside "A"
- Schema "B" if you'd like the plugin to help with completion, errors etc. inside "B"
- Your client code where you consume the "A+B" stitched schema using components

You should be able to make this work. See https://github.com/prisma/graphql-config#specifying-includesexcludes-files 

Once you've configured "A+B" with the URL for your stitched endpoint, you can click the green arrow in the editor gutter in the config editor, and it will write the introspection result to the file specified in "schemaPath". Then make sure that you use "include"/"exclude" so "A" and "B" are not discovered where you'll be using the stitched schema.

Hope that helps.

Best regards,
Jim.

**Comment by ph55** [comment]
Such an overkill, Jesus.
All I wanted is some GraphQL schema syntax highlighting and format.

**Comment by ph55** [comment]
Thanks for trying to help though @jimkyndemeyer 
Really appreciate it. 

Great plugin overall but too complicated.

**Comment by ph55** [comment]
Thanks for help.
Really appreciate it.

I've implemented the flow you described - https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/201#issuecomment-451404723

Seems like 'Query' error is gone but there is another error now.
`User` type can't recognise `Country` imported from another folder.

**User**

> .graphqlconfig

```json
{
  "includes": ["../country/*.graphql", "*.graphql"]
}
```

> user.graphql

```gql
type Query {
  user(id: ID!): User
  users: [User]
}

type User {
  id: ID!
  email: String!
  username: String!
  firstName: String
  lastName: String
  phone: String
  country: Country!
}
```

**Country**

> .graphqlconfig
```json
{
  "includes": ["*.graphql"]
}
```

> country.graphql

```gql
type Country {
  id: ID!
  name: String!
  iso2: String!
  iso3: String!
  isoNum: Int!
  phoneCode: Int!
  isBlocked: Int!
}
```

![image](https://user-images.githubusercontent.com/1386622/50737083-de79c180-11cd-11e9-977d-f9aa76828b99.png)

Repo is the same:
https://github.com/ph55/js-graphql-intellij-plugin-201

**Comment by ph55** [comment]
Found solution.
It works with single `.graphqlconfig` file with devision to projects inside:

```json
{
  "projects": {
    "config": {
      "includes": ["./config/*.graphql"]
    },
    "user": {
      "includes": ["./country/*.graphql", "./user/*.graphql"]
    }
  }
}
```

**Comment by ph55** [comment]
Ok. Another issue popped up.

If any of components depends on the type of another component - Query error will be thrown as well.

Example:
`Trader` depends on `User` type.
Both `Trader` and `User` have `type Query` definition.

> .graphqlconfig
```json
{
  "projects": {
    "user": {
      "includes": ["./country/*.graphql", "./user/*.graphql"]
    },
    "trader": {
      "includes": ["./user/*.graphql", "./trader/*.graphql"]
    }
  }
}
```

> User.graphql
```gql
type Query {
  user(id: ID!): User
  users: [User]
}

type User {
  id: ID!
  email: String!
  username: String!
  firstName: String
  lastName: String
  phone: String
  country: Country!
}
```

> Trader.graphql
```gql
type Query {
  trader(id: ID!): Trader
  traders: [Trader]
}

type Mutation {
  register(input: TraderRegisterInput!): Trader
}

type Trader {
  id: ID!
  user: User!
}

input TraderRegisterInput {
  email: String!
  password: String!
  currency: String!
}
```

Error:
![image](https://user-images.githubusercontent.com/1386622/50896656-5d5f3c00-1412-11e9-9d48-bce3a3c6e645.png)

Repo is the same:
https://github.com/ph55/js-graphql-intellij-plugin-201

---

Maybe we could think about more simple and more maintainable way to handle merged schemas.
I think it will be relevant for large scale applications.

**Comment by ph55** [comment]
Ok. So I found the proper way to handle this. 
Via extend !

> .graphqlconfig
```json
{
  "schemaPath": "./root.graphql",
  "projects": {
    "app": {
      "includes": [
        "./config/*.graphql",
        "./country/*.graphql",
        "./user/*.graphql",
        "./trader/*.graphql"
      ]
    }
  }
}
```
> root.graphql
```gql
scalar JSON

type Query
type Mutation
```

> trader.graphql
```gql
extend type Query {
  trader(id: ID!): Trader
  traders: [Trader]
}

extend type Mutation {
  registerTrader(input: TraderRegisterInput!): Trader
}

type Trader {
  id: ID!
  user: User!
}

input TraderRegisterInput {
  email: String!
  password: String!
  currency: String!
}
```

Repo is the same:
https://github.com/ph55/js-graphql-intellij-plugin-201

**Comment by ktersius** [comment]
@ph55 If I may ask how did you combine your graphql files into one schema?

I'm currently using https://github.com/prisma/graphql-import but they don't seem to support extend.
https://github.com/prisma/graphql-import/issues/42

**Comment by ph55** [comment]
@ktersius Sure. I'm using NestJS framework which handles schema stitching. I think it's supported by default in Apollo graphql server.
You can check it's module here: https://github.com/nestjs/graphql

**Comment by ktersius** [comment]
@ph55 Thanks. I ended up using https://github.com/Urigo/merge-graphql-schemas which seems to do the job.

**Comment by stephen-wille** [comment]
i don't think this is feasible for me as it's just too much config work
