### ISSUE TITLE
Syntax Support for dynamic generate query

### ISSUE THREAD

**Issue by KevinYaoooooo** [jimkyndemeyer/js-graphql-intellij-plugin#206]
![image](https://user-images.githubusercontent.com/12027816/51318981-c855e600-1a96-11e9-85c2-5fe94cdf3c59.png)

![image](https://user-images.githubusercontent.com/12027816/51319027-e4598780-1a96-11e9-8f09-986ba145aff8.png)

**Comment by jimkyndemeyer** [comment]
Hi Kevin.

Thanks for using the plugin.

I'm reluctant to make the GraphQL "templating" any more complicated than it already is. Currently there is placeholders support for variables and fragments. This appears to cover 99% of existing use-cases including composing GraphQL from components. With your specific example, GraphQL doesn't really give you any benefits, in that the fragment is fully dynamic and can't be validated.

For context, the existing templating is made by "faking valid" GraphQL by replacing the placeholder parts with "valid" GraphQL and filtering the validation errors that come back. In all cases, the challenge is that GraphQL validation is not officially defined without a valid syntax tree.

I highly recommend reading https://blog.apollographql.com/5-benefits-of-static-graphql-queries-b7fa90b0b69a

It outlines many of the benefits that you get from static queries, both at build time and in production.

Without knowing your use case and what you're trying to achieve, I think there is a "native GraphQL" way of doing this kind of "buckets" using a more flexible schema and variables that contain input objects. It could make sense to describe what you're after on Stackoverflow for example, and get feedback on ways of achieving your goal.

If you do add a post somewhere, please link to it from here. I'll keep this issue open in case other developers have similar needs.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing based on the above and no additional activity.

Feel free to add additional comments.

Best regards,
Jim.
