### ISSUE TITLE
Graphql doesn't work with spring boots 2.0.4 (or up)

### ISSUE THREAD

**Issue by Hackniu** [jimkyndemeyer/js-graphql-intellij-plugin#208]
I build my app with maven with intellij 2018.1.2 (Ultimate edition), and I am using dependency below:

org.springframework.boot
spring-boot-starter-web
2.0.4.RELEASE

com.graphql-java
graphql-spring-boot-starter
5.0.2

com.graphql-java
graphql-java-tools
5.2.4
When I run my app in intellij with graphql dependencies(without any code of graphql), it disabled my start button and debug button after click those button once. But it seems that graphql works with spring-boot 2.0.3.RELEASE. Does anyone knows what the reason could cause intellij work abnormal with adding graphql dependencies? Thanks!

**Comment by jimkyndemeyer** [comment]
Hi Hackniu.

This issue tracker is for issues relating to the language tooling that this GraphQL plugin provides, e.g. GraphQL syntax highlighting, completion, and error highlighting.

From what you're describing, it doesn't appear like this plugin is involved. There is no code in the plugin that integrates with run configurations or dependency management.

I think what you're after is https://intellij-support.jetbrains.com/hc/en-us/?intellij-idea

Best regards,
Jim.
