### ISSUE TITLE
Schema file not read only (viewer mode) in 1.3.3

### ISSUE THREAD

**Issue by vangorra** [jimkyndemeyer/js-graphql-intellij-plugin#21]
I'm creating a new file called "schema.graphqls". Then I attempt to type "schema {}". I don't get past typing the "s" before the following console error appears. This wouldn't be so bad except after this error appears, I cannot modify the editor view for the file. I get a small tooltip that says "This view is read only".

> /home/robbiev/bin/node /home/robbiev/.WebStorm2016.2/config/plugins/js-graphql-language-service.dist.js --port=46469
> JS GraphQL listening on http://127.0.0.1:46469/js-graphql-language-service
> Setting Project Dir '/home/robbiev/Documents/git/cemx/src'
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "s"
> 
> 1: s
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "s"\n\n1: s\n   ^\n' }
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "s"
> 
> 1: s
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "s"\n\n1: s\n   ^\n' }
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "sh"
> 
> 1: sh
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "sh"\n\n1: sh\n   ^\n' }
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "sh"
> 
> 1: sh
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "sh"\n\n1: sh\n   ^\n' }
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "s"
> 
> 1: s
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "s"\n\n1: s\n   ^\n' }
> Unable to build schema AST { [Error: Syntax Error GraphQL (1:1) Unexpected Name "s"
> 
> 1: s
>    ^
> ]
>   message: 'Syntax Error GraphQL (1:1) Unexpected Name "s"\n\n1: s\n   ^\n' }
>

**Comment by jimkyndemeyer** [comment]
Hi Robert.

Thanks for using the plugin.

The schema language isn't supported yet for editing scenarios. Here more background regarding the schema language support from an earlier issue:

> As it stands, the .graphqls support is considered read-only and requires that a valid parse tree can be created for syntax highlighting. It was added as a means of showing the currently loaded schema that the plugin uses for completion, error highlighting, and for providing find usages etc.
> 
> I logged graphql/codemirror-graphql#14 a short while ago since schema editing would be a useful addition. Until that issue is implemented, you should edit your schema file with another file extension to prevent the errors-as-you-type from popping up the console.

So the schema file is supposed to be in viewer mode. I'll investigate why you're able to type in it in the latest version.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
@vangorra Can you describe the steps to reproduce this in more detail? The editor is immediately read-only for me when I attempt to write.

**Comment by jimkyndemeyer** [comment]
Closed by #22: .graphqls files are editable in in v1.4.0
