### ISSUE TITLE
[v2] Unable to extend server schema with local schema 

### ISSUE THREAD

**Issue by pashazz** [jimkyndemeyer/js-graphql-intellij-plugin#210]
What I want to do is to manage my application's local state with `@client` queries (Apollo client cache) using schema available locally and use remote data from remote endpoint.
The configuration presented  in the MWE (remote schema on a server + local schema with local queries) allows me to generate TypeScript types with graphql-code-generator for all queries so I am sure that the queries are correct.

I created a MWE with my graphql config (.graphqlconfig.yaml), local schema (schema.graphql). Endpoint is changed to fakerql, but it doesnt matter as these graphql files only contain client queries.

https://github.com/pashazz/graphql-mwe

src/vmsTable.graphql looks like this:
![image](https://user-images.githubusercontent.com/45922/52169813-572d5880-274f-11e9-9c7c-8edf9e780bce.png)

**Version:** v.2.0 alpha 5

**Comment by jimkyndemeyer** [comment]
Hi Pavel.

Thanks for using the plugin.

I took a quick look at the git repo, and you're missing two minor changes:
- Add the following to your `schema.graphql` file: `directive @client on FIELD_DEFINITION | FIELD`. This basically tells the plugin that this directive exists and is valid on fields.
- Remove the `extend` keyword from your mutation and query definitions in `schema.graphql`. These two root types need to be declared somewhere initially. You're free to use `extend` elsewhere to add additional fields.

Hope that helps. I'm closing this issue on that basis, but feel free to add comments.

Best regards,
Jim.

**Comment by jereckley** [comment]
A quick updated. I found the green arrow... its on the .graphqlconfig file. The funny thing is that it doesn't matter what url I put in the url property. It still pulls from localhost port 8080. Thanks for all your hard work on the plugin!

**Comment by jimkyndemeyer** [comment]
@jereckley Thanks, I have a fix for the stale endpoint url in the next alpha.
