### ISSUE TITLE
[v2] .graphqlconfig includes/excludes doesn't work as expected

### ISSUE THREAD

**Issue by dan-j** [jimkyndemeyer/js-graphql-intellij-plugin#214]
## Version and Environment Details
__Operation system__: MacOS 10.14

__IDE name and version__: Webstorm 2018.3.4

__Plugin version__: v2.0.0-alpha-5

## Expected Behaviour

Within a monorepo with some application packages and some common packages, to be able to use `"includes"` within a `.graphqlconfig` file of an application package to load SDL files from a common package.

## Actual Behaviour

GraphQL Types within my application package give an error: "The interface type "MyType" is not present when resolving type "IMyType", where `MyType` is a GraphQL type defined in my application, and `IMyType` is an interface in a shared package.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

My project is a little more complicated with two levels of directories under `./packages/`, but this is to separate api and ui packages, however the below is the gist of what I'm trying to achieve

A directory structure like so:
```
.
└── packages
    ├── my-api
    │   ├── .graphqlconfig
    │   └── schemas
    │       └── schema.graphql
    └── my-shared-lib
        └── schemas
            └── schema.graphql
```

Where `packages/my-api/.graphqlconfig` contains the following:

```json
{
    "name": "my-api",
    "extensions": {
        "endpoints": {
            "Default GraphQL Endpoint": {
                "url": "http://localhost:3000/graphql",
                "headers": {
                    "user-agent": "JS GraphQL"
                }
            }
        }
    },
    "includes": [
        "./schema/**/*",
        "../my-shared-api/schemas/**/*"
    ]
}
```

I have also tried:

- creating a root `.graphqlconfig` and using the `"projects"` key
- reordered the `"includes"` array
- changed the glob from `...**/*` to `...**`
- used absolute paths (mainly to check my relative paths are correct)

**Comment by dan-j** [comment]
Also worth adding...

I have my SDL files separated by types, so I have around 50+ `.graphql` files across the packages. If I edit one of the files which the IDE is saying can't resolve (i.e. a type in my application package references a type in my shared package with an error, I edit the shared type) the error goes away, and cmd+click works as expected. If I restart WebStorm, the error returns.

**Comment by jimkyndemeyer** [comment]
Hi Dan.

Thanks for testing the alpha.

From the project structure you've outlined you need to use the `projects` key in a `.graphqlconfig` file that resides in a directory where it can see both the shared lib and specific schemas as child directories. 

Note that a `.graphqlconfig` can not include anything outside the folder it resides in. The reason for that restriction is that graphql files find their corresponding config file by looking in their current directory or parent directories.

If you find that it doesn't work, please link to a git repository that reproduces the error, or attach a zip file directory to this issue.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Hi Dan.

I just published alpha-6 which contains a fix that should make your use case possible. I've created an example project at https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/two-schemas-plus-shared-using-projects that shows how to reference shared types.

Hope that helps.

Best regards,
Jim.

**Comment by dan-j** [comment]
Awesome! Thanks a lot, just tried this out and works like a charm. 

Loving this plugin, thanks for your efforts!
