### ISSUE TITLE
Unknown type "Subscription".

### ISSUE THREAD

**Issue by frederikhors** [jimkyndemeyer/js-graphql-intellij-plugin#219]
**Why this error?**

![image](https://user-images.githubusercontent.com/41120635/54399961-16671e80-46c1-11e9-89cd-ec0a031dd590.png)

Error:(4, 19) Unknown type "Subscription".

## Version and Environment Details
__Operation system__: Windows 10

__IDE name and version__: Goland 2018.3.5

__Plugin version__: JS Graphql v1.7.3 - NodeJS (plugin) v183.5429.1 - NodeJS 10.15.3

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for testing the plugin.

The 1.x release is based on a pretty old GraphQL spec and doesn't support subscriptions.

Please try https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1 which also features completion and error highlighting while authoring schemas using SDL.

Let me know if you have any issues.

Best regards,
Jim.
