### ISSUE TITLE
[v2] Ignore files which are ignored by IntelliJ

### ISSUE THREAD

**Issue by steebchen** [jimkyndemeyer/js-graphql-intellij-plugin#220]
The plugin should ignore errors in ignored files:

![Selection_999(1127)](https://user-images.githubusercontent.com/5013932/54465898-ba160480-477d-11e9-85bc-d950e7667a06.jpg)

It probably should not completely ignore the files, because there may be cases where types are defined in vcs-ignored files, but I think it would be good if it would ignore errors in ignored files. 

## Version and Environment Details
__Operation system__: Linux Mint

__IDE name and version__: 2019.1 EAP

__Plugin version__: 2.0.0-alpha-8

**Comment by jimkyndemeyer** [comment]
Hi Luca.

Thanks for testing the alpha.

Can you describe your use case in more detail, and include the error message you're seeing?

The reason I'm asking is that I don't think it always makes sense to disable error highlighting just because a file is ignored in vcs.

So just trying to understand your use case, as there might be an alternative solution.

Best regards,
Jim.

**Comment by steebchen** [comment]
Sure, makes sense!

My use case is basically [Prisma](https://www.prisma.io). I write SDL, code gets generated, and additionally I output a schema.graphqls with the generated prisma graphql server so I have completions in my seed *.graphql files. However, now that prisma generates a second schema, now I have conflicts because my original config declares `type User` but so does the prisma GraphQL server.

I see that this is a special case, in the only reason I generate the extra schema.graphqls file is I can't seem to find an option in the .graphqlconfig file to get the schema from a server instead of an extra generated graphql file... so feel free to close if this is out of scope.

**Comment by jimkyndemeyer** [comment]
Hi Luca.

You should be able to get this working without duplicate type errors by separating your two "logical" schemas. Take a look at https://github.com/jimkyndemeyer/graphql-config-examples which shows various examples of how to control schema discovery via `.graphqlconfig` globs.

You'd then have one "SDL authoring schema" and your "Production schema" that you can consume from UI components for example.

Once you get it sorted, I'd appreciate a PR or a "how-to" issue in the `graphql-config-examples` repository as this could help other Prisma users.

Thanks for the kind words about the plugin :)

Let me know if you have any questions.

Best regards,
Jim.

**Comment by steebchen** [comment]
Thanks for the hint. I can get my schema from a remote now, but I still end up having a local graphql schema file which does not solve my original problem.

**Comment by steebchen** [comment]
This can be solved using `projects`. Didn't hat the time to fully test it but it fixes my main problem.
