### ISSUE TITLE
Autoformatting query response

### ISSUE THREAD

**Issue by mkczyk** [jimkyndemeyer/js-graphql-intellij-plugin#221]
When I write and run query, I get unformatted JSON response:

![graphql-no-format](https://user-images.githubusercontent.com/11051213/54481013-a88d3500-482f-11e9-8cd8-db0080b31259.png)

To format response, I have to go to response tab and use `Ctrl+Alt+L` every time:

![graphql-format](https://user-images.githubusercontent.com/11051213/54481356-da07ff80-4833-11e9-8d6b-2e938a5d1a67.png)

Feature requests: 
- autoformatting response after executing query,
- ability to turn off/on autoformatting response (checkbox in settings or button in GraphQL tab).

v1.7.3

**Comment by jimkyndemeyer** [comment]
Hi Marcin.

Thanks for using the plugin.

v2 beta-1 should format the response as expected, so please try that. Installation instructions at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Best regards,
Jim.

**Comment by mkczyk** [comment]
Hi Jim,

Thank you for your response.

In v2 autoformatting works fine.

![image](https://user-images.githubusercontent.com/11051213/54868967-9ca2f500-4d92-11e9-99bb-45512b4c5194.png)

Best regards,
Marcin

**Comment by dawi** [comment]
I am using IntelliJ IDEA 2022.1 Ultimate and the auto-formatting of responses does not work for me.
