### ISSUE TITLE
Add support for Oauth tokens

### ISSUE THREAD

**Issue by Naouak** [jimkyndemeyer/js-graphql-intellij-plugin#223]
Hi,

I'm using graphql endpoints/schema that are behind an oauth authentication. I can currently set in the option file the token but I have to do it each time the token is invalidated (every 10 hours in my case).

It would be great to have a way to either:
- set the token dynamically.
- support HTTP variables from Jetbrains HTTP client.
- support OAuth authentication directly in the plugin.

Thanks

**Comment by jimkyndemeyer** [comment]
Hi Quentin.

Thanks for using the plugin.

Version 2 supports environment variables for use cases such as authentication. I've posted an example project configuration for how to authenticate against the GitHub API at [graphql-config-examples/github-api-v4/.graphqlconfig](https://github.com/jimkyndemeyer/graphql-config-examples/blob/c6968b24feb4cbb7a03b995880781523d8e0ff5d/github-api-v4/.graphqlconfig#L9)

Note that this functionality is part of 2.0 which you'll find more info about at:
https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

That should solve your issue. If not, let me know what you'd like to see changed.

Best regards,
Jim.
