### ISSUE TITLE
How to remove a block border

### ISSUE THREAD

**Issue by ivan-kleshnin** [jimkyndemeyer/js-graphql-intellij-plugin#225]
Hi guys. Thanks for the awesome plugin! I have a question – how to disable a gray border outside of the block (see the screenshot)

![Screen Shot 2019-03-21 at 11 10 14](https://user-images.githubusercontent.com/2128182/54742384-ebe9f980-4bc9-11e9-9594-240bbe8d7ebe.png)

I don't like the look of it (too distracting) and would like to hide or disable it.
Searching through the settings didn't help.

**Comment by jimkyndemeyer** [comment]
Hi Ivan.

Thanks for using the plugin.

I recommend that you try the 2.0 beta which also provides completion and error highlighting while authoring schemas. See installation steps at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-1

Best regards,
Jim.

**Comment by ivan-kleshnin** [comment]
Thank you for the response, I'll do. Keep it up!
