### ISSUE TITLE
[v2] Plugin JS GraphQL was not installed: Cannot download

### ISSUE THREAD

**Issue by RafaelKr** [jimkyndemeyer/js-graphql-intellij-plugin#234]
## Version and Environment Details
__Operation system__:
Linux Mint 19.1 Cinnamon 64-bit

__IDE name and version__:
```
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
Licensed to IntelliJ IDEA Evaluator
Expiration date: April 28, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-47-generic

```
__Plugin version__:
v2.0.0 not installable after uninstalling v2.0.0-end-of-beta

## Expected Behaviour
Should be installable from IntelliJ Marketplace

## Actual Behaviour
Today I received the v2.0.0-end-of-beta update, thanks!
Independently of that I ran `Window > Store Current Layout as Default`. After restarting IntelliJ, the window didn't load correctly with an exception. Unfortunately I didn't copy or reported it, but it was something like `window="GraphQL" already exists`, so maybe IntelliJ already loaded the GraphQL tab (in the bottombar) and on initialization of the plugin it is trying to add it again? Anyway, I disabled the plugin from the exception window, restarted the IDE and it started correctly.
Now I uninstalled the `v2.0.0-end-of-beta` and wanted to install v2.0.0 from the marketplace, but it's not working with the following error:
```
Plugin JS GraphQL was not installed: Cannot download
'https://plugins.jetbrains.com/pluginManager/?action=download&id=com.intellij.lang.jsgraphql&build=IU-191.6183.87&uuid=e2b250d4-d380-4e86-b953-fe9b95701333': Request failed with status code 404
```
I don't know if you or JetBrains has to fix this error.  
I also tried to run `File > Invalidate Caches / Restart...`, but didn't change anything.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Maybe just uninstall, then install? Or install `v2.0.0-end-of-beta` from Repo, uninstall again and then try to install from the Marketplace.

Actually this issue thread has two issues, but I can't further test the first one without the second issue being resolved. Thanks for having a look at it, Jim.

Best regards
Rafael

Edit:
![image](https://user-images.githubusercontent.com/14234815/55712365-e1fc2f00-59ee-11e9-90db-62261c5850f5.png)

**Comment by jimkyndemeyer** [comment]
Hi Rafael.

Did you remove the custom alpha/beta repository URL? I think that may be what's causing the issue.

**Comment by RafaelKr** [comment]
Hi Jim. Yes, I removed the repository URL from the "Custom Plugin Repositories" window. It's not listed there anymore.

**Comment by RafaelKr** [comment]
Additional information: I just tried to open the URL of the "Failed to Download" window in the browser (https://plugins.jetbrains.com/pluginManager/?action=download&id=com.intellij.lang.jsgraphql&build=IU-191.6183.87&uuid=e2b250d4-d380-4e86-b953-fe9b95701333) 
It works! It's downloading `JS GraphQL-2.0.0.zip`. So most probably this is a problem with IntelliJ.

**Comment by jimkyndemeyer** [comment]
I just ran Into the same 404 issue trying to update. I've contacted JetBrains to make them aware of the issue.

**Comment by Petar-np** [comment]
Same issue in WebStorm

**Comment by wsrast** [comment]
Workaround:

1. Put the following into your browser, as @RafaelKr mentioned, and download it to your desktop or whereever.

2. Go to File > Settings > Plugins > Gear Icon to right of right side tabs > Install Plugin from Disk...

3. Locate your downloaded file and hit Ok.

4. Profit.

**Comment by jimkyndemeyer** [comment]
Ok, so JetBrains is apparently rolling out a new version of the repository with a brand new look: https://plugins.jetbrains.com/plugin/8097-js-graphql

I suspect that update is related to the issue.

**Comment by RafaelKr** [comment]
For me it's working again.
Jim, thank you very much for your quick response and support. Is there any way to donate you a coffee? :)

Have a nice week all
Rafael

**Comment by jimkyndemeyer** [comment]
JetBrains confirmed that this was an issue on their end: https://youtrack.jetbrains.com/issue/MP-2197

@RafaelKr I'm happy to help, and thank you for the offer. I don't have a setup for donations, but if you'd like to support open source in general there's a good list at https://github.com/joshtronic/donate#organizations

Best regards,
Jim
