### ISSUE TITLE
[V2] Schema parsing is broken

### ISSUE THREAD

**Issue by Mikhus** [jimkyndemeyer/js-graphql-intellij-plugin#240]
## Version and Environment Details
__Operation system__: Linux Mint

__IDE name and version__: WebStorm (part of ultimate edition)

__Plugin version__: 2.0.0

## Expected Behaviour
Schema, containing un-ordered or cycling types declarations parsed with no errors, as in previous version.

## Actual Behaviour
I have a schema which has types referencing each other in some cases and previously it has no matter how types declaration followed each other. Another point is that schema has cyclic dependencies, for example: 

~~~graphql
type Expression {
  id: ID!
  conditionId: ID!
  condition: Condition!
}

type Condition {
  id: ID!
  expressions: [Expression]
}
~~~

Such a case does not give a way to construct a correct order to prevent errors. Previous version has been parsing my schema with no problem.

Currently I'm getting an error "The field type 'Condition' is not present when resolving type 'Expression' [@229:1]"

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Try to parse schema with cycling deps as was stated above...

**Comment by Mikhus** [comment]
Previous installed working version was 1.7.3

**Comment by jimkyndemeyer** [comment]
Hi Mykhailo.

Thanks for using the plugin.

I just created a GraphQL file with the following type definitions and it validates just fine:

```GraphQL
type Query {
    document: Expression
}

type Expression {
    id: ID!
    conditionId: ID!
    condition: Condition!
}

type Condition {
    id: ID!
    expressions: [Expression]
}

query Query {
    document {
        condition {
            id
        }
    }
}
```

Here's the view I see:

![image](https://user-images.githubusercontent.com/15837712/55976476-9961a180-5c8c-11e9-9be8-b2c6c0b304e2.png)

So cyclic dependencies appear to work based on my example above.

Can you try and create a minimal example that demonstrates the issue and either attach it or provide a link?

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing this until a minimal reproduction is attached to the issue.
