### ISSUE TITLE
Support unicode in schema comments (affects GitHub v4 API)

### ISSUE THREAD

**Issue by mattkrick** [jimkyndemeyer/js-graphql-intellij-plugin#246]
This is likely a followup to #216. It looks like #216 resolved it for JSON & SDL with legacy comment sigils, but for the triple quotes there's still an error.

## Version and Environment Details
__Operation system__: Ubuntu 18.04

__IDE name and version__: Webstorm 2019.1

__Plugin version__: 2.1.0

## Expected Behaviour

Support for unicode in .graphql file (needed for GitHub schema)

## Actual Behaviour

`Unexecpted token:`....

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

reference the following schema:
```
type Query {
  """👍"""
}
```

**Comment by jimkyndemeyer** [comment]
Hi Matt.

Thanks for using the plugin.

The GraphQL grammar doesn't allow multi-character Unicode emojis so this is not a bug.

I've contacted GitHub previously (https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/216#issuecomment-468952645), as their use of emojis break all spec-compliant tools that interfaces with their schema.

There is an open issue that covers expanding this range at https://github.com/graphql/graphql-spec/issues/214 but it will require a change in the spec. Should the spec change I'll update the plugin.

Best regards,
Jim.
