### ISSUE TITLE
Chinese comments are garbled in 'schemaPath' file.

### ISSUE THREAD

**Issue by Devil-Cong** [jimkyndemeyer/js-graphql-intellij-plugin#247]
## Version and Environment Details
__Operation system__:
macOS Mojave 1.14.2

__IDE name and version__:
WebStorm 2018.3.6

__Plugin version__:
v2.1.0

## Expected Behaviour
![image](https://user-images.githubusercontent.com/13516290/56655804-65dc3980-66c6-11e9-8ca9-9e69bf4fa734.png)

## Actual Behaviour
1. When I use this config to fetch the remote schema. It work. But the chinese comments are garbled in `schemaPath` file. 
![image](https://user-images.githubusercontent.com/13516290/56655942-bb184b00-66c6-11e9-92e4-1cfdf32959ac.png)
![image](https://user-images.githubusercontent.com/13516290/56655842-77bddc80-66c6-11e9-851d-193d890f95b5.png)
2. Then I found that if I fetch the remote schema with `Postman`. Then response data is normal.
![image](https://user-images.githubusercontent.com/13516290/56657414-8c03d880-66ca-11e9-8745-93d79ccb5ef9.png)
So is it possible that this is a bug?

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Use the `introspect: true` option to fetch an existing remote schema, which with chinese comments.

**Comment by Devil-Cong** [comment]
Hi @jimkyndemeyer , Is there any plan to fix it?

**Comment by jimkyndemeyer** [comment]
Hi Leon Liu.

Thanks for using the plugin.

I can't say when I'd have time to look at this, so a PR would be much appreciated.

I'm a bit surprised that this is an issue as there's a test that has Russian unicode characters in it, and that works as expected (see the last line):

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/6d1ed3231a15a47c92e27021c4c9ddefb6387660/src/test/com/intellij/lang/jsgraphql/ide/editor/GraphQLIntrospectionHelperTest.java#L13-L43

If you'd like to take a look I think the relevant location to set a breakpoint with your schema is https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/6d1ed3231a15a47c92e27021c4c9ddefb6387660/src/main/com/intellij/lang/jsgraphql/ide/editor/GraphQLIntrospectionHelper.java#L226

The issue might also stem from not having the right content encoding headers available on the response from your endpoint. One of the recent changes in this plugin was to assume UTF-8 in case no header specified the encoding, as outlined in https://tools.ietf.org/html/rfc7159.html

Best regards,
Jim.

**Comment by Devil-Cong** [comment]
Hi @jimkyndemeyer .

Thanks for you reply.

After my test, I found the garbled contents in 'schemaPath' file was use `ISO-8859-1` encoding. Yes, `ISO-8859-1` was the Java 'httpClient' default response handle encoding. That is why the chinese comments was normal in `Postman`, and not in the plugin. So I indicate the response encoding was UTF-8 by adding `Content-Type: application/json;charset=UTF-8` in response header to fix the problem. 

Thank you again.

**Comment by conanchen** [comment]
Hi @Devil-Cong , I have the same problem, but how can i add "Content-Type: application/json;charset=UTF-8" to the response as it comes from third party system ?

**Comment by Devil-Cong** [comment]
> Hi @Devil-Cong , I have the same problem, but how can i add "Content-Type: application/json;charset=UTF-8" to the response as it comes from third party system ?

Sorry, I have no idea. I solved this problem by adding the response header to my own GraphQL service. Maybe you can try to proxy the third-party service.
