### ISSUE TITLE
[v2] how to use environment variables?

### ISSUE THREAD

**Issue by sam-at-work** [jimkyndemeyer/js-graphql-intellij-plugin#249]
I am using IntelliJ iDEA 2019.1. I have a `.graphqlconfig` file as follows. I am trying to figure out how to get `js-graphql-intellij-plugin` to automatically get the value of `YOUR_APP_TOKEN` which I have in a `.env` file.

```
{
  "schemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "dev": {
        "url": "http://your-app.com/graphql",
        "headers": {
          "Authorization": "Bearer ${env:YOUR_APP_TOKEN}"
        }
      }
    }
  }
}
```
When I run a graphql query using `js-graphql-intellij-plugin` plugin, I get a dialog box asking to 

> Enter Missing GraphQL "API_KEY" Environment Variable

(I have a `.env` file with this value in it which it would be great if there was a way the plugin could read from.)
If I paste the value into the dialog box, it does remember the value, even though the dialog box appears every time I make a new request.

The hint text in this dialog box says:
> *Hint* Specify environment variables using `-DvarName=varValue` on the IDE command line.

But `-DvarName=varValue` is not a valid bash command.

## Expected Behaviour
A way to either set the environment variable inside of IntelliJ so the dialog box doesn't always pop up when I run a graphql query, or for `js-graphql-intellij-plugin` to be able to env vars from a `.env` file.

**Comment by jimkyndemeyer** [comment]
Hi Sam.

Thanks for using the plugin.

The `-D` option would still show the dialog, and would only set the initial value.

I opted to show the dialog each time as the it would also be annoying to have to restart the IDE in case a new value needs to be entered. But I made sure to focus the dialog such that you can simply press enter to close it using the current value.

A lot of non-JS project don't use .env files, so I'm not sure that's worth the effort. I'm thinking that a check box to not show the dialog again until IDE restart could be the a pragmatic solution.

Best regards,
Jim.

**Comment by sam-at-work** [comment]
HI Jim,

Thanks for the response. Finding v2 of the plugin really useful btw.

Could you please clarify how the -D option works? What do you mean by the
IDE command line in IntelliJ? Assuming it's not the terminal.

Kind regards,
Sam

**Comment by jimkyndemeyer** [comment]
Hi Sam.

I mean the command line that starts your IDE process. I'm actually not sure how to pass the arguments from a terminal as I've only tested this by running the IDE as debug from inside another IntelliJ instance:

![image](https://user-images.githubusercontent.com/15837712/57138569-4ffc0200-6db3-11e9-83e0-3edcf6d3a8cb.png)

You might have some luck by reviewing https://www.jetbrains.com/help/idea/tuning-the-ide.html

The plugin uses `System.getProperty` to look up the default values for the env vars given that IntelliJ itself is a Java process.

**Comment by sam-at-work** [comment]
OK thanks. Will close issue.
I found the popup dialog a bit annoying when I first referenced an env var in my .`graphqlconfig` file, but I am used to it now.
