### ISSUE TITLE
Upload dataType

### ISSUE THREAD

**Issue by tkvlnk** [jimkyndemeyer/js-graphql-intellij-plugin#250]
Hi! Many thanks for this plugin. It is really useful and I enjoy working with it a lot. Here is a problem I faced building small demo which uploads files using GraphQL
https://github.com/jaydenseric/graphql-multipart-request-spec

## Version and Environment Details
__Operation system__: 
macOS 10.14.4 

__IDE name and version__: 
WebStorm 2018.3.6
Build #WS-183.6156.10, built on March 24, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

__Plugin version__: 
2.1.0

## Expected Behaviour
Schema doesn't displays and error for `Upload` data type

## Actual Behaviour
Schema reports an error for  `Upload` data type
![Alt text](https://monosnap.com/image/wgYhvFvjRnXgUCgHoYs2nBrbVQ4VTf.png)

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Define mutation schema which uses `Uload` data type

**Comment by MartijnHols** [comment]
Unfortunately that is not always possible as setups such as apollo-server add it for us. Adding a custom scalar would duplicate it, leading to application errors. 

https://github.com/apollographql/apollo-server/blob/6535fcfad366f30fa98850b52e8a2da853338db0/packages/apollo-server-core/src/ApolloServer.ts#L501-L507

**Comment by jimkyndemeyer** [comment]
@MartijnHols You should be able to declare the Upload scalar in a separate .graphql file that is only included in the schema discovery done by the plugin. Just make sure you don't include that same file in the type defs passed to the apollo server.

This approach is similar to how client-only fields can be added to the schema for Apollo Client: https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives (note that in the example the GraphQL is in tagged template literals, but could just as well be plain .graphql files)
