### ISSUE TITLE
[V2] Inspection fails with tons of "The type 'QueryType_JPA' with field 'FIELD_NAME' [@-1:-1] has declared an argument with a non unique name 'ARGUMENT_NAME'"

### ISSUE THREAD

**Issue by joshstrange** [jimkyndemeyer/js-graphql-intellij-plugin#251]
## Version and Environment Details
__Operation system__: Mac OS 10.14.4 (18E226)

__IDE name and version__: IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

__Plugin version__: v2.1.0

## Expected Behaviour
Plugin works as before with minor changes to support .graphqlconfig 

## Actual Behaviour

Plugin doesn't support .json schemaPath so I [tried to use introspect](https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection) and got the following error. 

````
SchemaProblem{errors=[The type 'QueryType_JPA' with field 'generatedReport' [@-1:-1] has declared an argument with a non unique name 'asynchronousJobId', The type 'QueryType_JPA' with field 'generatedReport' [@-1:-1] has declared an argument with a non unique name 'reportId', The type 'QueryType_JPA' with field 'generatedReport' [@-1:-1] has declared an argument with a non unique name 'reportParameters', The type 'QueryType_JPA' with field 'generatedReport' [@-1:-1] has declared an argument with a non unique name 'id', The type 'QueryType_JPA' with field 'generatedReports' [@-1:-1] has declared an argument with a non unique name 'asynchronousJobId' ...
````

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

This is an internal project and I cannot share API/code examples. The old plugin worked just fine and I tried to use the JSON response from the inspection query that I used with the old plugin but it was never picked up (or maybe was silently throwing the same error). Not sure what is going on here.

**Comment by jimkyndemeyer** [comment]
Hi Josh.

Thanks for using the plugin.

The error thrown appears to be https://github.com/graphql-java/graphql-java/blob/6211b411f375b03c094b7333fed9a2308e4b6c23/src/main/java/graphql/schema/idl/errors/NonUniqueNameError.java#L21

Without access to your schema definition I can't really say how this can be resolved. I'd need a small reproducable example to make this actionable. If that's not possible I see two ways forward:

- You could try commenting out parts of the schema to figure out why `graphql-java` sees your 
schema as invalid.
- Downgrade to 1.7.4 manually by downloading it from https://plugins.jetbrains.com/plugin/8097-js-graphql/versions and using the "Install plugin from disk" option

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Hi Josh.

This issue is not actionable in its current state, so I'm closing it on that basis.

If you have any additional info to help reproduce this feel free to add a comment and we'll take it from there.

Best regards,
Jim.
