### ISSUE TITLE
Webstorm complaints on string literals

### ISSUE THREAD

**Issue by osenvosem** [jimkyndemeyer/js-graphql-intellij-plugin#252]
How to fix/suppress this?

![Screenshot 2019-05-20 at 18 13 25](https://user-images.githubusercontent.com/6762673/58034475-561e0c80-7b2f-11e9-9042-e9715a6fb2e7.png)

**Comment by jimkyndemeyer** [comment]
Hi Sergey.

Thanks for using the plugin.

It looks like your schema hasn't been picked up by the plugin. Please take a look at https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide and https://blog.jetbrains.com/webstorm/2019/04/featured-plugin-js-graphql/ for how to get started.

Best regards,
Jim.
