### ISSUE TITLE
Indentation in gql` string literals is wrong, unconfigurable

### ISSUE THREAD

**Issue by bryankennedy** [jimkyndemeyer/js-graphql-intellij-plugin#258]
## Version and Environment Details
__Operation system__: macOS 10.14.5

__IDE name and version__: InteliJ IDEA Ultimate 2019.1.3

__Plugin version__: v2.1.0

## Expected Behaviour
I should be able to configure the number of spaces used for indentation in `.graphql` files and in `gql` string literals. These two indentation setups should be the same.

## Actual Behaviour
In my current setup I have my JS files set to indent code at 2 spaces. When these files include gql string literals the indentation within that gql code is 4 spaces. In my fully GraphQL files like `thing.graphql` the indentation is handled with 2 spaces.

In this issue #180 there is a mention of the GraphQL pane in the Preferences > Code Style. I don't see this pane any longer. Was it removed, or do I have something misconfigured? Forgive me if this is something wrong about my install. I couldn't find any details about how to set this in past issues or the existing documentation.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Create a .js file, add a `gql` string literal. If you have your Javascript indent spaces set to 2 spaces, the gql fragment will still get set to 4 spaces.

**Comment by EugeneDraitsev** [comment]
I faced with same issue. Seems like it happens after upgrade plugin to 2.1 from 2.0 or idea to 2019.1.3 from EAP

**Comment by ArStah** [comment]
Same here. After updating WebStorm to 2019.1.3 have got 4 spaces indentation in string literals

**Comment by kptlronyttcna** [comment]
Same here (using windows)

**Comment by jimkyndemeyer** [comment]
The dedicated code style tab was lost in the 1.x to 2.x migration.

For now, the GraphQL indentation is controlled by the following setting:

![image](https://user-images.githubusercontent.com/15837712/59420141-9d18be00-8dcc-11e9-89a0-96a4888c4da9.png)

**Comment by EugeneDraitsev** [comment]
@jimkyndemeyer 

![screencast 2019-06-13 11-18-56 gif sb-779b8554-bYSWsX](https://user-images.githubusercontent.com/16540432/59420404-20d2aa80-8dcd-11e9-8973-f4724a49dbcf.gif)

Seems like this option is not working too.

**Comment by jimkyndemeyer** [comment]
@EugeneDraitsev Try with tab size 1:

![image](https://user-images.githubusercontent.com/15837712/59423896-55496500-8dd3-11e9-9814-7e307ce6add9.png)

**Comment by EugeneDraitsev** [comment]
I tried invalidate cache and restart idea, different values here, but it still works like `Tab Size: 4` and `Indent: 4`
![screencast 2019-06-13 12-05-50 gif sb-779b8554-FeU3VC](https://user-images.githubusercontent.com/16540432/59424226-e91b3100-8dd3-11e9-8226-3389f75502d9.gif)

**Comment by jimkyndemeyer** [comment]
Hmm, it appears the the "Other File Types" setting only applies to `.graphql` files and not injected GraphQL in JavaScript.

I haven't changed anything between 2.0 and 2.1 so not sure what's going on. Could be a change in how the IntelliJ platform formats injected languages.

It's likely that the code style page for GraphQL needs to be reintroduced to fix this.

**Comment by jimkyndemeyer** [comment]
Fixed in 2.2.0 pending JetBrains approval: Added Code Style settings page to control indentation

**Comment by bryankennedy** [comment]
I can confirm with the updated plugin that this fixes the problem. Thanks for getting it fixed so quickly.
