### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by kptlronyttcna** [jimkyndemeyer/js-graphql-intellij-plugin#260]
## Version and Environment Details
__Operation system__: Windows 10 

__IDE name and version__:  Intellij 2019.1.3

__Plugin version__: 2.2.0

Look at this picture:

![image](https://user-images.githubusercontent.com/15993774/59966986-34061880-9539-11e9-8d86-a84c76099a7d.png)

When I remove the `gql` tag it looks like this:

![image](https://user-images.githubusercontent.com/15993774/59966992-51d37d80-9539-11e9-88a8-712eed463a1d.png)

Adding `gql` tag somehow adds some extra indentations. I'm using 2 spaces for indention both in typescript and graphql code style settings.

**Comment by jimkyndemeyer** [comment]
Hi Ali.

Thanks for using the plugin.

The plugin wraps the JavaScript/TypeScript formatter to be able to also format the injected GraphQL.

If you configure your JavaScript indentation to match your TypeScript indentation you should see the right indentation.

Let me know if that works for you.

Best regards,
Jim.

**Comment by kptlronyttcna** [comment]
Yes, it works when JS and TS both have same indentation.
