### ISSUE TITLE
graphql.AssertException: Internal error: should never happen: cannot build value of null from EnumValue{name='PRIMARY_KEY_ASC'}

### ISSUE THREAD

**Issue by wesselvdv** [jimkyndemeyer/js-graphql-intellij-plugin#262]
## Version and Environment Details
__Operation system__: Mac OS X Mojave 10.14.5

__IDE name and version__: PhpStorm 2019.1.3

__Plugin version__: 2.2.0

## Expected Behaviour
The plugin should successfully parse my schema, that's generated from Postgraphile which contains quite some ORDER_BY enums.

## Actual Behaviour
It crashes with the following error:

graphql.AssertException: Internal error: should never happen: cannot build value of null from EnumValue{name='PRIMARY_KEY_ASC'}

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Try and parse the attached schema.
[schema.graphqls.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/3329028/schema.graphqls.zip)

**Comment by jimkyndemeyer** [comment]
Hi Wessel.

Thanks for using the plugin.

The schema has a number of default values for orderby that are set to `PRIMARY_KEY_ASC` but the type of the argument expect a list of order by, e.g. `[PRIMARY_KEY_ASC]`.

Here's an example of the invalid default value which should be a list:
```graphql
playerDefinitionsAbilityFactorEdge(
        """The method to use when ordering `PlayerDefinitionsAbilityFactor`."""
        orderBy: [PlayerDefinitionsAbilityFactorsOrderBy!] = PRIMARY_KEY_ASC
    ): PlayerDefinitionsAbilityFactorsEdge
```

I did a quick replace in your schema file of `= PRIMARY_KEY_ASC` to `= [PRIMARY_KEY_ASC]` and that causes the schema to validate.

Best regards,
Jim.

**Comment by BMorearty** [comment]
Thanks, I had the same error message and it was caused by the exact same mistake in my project's GraphQL schema!
