### ISSUE TITLE
Intellij plugin jumps between the files when I click on data structures

### ISSUE THREAD

**Issue by akhlystov5** [jimkyndemeyer/js-graphql-intellij-plugin#266]
## Version and Environment Details
__Operation system__: Windows 7

__IDE name and version__: 
IntelliJ IDEA 2018.3.6 (Ultimate Edition)
Build #IU-183.6156.11, built on March 25, 2019
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

__Plugin version__: v2.1.0

## Expected Behaviour
I have two files with identical data structures names. if click on a data structure in one file it should select this data structure in the existing file..

## Actual Behaviour
But actually it it can jump to another file and vice versa.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
create to QueryType and data structure

type QueryType {
    getFunds(audience: PersonalInvestmentAudienceType): [PersonalInvestmentFund]
...
enum PersonalInvestmentAudienceType {
    NEW_CUSTOMER
    EXISTING_CUSTOMER
}

* copy the file to the same folder.
* select PersonalInvestmentAudienceType with Ctrl+Click
see that it jumps to another file

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for using the plugin.

The plugin treats all type declarations as global across files given that GraphQL has no concept of imports. For that reason you'll need to configure schema discovery to associate the different files with separate schemas as documented in https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide

The documentation links to [graphql-config-examples](https://github.com/jimkyndemeyer/graphql-config-examples) repo which shows how to achieve your use case.

I'm closing this issue on that basis. Let me know if you have any questions.

Best regards,
Jim.
