### ISSUE TITLE
Multiple projects support

### ISSUE THREAD

**Issue by vankop** [jimkyndemeyer/js-graphql-intellij-plugin#267]
## Version and Environment Details
__Operation system__: 
OSX
__IDE name and version__: 
Webstorm 2019.1
__Plugin version__: 
2.2.0
## Expected Behaviour
I have 2 projects with different schemas, I expect that they will have different scope
## Actual Behaviour
Got errors like:
`There is already a schema defined [@3:1]`
## Steps to Reproduce / Link to Repo with Reproduction and Instructions

.graphqlconfig
```
{
	"projects": {
		"App": {
			"schemaPath": "./graphql/app/schema.graphql",
			"include": ["./graphql/app/*.graphql"]
		},
		"Reporting": {
			"schemaPath": "./graphql/reporting/schema.graphql",
			"include": ["./graphql/reporting/*.graphql"]
		}
	},
	"extensions": {
		"endpoints": {
			"App": {
				"url": ""
			},
			"Reporting": {
				"url": ""
			}
		}
	}
}

```

Getting errors in `*/schema.graphql`

**Comment by vankop** [comment]
there is related issue https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/84 but i did not find solution there

**Comment by jimkyndemeyer** [comment]
Hi Ivan.

Thanks for using the plugin.

The configuration looks valid so I'll need a way to reproduce the issue to help you.

Can you attach a minimal example that reproduces the issue as a zip file?

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Nothing actionable on this in its current state.

Please add a comment with minimal reproducing example and I'll take a look.
