### ISSUE TITLE
Disable Schema discovery

### ISSUE THREAD

**Issue by Growiel** [jimkyndemeyer/js-graphql-intellij-plugin#268]
Hello,

I'm looking for a way to disable Schema discovery.

Let me explain.

We use a lot of Javascript to generate our schema, with things like:

```
const directiveName = 'connectionArgs'

// language=GraphQL
const typeDefs = `
    """
    Adds the connection arguments on a field.
    """
    directive @${directiveName} on FIELD_DEFINITION
`
```

Obviously, the plugin fails at parsing that type of GraphQL, since it has to parse a variable to get the actual name of the directive (we get the error `Unexpected token: "EOF"`).

The workaround is to generate the schema from the server with introspection. It works great BUT the generated file and the original files are fighting with each other and we get a lot of errors like:

```
'XXX' type tried to redefine existing 'XXX' type
There is already a schema defined
```

I do not expect the plugin to be able to run javascript on the fly to discover our schema correctly (although it would be awesome) but a way to disable the schema discovery and only rely on the introspected file would be a really good start for us.

I do know that I can ignore the files in `.graphconfig` so they are not discovered, but since we are using multiple schema in the same projects, if we ignore files, then every schema is viewed as global instead of being scoped to the correct folders.

Hope I make sense.

Thanks !

**Comment by jimkyndemeyer** [comment]
Hi Growiel.

Thanks for using the plugin.

I think you can get your use case to work with the plugin in two different ways:

- __Recommended__: Remove the `// language=GraphQL` injection comment. This causes the plugin to include the template literal in schema discovery and indexing. You can still use injection but use the "temporary" intention that doesn't add the comment.
- __Or__: Divide the introspection and the Javascript templated "GraphQL" into two different schemas. You can do this using two graphqlconfig files or via the projects field in a single graphqlconfig. Make sure that your templated schema includes your code such that they don't bubble into the "Global" default project schema.

Best regards,
Jim.

**Comment by Growiel** [comment]
Hello,

The issue with using the first method and use the "temporary" intention, is that it's not versioned, Every member of the team has to do it for each block, which is not really an option.

Could you provide an example of config for the divided schemas ? I'm not sure I understand what you mean.

Thanks !

**Comment by jimkyndemeyer** [comment]
I mean that you would have two schemas in your project.

See the docs at https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#setting-up-multi-schema-projects-using-graphql-config

You'll find a number of examples at how to achieve multi-schema project setups at https://github.com/jimkyndemeyer/graphql-config-examples

Best regards,
Jim.

**Comment by Growiel** [comment]
I already have a multi-schema config:

```
{
  "name": "XXX",
  "projects": {
    "main": {
      "schemaPath": "main.introspection.schema.graphql",
      "extensions": {
        "endpoints": {
          "Main GraphQL Endpoint": {
            "url": "URL",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    },
    "test": {
      "schemaPath": "test.introspection.schema.graphql",
      "extensions": {
        "endpoints": {
          "Test GraphQL Endpoint": {
            "url": "XXX",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    }
  }
}

```

But when I use this config, I have the errors I mentioned before:

![Screenshot from 2019-07-10 09-49-17](https://user-images.githubusercontent.com/5228735/60950788-1f2ad280-a2f8-11e9-803c-04506583fe3b.png)

If I add `excludes: ["**"]`, the errors are gone but the schemas get mixed up (since it's all global scope), which I obviously don't want.

**Comment by jimkyndemeyer** [comment]
The `schemaPath` file is always considered as included in a specific schema. 

If I understand your use case correctly, you have to constrain the schemas from doing additional discovery using `includes` / `excludes` to make sure they don't overlap.

So, for your "main" and "test" schemas add the appropriate includes. These schemas should only pick up valid GraphQL files and components that need to use that specific schema. If you don't have any files to include here it's possible to simply have a single include that points to the file name you have in `schemaPath`.

Next, add projects to the config that are aimed at discovering the JS templated parts and scoping them in their own schemas. You'll need to specify `includes` here to make sure the JS templated files are scoped within this schema and not global. These schemas will inevitably show the `EOF` errors since they're not valid GraphQL, but that's fine since you have the valid schemas as well.

**Comment by Growiel** [comment]
I realized I posted the wrong schema above. The correct one already has includes:

```
{
  "name": "GraphQL Schemas",
  "projects": {
    "main": {
      "schemaPath": "main.introspection.schema.graphql",
      "includes": ["main/**"],
      "extensions": {
        "endpoints": {
          "Main GraphQL Endpoint": {
            "url": "XXX",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    },
    "test": {
      "schemaPath": "test.introspection.schema.graphql",
      "includes": ["test/**"],
      "extensions": {
        "endpoints": {
          "Test GraphQL Endpoint": {
            "url": "XXX",
            "headers": {
              "user-agent": "JS GraphQL"
            },
            "introspect": true
          }
        }
      }
    }
  }
}

```

And this generates the errors posted before, since the schema in `schemaPath` is already defining all the types, and then the GraphQL files in my `main` or `test` folders are also defining the same types.

I want my `shemaPath` to ba applied (scoped) to either `test` or `main` but I do NOT want the files inside to be discovered. I only want them to have autompletion and all the other tools, but be ignored as far the schema goes, to avoid errors.

Hope i'm clear.

**Comment by jimkyndemeyer** [comment]
You wrote: "the GraphQL files in my main or test folders are also defining the same types.". Then why are you using `"includes": ["main/**"]` as this will match the files you want to avoid??

**Comment by Growiel** [comment]
What I want is:

The files in `main` to be scoped to the `main.introspection.schema.graphql` file that I get from introspecting the server.
In those files, autocomplete should work based on the content of the `main.introspection.schema.graphql`. 
The content of the `test.introspection.schema.graphql` file should NOT show up during autocomplete.
I do not want the files to be used for schema discovery, rely only on the introspected schema.

The files in `test` to be scoped to the `test.introspection.schema.graphql` file that I get from introspecting the server.
In those files, autocomplete should work based on the content of the `test.introspection.schema.graphql`. 
The content of the `main.introspection.schema.graphql` file should NOT show up during autocomplete.
I do not want the files to be used for schema discovery, rely only on the introspected schema.

Why ? 
Because the way we create the schema is not valid GraphQL (we use javascript a lot) so the schema discovery fails and returns lots of errors.
But, the schema generated from introspection is valid and is the one we want to use for autocomplete when creating the schema.

**Comment by jimkyndemeyer** [comment]
This sounds like a chicken and egg dilemma. If I understand you correctly, you want the introspection to drive completion, but the introspection is derived from the schema you want completion for. Schema discovery is what powers the completion so it can't really be turned off.

I don't see how the plugin could support this specific use case and still follow the graphql-config format that the community tools adhere to. You could consider using a code-generation script to generate the appropriate GraphQL SDL files that you're currently using JS templates for. With that approach you don't need to do introspection to get the benefits from the plugin, and you're still able to generate parts of the schema.

Beyond the comments I've already made I don't think I can be of further help. I'm closing the issue on that basis, but feel free to add comments.

Best regards,
Jim.
