### ISSUE TITLE
Uknown types and fields - but they work in the app

### ISSUE THREAD

**Issue by svstartuplab** [jimkyndemeyer/js-graphql-intellij-plugin#270]
## Version and Environment Details
__Operation system__: 

MacOS 10.14.5

__IDE name and version__: 

Webstorm 2019.1 and the 2019.2 EAP

__Plugin version__: 

2.2.0

## Expected Behaviour

Recognize valid GraphQL types and fields.

## Actual Behaviour

Highlights MemberInput as Unknown type "MemberInput" and addMember as Unknown field "addMember".  All my queries and mutations on all components have the same issue.  If I uncheck the plugin in the IDE then this flagging goes away.  The mutations and queries perform as expected either way so this is a plugin, not code, issue.

```
const addMember = gql `
          mutation addMember($input: MemberInput!) {
              addMember (input: $input) {
                  first_name
                  last_name
                  user_name
              }
          }`;

this.apollo.mutate({
          mutation: addMember,
          variables: {
            input: {
              first_name: first_name,
              last_name: last_name,
              user_name: user_name,
            }
          },
        })
        .subscribe(result => {
          console.log('result.data in subscribe: ', result.data);
          errors = result.errors;
          console.log('errors in mutate', errors)
        });
```

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

Just writing a query or mutation causes this.  The schema is compiled by Nestjs on the server as such:

graphql.schema.ts

```
export class MemberInput {
    first_name: string;
    last_name: string;
    user_name: string;
}

export abstract class IMutation {
    abstract addMember(input: MemberInput): Member | Promise<Member>;

    abstract updateMember(member_id: number, input: MemberInput): Member | Promise<Member>;

    abstract deleteMember(member_id: number): Member | Promise<Member>;
}
```
This behavior started recently.  I didn't change the IDE version and I also tried 2019.2 EAP.

**Comment by jimkyndemeyer** [comment]
Hi Jim.

Thanks for using the plugin.

If the plugin marks fields or types as unknown they're most likely not part of the schema discovery you've configured in your project.

The plugin supports GraphQL SDL and Introspection JSON as the two ways of defining your schema. Please review the docs at https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide

Best regards,
Jim

**Comment by svstartuplab** [comment]
Well, from your docs this is what I have had for months and it was working well.  I did upgrades last week, my whole stack on both the Vagrant box and to Angular 8 and that is when the problem began.  My code didn't change except for a couple of unrelated issues during the Angular 8 update.  Nestjs makes one schema from my various module schemas which I posted the relevant parts above.

```
By default, the plugin assumes that your project only contains a single schema.
 If this is the case, you don't need to take any action in terms of schema discovery. 
For a single-schema project, schema types are discovered as follows:

All .graphql files in the "Project files" scope are processed for type definitions 
which are added to a singleton type registry
```

**Comment by jimkyndemeyer** [comment]
A couple of things to check:
- In the GraphQL tool panel it should show the default schema. It should list any errors and how many types it's found during discovery. You can double click the type summary tree node to see type names and associated files they're declared in
- If no types are found, and you do have a `.graphql`file, then verify that it's within the Project scope, e.g. not excluded or in an excluded folder
- As a final step you could do a File menu > "Invalidate caches /Restart". This can solve issues with index corruption during upgrades

**Comment by svstartuplab** [comment]
It can't find the schema on localhost:3000/graphql.
My Angular dev server is finding it and queries and mutations work.  It seems that your 
handy plug-in would also see that schema.  Maybe I'm missing something though.

In my app.module.ts:
```
{
      provide: APOLLO_OPTIONS,
      useFactory: (httpLink: HttpLink) => {
        return {
          cache: new InMemoryCache(),
          link: httpLink.create({
            uri: 'http://localhost:3000/graphql'
          })
        };
      },
      deps: [HttpLink]
    },
```
In the tools panel:

`There is no top level schema defined`

In .graphqlconfig:

```
{
  "schemaPath": "graphql.schema.ts",
  "extensions": {
    "endpoints": {
      "Default (http://localhost:3000/graphql)": {
        "url": "http://localhost:3000/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        }
      }
    }
  }
}
```

In graphql.schema.json in the Angular setup.  I believe this file is deprecated though.

`"file": "graphql.schema.ts"`

```
"endpoints" : [
    {
      "name": "Default (http://localhost:3000/graphql)",
      "url": "http://localhost:3000/graphql",
      "options" : {
        "headers": {
          "user-agent" : "JS GraphQL"
        }
      }
    }
  ]
```

**Comment by svstartuplab** [comment]
I cleared the cache as you instructed.  No help.

**Comment by jimkyndemeyer** [comment]
Thanks for adding your config. I see the issue.

You can't use `"schemaPath": "graphql.schema.ts"`. While the plugin does look for type definitions inside graphql/gql tagged template literals it doesn't support arbitrary framework specific ways of expressing a schema using TypeScript or JavaScript. The schema path, if set, must be a GraphQL or JSON file as per the graphql-config spec.

You need to specify something like ` "schemaPath": "schema.graphql"` and then invoke an introspection such that the plugin writes your endpoint schema to this file. There's an example of how to do this at https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection

**Comment by svstartuplab** [comment]
Nestjs requires the .ts for importing the schema into components.  When I remove it then I can't use GraphQL anywhere.  I couldn't find a fix for this.

app.module.ts on the server:
```
@Module({
  imports: [
    TypeOrmModule.forRoot(),
    GraphQLModule.forRoot({
      typePaths: ['./**/*.graphql'],
      definitions: {
        path: join(process.cwd(), 'src/graphql.schema.ts'),
        outputAs: 'class',
      },
      debug: true,
      playground: true,
    }), ...
```

Introspection does create a graphql.schema file in my project root.  That didn't help so I moved it to the app root and no help either.  This workflow is a pain of course.  I'm developing both sides concurrently and I have to restart both the Angular and Nestjs servers.  Ugh.

**Comment by jimkyndemeyer** [comment]
I'm not suggesting that you remove the ts file, just stating that the plugin doesn't understand it as a schema. The plugin understands two sources of data to build a schema: GraphQL SDL in `.graphql` files, or a JSON file with the result of an introspection query.

The plugin can't support all GraphQL frameworks and programming languages -- there's countless. So it relies on GraphQL SDL or introspection as a standard spec-based way of discovering your schema.

So, two choices to get the benefits from this plugin:
- Author the schema using GraphQL SDL, e.g. like Apollo, and schema discovery is built-in
- Execute an introspection query using the plugin each time your schema changes and write it to a GraphQL SDL file.

The action to introspection supports a key binding for convenience. See the bottom of https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection and #269 

I hope this clears up how best to do schema discovery with your project setup.

Let me know if you have any further questions.

Best regards,
Jim.

**Comment by svstartuplab** [comment]
Nestjs just wraps Apollo Server and creates a consolidated schema for Apollo.  I am using SDL and Playground works fine with it.  Probably can't use your plugin then.  Best to you.

This is what was created by introspection on the client dev side, but your plugin can't find it.

File name graphql.schema

```
# This file was generated based on ".graphqlconfig". Do not edit manually.

schema {
  query: Query
  mutation: Mutation
}

type Member {
  country: String!
  email: String
  first_name: String!
  last_name: String!
  links: String!
  main_skill_title: String!
  member_id: Int!
  member_status: String!
  middle_initial: String!
  other_skills: String!
  pitch: String!
  rating: Int
  skill_id_array: [Int!]!
  skills_comments: String!
  user_name: String
}

type MembersCategories {
  category_id: Int!
  category_name: String!
  industry_id: String!
}

type MembersSubCategories {
  category_id: Int!
  skill_id: Int!
  skill_name: String!
}

type Mutation {
  addMember(input: MemberInput!): Member!
  deleteMember(member_id: Int!): Member
  updateMember(input: MemberInput!, member_id: Int!): Member!
}

type Query {
  checkEmail(email: String): Member
  checkUserName(user_name: String): Member
  getMember(member_id: Int!): Member!
  getMemberCategories(category_id: Int!): [MembersCategories]
  getMemberSubCats(skill_id: Int!): [MembersSubCategories]
  getMembers: [Member]
  getMembersByCountry(country: String!): [Member]
  getSkill(skill_id: ID!): SkillsGQL!
  getSkills: [SkillsGQL]
  lastNameSearch(input: LastNameInput!): [Member]
}

type SkillsGQL {
  category_id: String!
  industry_id: String!
  skill_id: Int!
  skill_name: String!
}

input LastNameInput {
  last_name: String!
}

input MemberInput {
  country: String!
  email: String!
  first_name: String!
  last_name: String!
  links: String!
  main_skill_title: String!
  member_status: String!
  middle_initial: String!
  other_skills: String!
  pitch: String!
  skill_id_array: [Int!]!
  skills_comments: String!
  user_name: String!
}
```

**Comment by svstartuplab** [comment]
Also, it was working fine with the .ts schema until I made upgrades last week as I've said.  My code is the same.  Something broke your plugin, possibly a newer version of Angular with Apollo Client (Apollo-Angular).  Whatever.

**Comment by jimkyndemeyer** [comment]
I took your introspected schema and added it to a blank project which works fine:

![image](https://user-images.githubusercontent.com/15837712/61273609-38c19380-a7aa-11e9-8537-cc10f277aacd.png)

Your use case as I understand it should be fully supported by the plugin. I think your project structure is causing a bug, or it's somehow not setup correctly for the plugin to discover the schema. I can't tell which is the case without an example that reproduces the problem.

**Comment by svstartuplab** [comment]
Thanks, but I've reverted the changes we made back to what I had, which worked before last week's upgrades.  I've disabled your plugin.  However, now I'm stuck with trying to stop GraphQL from hitting my server every 2 seconds with a request for 
![image](https://user-images.githubusercontent.com/5234493/61309731-9ef8e700-a7a7-11e9-9210-54a6237cac01.png)
and much more...

I've rebooted my servers several times and Angular, Vagrant, and Chrome, and cleared Chromes cache, and in Webstorm / File / Invalidate Caches and Restart.  Even with all servers shut down plus Webstorm and Vagrant it continues that request every 2 seconds.  Whatever happened during your instructions for introspection caused this really strange phenomena.  I can't find a solution online after hours of working on this so I guess it isn't common.  Any ideas?

When you plugin was working for the past 5 months or so since I installed Apollo for Nestjs and Angular it was great!  Nothing in my server code changed.  The problem seemed to start after upgrading to Angular 8 and the related Apollo-Angular dependency upgrade.

**Comment by jimkyndemeyer** [comment]
I recall that playground introspects automatically every few seconds using polling unless you opt out in the options object passed when you create the apollo server.

You can also opt out using the settings icon on the top right in playground by editing   `"schema.enablePolling": true`. I think you're seeing this because you cleared your chrome caches and the playground settings are persisted in localStorage.

**Comment by svstartuplab** [comment]
Thanks Jim.  I changed the setting to false but that didn't help.  Then cleared storage in the Chrome dev tools / Application panel.  Still didn't work.  So removed introspection: false in the server setup and rebooted everything, and cleared the storage again.  This finally killed the polling and brought it back to the state I had before this nightmare.

**Comment by svstartuplab** [comment]
I put the that schema above in the app root and it works fine with Playground and in my app.  However, your plugin still doesn't work.  Notice that my original try with this schema had the name wrong which is why it probably didn't work yesterday.  I've blocked Nestjs from creating a consolidated schema for now.

**Comment by svstartuplab** [comment]
Jim, I'm authoring with SDL in each module.  So in the members module I haven an SDL file called members.schema.graphql on the server.  I believe that your plugin was finding this file for the past few months and using it, not the file that Nestjs creates so that we follow the Apollo best practices and have one graphql file at the root level for all modules in the app.  I suspect that all frameworks will be doing that.  Is there some way your plugin could work like Nestjs and discover the various schemas or we can configure it to find the schema?  Maybe the user adds the schemas to an array of module schemas that your plugin monitors?

Introspection was a nightmare.  It would have to happen with every little tweak of the SDL schema which means lots of polling.  Nestjs creates the root schema only during server restarts.

**Comment by jimkyndemeyer** [comment]
The plugin picks up type definitions across all graphql files and graphql/gql tagged templates within the scope of a schema. You can see an example of this at https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives

I'd be happy to take a look at this, but I'd need you to prepare an example Nest project that demonstrates the issue. Please attach that project as a zip file to this issue and I'll see what I can do.

**Comment by svstartuplab** [comment]
Jim, back to you next week.  Thanks!

**Comment by tintin10q** [comment]
He never came back.
