### ISSUE TITLE
Escaped backtickets seems to be unsupported

### ISSUE THREAD

**Issue by smeijer** [jimkyndemeyer/js-graphql-intellij-plugin#279]
```
import gql from 'graphql-tag';

export default gql`
  type User {
    id: ID!
    "Choose a nice username, so users can \`@mention\` you."
    username: String!
    email: String!
  }
`;
```

![image](https://user-images.githubusercontent.com/1196524/62429715-86c71880-b712-11e9-8bee-d0899a60702d.png)

![image](https://user-images.githubusercontent.com/1196524/62429734-a52d1400-b712-11e9-9c90-9c28dbb46370.png)

## Version and Environment Details
__Operation system__: Windows 10

__IDE name and version__: Webstorm 2019.2

__Plugin version__: 2.2.0

## Expected Behaviour
Escaped backticks shouldn't result in errors.

## Actual Behaviour
Backticks result in error highlights in tagged graphql type definitions.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Create a js file with the content posted above.

**Comment by jimkyndemeyer** [comment]
Hi Stephan.

Thanks for using the plugin.

I've implemented a fix for the upcoming 2.2.1 release.

Best regards,
Jim.
