### ISSUE TITLE
Does not load valid schema.json

### ISSUE THREAD

**Issue by Globegitter** [jimkyndemeyer/js-graphql-intellij-plugin#28]
I have a valid generate schema.json in my project root that I am trying to load but all I am seeing is `Watching '/home/markus/Projects/core/graphql.config.json' for changes.`, no errors just silence. If I use the default provided schema I also see the message `Loaded schema from '/path/core/graphql.schema.json':....`

The reason I know it is a valid schema, is because the exact same schema at the exact same location works for us using the `babel-relay-plugin` and its validation. The only think I could imagine, is that it is a quite large schema being over 220KB in size (everything on one line) and maybe it has some issues loading that?

**Comment by jimkyndemeyer** [comment]
Hi Markus.

Thanks for using the plugin.

I think the most effective way to debug this is for you to email me your schema. Without there's unfortunately not much to go on.

My email address is shown to the right in the plugin info at https://plugins.jetbrains.com/plugin/8097?pr=

There was a limit on 100kb before, but I bumped that to 32mb in a previous release.

Best regards,
Jim.

**Comment by Globegitter** [comment]
@jimkyndemeyer just sent it over.

**Comment by jimkyndemeyer** [comment]
Thanks for the schema.

The language service expects `schema.json` to be the result of an introspection query, which means that the root field should be called `data` per the GraphQL spec. In your case the root field is called `__schema`, which is expected to be the only child of the `data` field.

This means that the language service [doesn't load the schema.](https://github.com/jimkyndemeyer/js-graphql-language-service/blob/master/src/languageservice.js#L73-L75), so it never forwards the data to [buildClientSchema](https://github.com/graphql/graphql-js/blob/master/src/utilities/buildClientSchema.js#L79-L90) in Facebook's `graphql-js`.

You should be able to fix this by following the convention, so I'm curious how you generated your schema.json?

**Comment by Globegitter** [comment]
Ahhh that makes sense, we are using the introspection query that graphene (https://github.com/graphql-python/graphene) provides: https://github.com/graphql-python/graphene/blob/024f670c4d31a547eecd55d51e04d8a290fae049/graphene/types/schema.py#L67

Strangely enough that does work with the `babel-relay-plugin` out of the box. Is that something that should be fixed in graphene/our build system, or can support for that be added in the langauge service?

**Comment by jimkyndemeyer** [comment]
I think that [schema.py#L68](https://github.com/graphql-python/graphene/blob/024f670c4d31a547eecd55d51e04d8a290fae049/graphene/types/schema.py#L68) does somewhat [break](https://github.com/relayjs/relay-examples/blob/master/star-wars/data/schema.json#L2) [convention](https://github.com/relayjs/relay-examples/blob/master/todo/data/schema.json#L2), but I could make the language service check if the `__schema` field is on the root object and not `data`. I've logged https://github.com/jimkyndemeyer/js-graphql-language-service/issues/7 for that change.

It's a small change to the language service so I should have time to implement it during the weekend. Better a change here than break other tools by changing their established conventions.

**Comment by jimkyndemeyer** [comment]
Regarding why `babel-relay-plugin` work for you: Note the use of `.data` in https://github.com/facebook/relay/tree/master/scripts/babel-relay-plugin#usage

You've probably edited your plugin configuration at some point to not expect `.data`

**Comment by Globegitter** [comment]
It has been almost a year now since I set this up for our team, so can't fully remember anymore I have to admit. But interestingly enough https://facebook.github.io/relay/docs/guides-babel-plugin.html#content differs a bit from the readme (or at least doesn't specify what `parsedSchemaJSON` is compared to `schemaData` on the website).

In any case, it would be much appreciated if you could implement https://github.com/jimkyndemeyer/js-graphql-language-service/issues/7, since it would be quite some effort to modify it in our environment.
