### ISSUE TITLE
Custom headers don't work

### ISSUE THREAD

**Issue by tufgupmi** [jimkyndemeyer/js-graphql-intellij-plugin#280]
Hello 

I would like the plugin to send custom headers in the HTTP Request, only "Authorization" header is working. 

I have this  .graphqlconfig
```

{
  "name": "Remote Schema",
  "schemaPath": "remote-schema.graphql",
  "extensions": {
    "endpoints": {
      "API ADMIN": {
        "url": "http://localhost:8094/graphql",
        "headers": {
          "User-Agent": "JS GraphQL",
          "Authorization": "Basic eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJBRE1JTiIsImp0aSI6IjUwMTUzIiwiZXhwIjoyMTYwMjQ5MDQ1LCJtaW51dGVzIjoxMDAwMDAwMCwidG9rZW5QYXJhbWV0ZXJzIjoie1widXNlcklkXCI6NTAxNTMsXCJhdXRoUm9sZXNcIjpudWxsLFwicm9sZXNCeUtleVwiOm51bGx9In0.22CvG5QLdROXLreogecrTF3BQgGLEqwWB0xetLLM4IQ",
          "Content-Language": "EN"
        },
        "introspect": true
      },
}
```

When i send any graphql request, in the server only is received the "Authorization" header, I would like the "Content-Language" and any other header i configure be send in the request.

Thank you

**Comment by jimkyndemeyer** [comment]
Hi Fernando.

Thanks for using the plugin.

The plugin doesn't limit which headers it sends for requests. I tried adding a `test-header` and `content-language` header which go through just fine with an Apollo GraphQL server:

![headers](https://user-images.githubusercontent.com/15837712/63418534-895c8a00-c403-11e9-937a-73a526d2be6a.png)

I did however notice that the casing of the header name is different (at least with Apollo). Could that be the reason you don't see the header value as coming through?

Best regards,
Jim.
