### ISSUE TITLE
Cannot load schema from excluded folder

### ISSUE THREAD

**Issue by danez** [jimkyndemeyer/js-graphql-intellij-plugin#281]
## Version and Environment Details
__Operation system__: 
macOS 10.14.6

__IDE name and version__: 
PhpStorm 2019.2
Build #PS-192.5728.108, built on July 24, 2019

__Plugin version__: 
2.2.0
(worked in 1.7.4)

## Expected Behaviour

Schema which reside in excluded folders should be loadable

## Actual Behaviour

Schema does not get loaded at all

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

* Create Folder
* Right Click -> mark Directory as -> Excluded
* Put schema in this directory
* link to it in .graphqlconfig

**Comment by jimkyndemeyer** [comment]
Hi Daniel.

Thanks for using the plugin.

Excluded folders restrict the project files indexing that schema discovery builds on top of, so this current behavior is in line with what's expected on the InteliJ platform.

I'd like to understand your use case. Why do you need to exclude the folder that the schema is placed in? As stated, this expectation goes against how project indexing works on the IntelliJ platform.

Best regards,
Jim.

**Comment by danez** [comment]
Our schema gets generated from PHP annotations and is ignored in git. This is why we put it into our build folder, where all the build artifacts go, which is ignored in PHPStorm.
I guess if there is no option to make it work in the current plugin, we have to find a new location which is ignored in git but not excluded.

**Comment by jimkyndemeyer** [comment]
Hi Daniel.

Yeah, I recommend that you go for the included but git-ignored schema file.

I'm closing this issue on that basis.

Best regards,
Jim.
