### ISSUE TITLE
Introspection Query does not work (exception)

### ISSUE THREAD

**Issue by EugenEistrachKC** [jimkyndemeyer/js-graphql-intellij-plugin#283]
## Version and Environment Details
__Environment__:  Windows 10

__IDE name and version__: Intellij 2019.2

__Plugin version__:  2.2.0

## Expected Behaviour
Schema should be created

## Actual Behaviour
**.graphqlconfig:**
![grafik](https://user-images.githubusercontent.com/45036228/62737142-64ddd680-ba2f-11e9-9f46-96c710a41dd5.png)

**The introspection query returns the following result:**
https://pastebin.com/0xY40rYp

**And this is plugin exception:**
https://pastebin.com/raw/MaZhted1

I'm not sure if I'm doing something wrong but **GraphiQL** works without any problems:
![grafik](https://user-images.githubusercontent.com/45036228/62737452-1bda5200-ba30-11e9-875b-8b339364fdf3.png)

**Comment by jimkyndemeyer** [comment]
Hi Eugen.

Thanks for using the plugin.

The plugin uses `graphql-java` to build up a validated schema based on the introspection result. In this case the exception you attached indicates that the schema has a number of errors.

Specifically, there's a type called `SchemaProxy` which has a `directives` field with the output type `__Directive`. The exception states that `The field type '__Directive' is not present when resolving type 'SchemaProxy`, meaning that the schema is referring to an unknown type that isn't included in your schema.

The weird thing is that `__Directive` is part of the introspection types:  https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/resources/META-INF/graphql%20specification%20schema.graphql

I haven't encountered any other introspection results that tried to extend or make use of the introspection schema types before, so this is a first. Did you declare the `SchemaProxy` type yourself, or is it built-in to the GraphQL framework you're using?

As for a fix, the only way to get the schema to work with this plugin and `graphql-java` right now would be to not return the `SchemaProxy` type from your endpoint when it's introspected.

As for a more long term solution, I'm not sure whether introspection results are allowed to make use introspection types such as `__Directive`. This may require clarification in the GraphQL spec or a change in this plugin and/or `graphql-java` schema validation.

Best regards,
Jim.

**Comment by EugenEistrachKC** [comment]
I was using KGraphQL: https://kgraphql.in/
I decided to switch to graphql-java & https://github.com/ExpediaDotCom/graphql-kotlin which worked out in the end.
