### ISSUE TITLE
Go to Definition always scrolls to the top of the schema

### ISSUE THREAD

**Issue by AOrobator** [jimkyndemeyer/js-graphql-intellij-plugin#289]
## Version and Environment Details
__Operation system__: Mac OS 10.14.6

__IDE name and version__: 
Android Studio 3.5

__Plugin version__: 
v2.2.0

## Expected Behaviour
When I invoke go to definition on a graphql query I'm editing, I expect to be taken to the point in the schema where the property I'm interested in is defined.

## Actual Behaviour
Schema always scrolls to top of file.

**Comment by jimkyndemeyer** [comment]
The JetBrains team will take a look at this in https://youtrack.jetbrains.com/issue/IDEA-222678

**Comment by AOrobator** [comment]
Thanks for the update! At least there's a workaround for now.

**Comment by denofevil** [comment]
@jimkyndemeyer looks like the problem is caused by https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/master/src/main/com/intellij/lang/jsgraphql/v1/ide/project/JSGraphQLLanguageUIProjectService.java#L253 which scrolls editor to the very beginning.

**Comment by jimkyndemeyer** [comment]
@denofevil Ah, thanks. good catch. I think the issue is that the newly inserted header pushes some of the editor lines outside of the view. I'll see if I can figure out a way to simply restore the scroll position to what it was before the header was inserted.

**Comment by danez** [comment]
The same also happens in PHPStorm.

**Comment by jimkyndemeyer** [comment]
Fixed in the upcoming 2.3.0.
