### ISSUE TITLE
Add GraphQL configuration page for indentation

### ISSUE THREAD

**Issue by sibelius** [jimkyndemeyer/js-graphql-intellij-plugin#29]
I use 2 spaces on my Webstorm, this plugin is using 4 spaces, it should keep with the same indentation property of the IDE

**Comment by jimkyndemeyer** [comment]
Hi Sibelius.

I didn't implement configurable indentation yet, so it's using the "Other File Types" configuration:

![image](https://cloud.githubusercontent.com/assets/15837712/18774242/7a36415c-8157-11e6-8854-d1ebd6db173f.png)

I'll see if I can slip this into a release this weekend.

/Jim.

**Comment by sibelius** [comment]
I'll try here, thanks

Awesome plugin btw

Maybe it should just follow JavaScript configuration, as the reference implementation it is on JavaScript

**Comment by sedubois** [comment]
Agreed, I encounter the same issue (but the mentioned workaround of changing 'other file types' works well). Maybe reopen this?

**Comment by jimkyndemeyer** [comment]
The next release will include a Code Style page for GraphQL where indentation can be configured.

It doesn't look like the IntelliJ API supports "contextual" indentation based on language injection, e.g. when GraphQL is used in a JS file. So indentation is the same across GraphQL use cases.

**Comment by sedubois** [comment]
Alright, thanks 😊
