### ISSUE TITLE
Syntax colors with Monokai theme isn't working.

### ISSUE THREAD

**Issue by frederikhors** [jimkyndemeyer/js-graphql-intellij-plugin#290]
Syntax colors with Monokai theme isn't working.

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

The GraphQL syntax highlighting uses the "Language defaults" to do the highlighting (see the "Inherit values from on the right):

![image](https://user-images.githubusercontent.com/15837712/66505194-2023f980-eacb-11e9-88b6-a627058822d0.png)

For the Monokai theme you may need to tweak the colors to your liking.

**Comment by jimkyndemeyer** [comment]
Closing this based on the screenshot above. If that doesn't resolve the issue, add version info and steps to reproduce to make this actionable (as was also stated in the issue template).
