### ISSUE TITLE
Load schema from endpoint

### ISSUE THREAD

**Issue by jbarop** [jimkyndemeyer/js-graphql-intellij-plugin#298]
In GraphQL Config a schema can be specified by an endpoint (https://graphql-config.com/docs/schema#endpoint).

It would be nice if `js-graphql-intellij-plugin` would support fetching schemas from remote endpoints.

**Comment by jimkyndemeyer** [comment]
Hi Johannes.

Thanks for using the plugin.

The link you posted points to a version of `graphql-config` that is quite new and not yet supported by this plugin. They've recently reached out to start talks on this in #296. 

For now you can follow https://blog.jetbrains.com/webstorm/2019/04/featured-plugin-js-graphql/ and https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection on how to load your schema using this plugin.

They suggested a version indication in the new format might be needed to avoid this kind of confusion.

Best regards,
Jim.

//cc @kamilkisiela
