### ISSUE TITLE
Other languages

### ISSUE THREAD

**Issue by alexisvincent** [jimkyndemeyer/js-graphql-intellij-plugin#30]
How possible would it be to extend this plugin (even just the syntax highlighting) to other languages?

Such as clojure?

**Comment by jimkyndemeyer** [comment]
Hi Alexis.

I'm not sure I understand your question. Do you mean GraphQL injected in a clojure file similar to what `Relay.QL` does in JavaScript and TypeScript? If you do, it's bad news. I just checked with the "La Clojure" plugin, and it appears that the string literals don't support injected languages like JS/TS does.

The option you do have though is to write GraphQL queries and mutations in `.graphql` files and load them from the classpath. See [my previous comment](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/8#issuecomment-215779616).

Hope this answers your question.

/Jim.

**Comment by alexisvincent** [comment]
Yeah, that's exactly what I mean. What about the cursive plugin? Are you able to see? Cursive is the standard plugin for clojure.

**Comment by alexisvincent** [comment]
Thank you for your quick responce

**Comment by jimkyndemeyer** [comment]
I checked with the Cursive plugin and it too also doesn't support language injection in string literals.

I suggest you log an issue with JetBrains about supporting this. This plugin won't do auto injection, but you can enable injection using a comment in your code. See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/20#issuecomment-240073351 for details.
