### ISSUE TITLE
Entering values for env variables used in ".graphqlconfig"

### ISSUE THREAD

**Issue by alex83130** [jimkyndemeyer/js-graphql-intellij-plugin#300]
## Version and Environment Details
__Operation system__: macOS

__IDE name and version__: IntelliJ IDEA Ultimate 2019.2

__Plugin version__: 2.2.0

## Expected Behaviour
I need to pass a token to my file config (Token is storage in the local-storage of the browser). Do you know a way to do this ?
Thanks a lot

**Comment by jimkyndemeyer** [comment]
Hi Alexis.

Thanks for using the plugin.

See the graphqlconfig in https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/github-api-v4 for how to include tokens such as for authentication.

Best regards
Jim.

**Comment by alex83130** [comment]
Thanks for your quickly aswer.
I see this example but I don't understand how and where put the env variable in upstream.

**Comment by jimkyndemeyer** [comment]
Hi Alexis.

I'm not sure what you mean by "where put the env variable in upstream".

Can you describe what you're trying to do, and what's not working?

**Comment by alex83130** [comment]
I try to pass an external variable in the .graphqlconfig, in your exemple you've `${env:GITHUB-ACCESS-TOKEN}`, but where do you provide this variable ?

Thanks :)

**Comment by jimkyndemeyer** [comment]
Ah, you'll see a dialog where you can enter it when you execute a query or introspect the endpoint to fetch a schema. The dialog will remember your last entered value until you restart your IDE. Simply press enter the following time you see the dialog to reuse an existing value.

Hope that clears it up.

**Comment by alex83130** [comment]
Ah ok I get it, thanks a lot !
