### ISSUE TITLE
Unknown directive @client 

### ISSUE THREAD

**Issue by victororlyk** [jimkyndemeyer/js-graphql-intellij-plugin#302]
## Version and Environment Details
__Operation system__: 
MacOS Catalina 10.15.1
__IDE name and version__: 
WebStorm 2019.3
__Plugin version__: 
2.2.0
## Expected Behaviour
no error highliting on @client directive
## Actual Behaviour
it says `Unknown directive @client`
<img width="1057" alt="Screenshot 2019-12-09 at 14 59 17" src="https://user-images.githubusercontent.com/33072590/70438181-edc85580-1a95-11ea-89d2-46de1ef60b2b.png">

**Comment by jimkyndemeyer** [comment]
Hi Viktor.

Thanks for using the plugin.

This is intended behaviour as the plugin ships with the built-in directives and should mark unknown directives as errors.

See https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives for how to set this up properly.

**Comment by victororlyk** [comment]
Thank you!

**Comment by jazzdragon** [comment]
I think this would be enough of a common use case to warrant a section in the docs.
