### ISSUE TITLE
introspection not working

### ISSUE THREAD

**Issue by rolandjohann** [jimkyndemeyer/js-graphql-intellij-plugin#306]
## Version and Environment Details
__Operation system__: Mac OS

__IDE name and version__: IntelliJ 2019.3

__Plugin version__: 2.3.0

## Expected Behaviour
Setup plugin with `.graphqlconfig` content:
```json
{
  "name": "Remote Schema",
  "schemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "Remote GraphQL Endpoint": {
        "introspect": true,
        "url": "http://localhost:9000/graphql"
      }
    }
  }
}
```
and introspect schema should work.

## Actual Behaviour
Get introspection Error at IntelliJ, the graphql endpoint receives a POST with json body `{"query":"http://localhost:9000/graphql"}` which leads to an error response. Searched the docs, but maybe I'm missing something.

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

I think you may have entered your endpoint URL in GraphQL preferences page where you can replace the actual introspection query being sent. If that's the case, simply clear that field and you should be good to go.

**Comment by jimkyndemeyer** [comment]
![image](https://user-images.githubusercontent.com/15837712/71547904-6a1fcb80-29a6-11ea-881f-94fa02cb30c3.png)

**Comment by rolandjohann** [comment]
perfect, misread the label. Thanks for your quick response between the years @jimkyndemeyer !
