### ISSUE TITLE
[FEATURE] I use graphql merge libraby

### ISSUE THREAD

**Issue by MegaJSDeveloper** [jimkyndemeyer/js-graphql-intellij-plugin#309]
I use the library to combine many schemes into one, how can I make sure that the TYPE DECLARATION check is carried out only within the framework of one file? A check of REQUESTS for the scheme would take into account the scheme in ALL files =)?

![image](https://user-images.githubusercontent.com/58376230/72180840-162ad300-33f9-11ea-97d2-1ed1d81e51c7.png)

![image](https://user-images.githubusercontent.com/58376230/72180849-1e830e00-33f9-11ea-9aad-8e8ab75787d6.png)

![image](https://user-images.githubusercontent.com/58376230/72180867-2478ef00-33f9-11ea-9ac8-600bdd7862df.png)

Decision:
---
Make a trivial checkmark in the settings "evaluate parts of the graphql code independently", and in this mode your plugin will not swear overriding some type. But the syntax will be highlighted correctly. Indeed, in javascript, if some function is declared several times with that name, then when you poke the name of the function with a wheel, it simply suggests choosing which declaration to go to, do the same. and 90% of the problems associated with your plugin will disappear =)

**Comment by jimkyndemeyer** [comment]
If you'd like to add fields to the same Query type in a single schema, but from across a number of `.graphql` files, the spec-compliant way to do this is using the `extend` keyword:

```graphql
extend type Query {
  fieldYouWantToAdd: YourFieldType
}
```

Or, If you're seeing an unexpected "tried to redefine" error, you'll need to configure how the plugin discovers your schema(s). See https://github.com/jimkyndemeyer/graphql-config-examples and https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide

Using `.graphqlconfig` files and their `includes/excludes` fields the plugin can understand a wide array of project structures. On that basis I prefer to avoid having additional configuration options that control schema discovery.
