### ISSUE TITLE
Feature Request: Add support for multiple graphql files / graphql-import

### ISSUE THREAD

**Issue by blowsie** [jimkyndemeyer/js-graphql-intellij-plugin#313]
[graphql-import](https://oss.prisma.io/content/graphql-import/overview) allows you to define mutliple `.graphql` files with their own `Query` and `Mutation` types.

eg.
schema.graphql
```
# import Query.*, Mutation.* from "posts.graphql"
# import Query.*, Mutation.* from "users.graphql"
```

posts.graphql
```
type Post {
  id: ID!
  text: String!
}

type Query {
  posts: [Post]
}

type Mutation {
  deletePost(id: ID!): Post!
}
```

users.graphql
```
type User {
  id: ID!
  username: String!
}

type Query {
  users: [User]
}

type Mutation {
  deleteUser(id: ID!): User!
}
```

As far as I know, This extenstion does currently not allow for this.

Here are the errors
![image](https://user-images.githubusercontent.com/308572/74047460-4cdc1500-49c8-11ea-8f4a-ef03dad1d6c4.png)

---

Is it possible to configure the plugin to prevent the errors, if is it possible to support graphql import somehow ?

**Comment by jimkyndemeyer** [comment]
Hi Sam.

Thanks for using the plugin.

The plugin has a goal of following the GraphQL spec to ensure it works with as many setups and frameworks as possible.

The spec-compliant way to do what you're attempting is to use the `extend` keyword on your query and mutation types. See https://github.com/jimkyndemeyer/graphql-config-examples/blob/master/extend-client-fields-and-directives for examples of how Apollo does this.

For your example you would declare your schema.graphql as follows:
```graphql
type Query {}

type Mutation {}
````

This makes the types available for extension in the other graphql files which the plugin will pick up automaticallly based on https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide#project-structure-and-schema-discovery

Your schema should then validate according to spec, and the plugin should no longer show any errors.

Hope this helps.

Best regards,
Jim.

**Comment by blowsie** [comment]
Great thanks! I will give this a go, need to make sure I will be able to import all of the schemas still.

In short I was unaware of the `extend` keyword

**Comment by blowsie** [comment]
Works perfectly.
