### ISSUE TITLE
There is no top level schema object defined - when configured for a remote schema endpoint

### ISSUE THREAD

**Issue by cognivator** [jimkyndemeyer/js-graphql-intellij-plugin#315]
## Version and Environment Details
__Operation system__: OS X 10.14.6

__IDE name and version__: Webstorm 2019.3

__Plugin version__: 2.3.0

## Expected Behaviour
Using the `.graphqlconfig` found in the examples, https://github.com/jimkyndemeyer/graphql-config-examples/blob/master/remote-schema-introspection/.graphqlconfig, I should be able to force the remote schema query using the double-arrow in the Graphql tool window.

## Actual Behaviour
The Graphql tool window shows the following error,
```
Remote Schema
  Schema discovery summary - schema is empty
  Schema errors
    There is no top level schema object defined
  Endpoints
    Remote GraphQL Endpoint - https://portal.ehri-project.eu/api/graphql
```
The double-arrow is NOT enabled when 'Remote Schema' is selected.
Also, FWIW, the example graphql endpoint at gdom is no longer valid... it times out in a browser.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Create a `.graphqlconfig` file in the root of a client graphql project with no other explicit schema definitions. Some queries exist within the project, as graphql-tag template strings.

The content of `.graphqlconfig` is copy-tweaked from the samples, with the endpoint changed from gdom (which does not respond) to a different public graphql endpoint found at https://github.com/APIs-guru/graphql-apis.

`.graphqlconfig` contents
```
{
  "name": "Remote Schema",
  "schemaPath": "./schema.graphql",
  "extensions": {
    "endpoints": {
      "Remote GraphQL Endpoint": {
        "url": "https://portal.ehri-project.eu/api/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        }
      }
    }
  }
}
```

## Intent
My client application must query from several disparate graphql endpoints with their own, unique schemas. I am looking for a way for Graphql plugin to allow proper inspection / intention within the queries defined in graphql-tag template strings.

My project will NOT be defining its own schema, nor do I want to enable any tooling that attempts to create queries or mutations.

I'm successfully using `graphql-codegen` to generate Typescript type declarations from downloaded graphql introspection JSON files for the remote schemas. The last step is to get Webstorm to provide appropriate, useful help within gql template strings, and to automatically fetch updates from the remote schema endpoints.

Please advise.

**Comment by jimkyndemeyer** [comment]
Hi, thanks for using the plugin.

If I recall correctly, the double arrow is to re-run a previously executed introspection, but that might not be clear from the current UI.

Please take a look at https://blog.jetbrains.com/webstorm/2019/04/featured-plugin-js-graphql/

It should guide you through how to fetch the remote schema.

Best regards,
Jim.
