### ISSUE TITLE
Unparsed default value in interface implementation

### ISSUE THREAD

**Issue by nyffenem** [jimkyndemeyer/js-graphql-intellij-plugin#316]
## Before you create the issue
Nothing related found in existing issues of FAQ.

## Version and Environment Details
__Operation system__: Windows 10 Enterprise, Version 1809

__IDE name and version__: Intellij IDEA Ultimate 19.3 / Runtime Version 11.0.5

__Plugin version__: 2.3.0

## Expected Behaviour
No errors in parsing graphqls

## Actual Behaviour
Errors in parsing graphqls:
[GraphQLPlugin-Stacktrace.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/4219705/GraphQLPlugin-Stacktrace.txt)

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Define an interface element containing field with parameters for which one is a list with  a default value:
'''
interface Partner{
  #a few fields...
  gegebeneVollmachten( 
    #a few fields,
     freigabeStatusCode: [BdvCode!] = ["2"]
    ): [Vollmacht!]!
}

With at least one implementation:
type NatuerlicherPartner implements Partner{
#a few fields...
  gegebeneVollmachten( 
    #a few fields,
     freigabeStatusCode: [BdvCode!] = ["2"]
    ): [Vollmacht!]!
}

This is not parsed correctly by the plugin. The GraphQL tab displays the attached stack-trace in the "Schema errors" section. But compiled and launched, it works fine.

**Comment by vepanimas** [comment]
Works in 3.0.0.
