### ISSUE TITLE
Fields named "on" not allowed

### ISSUE THREAD

**Issue by fwal** [jimkyndemeyer/js-graphql-intellij-plugin#318]
## Version and Environment Details
__Operation system__: macOS 10.15.3

__IDE name and version__: Android Studio 3.6.1

__Plugin version__: 2.3.0

## Expected Behaviour
Types and enums should be able to have fields named `on`.

My first thought was that `on` was a reserved name (due to the fragment `on` declaration) but I didn't find anything in the specs that disallowed `on` as a name:
- Names - https://spec.graphql.org/June2018/#sec-Names
- Enum -  https://spec.graphql.org/June2018/#sec-Enum-Value
- Reserved names - https://spec.graphql.org/June2018/#sec-Reserved-Names

## Actual Behaviour
The plugin returns schema errors `The field type 'X' is not present when resolving type 'Y'` and/or `Unexpected token: "on"`.

## Steps to Reproduce / Link to Repo with Reproduction and Instructions
Most simple form:
```GraphQL
# schema.graphql

type Switch {
    on: Boolean
}

# > Unexpected token: "on"
```
How I discovered it:
```GraphQL
# schema.graphql

enum Switch {
    off
    on
}

type Control {
    switch: Switch
}

# > The field type 'Switch' is not present when resolving type 'Control'
```

**Comment by fwal** [comment]
Possible duplicate of #264

**Comment by jimkyndemeyer** [comment]
Yup, same issue as #264
