### ISSUE TITLE
Detailed getting started doc would be helpful

### ISSUE THREAD

**Issue by dboreham** [jimkyndemeyer/js-graphql-intellij-plugin#32]
This is probably due to some lack of knowledge on my part, but I wasn't able to figure out how to use the plugin. I have it installed in Webstorm and I can see the menu items to create graphql files. I've also configured Node in Webstorm. What I can't see how to do is get any content in the graphql files with syntax highlighting and so on (like in the screen shots). So I figured since the screen shots come from the relay-examples projects, I'd try those. Still can't figure out how to get what's in the screen shots..

It would be great if there were some step-by-step instructions that detailed how to go from "git clone" on the relay-examples to having the screen shot example images in your own webstorm. For example in the screen shots I see a file "query.graphql" -- should we create that file? (I did try that but it didn't seem to help).

Thanks.

**Comment by jimkyndemeyer** [comment]
Hi dboreham.

Thanks for using the plugin.

Once installed, the plugin should show a "Create a graphql.config.json" notification bar at the top of any editor that contains graphql. This includes editors with tagged templates such as Relay.QL and gql, or as you mentioned .graphql files. Syntax highlighting should work right away, before configuring a schema using graphql.config.json.

I suspect there might be an issue with the language service that runs as a Node process. Can you attach a screenshot of your WebStorm with the console tab of the graphql toolwindow shown?

![image](https://cloud.githubusercontent.com/assets/15837712/18921316/937e988e-85a4-11e6-81c1-9337af10d593.png)


/Jim

**Comment by dboreham** [comment]
Hi, I'm pretty sure the Node stuff is configured and working ok. I'm reproducing the problem on a new clean machine now to be absolutely sure: if I begin with the relay starwars example checked out from github, should I see the graphql plugin active on any of its source files (I don't), or do I need to add a new file to the project? If so what file do I add? Thanks.

**Comment by jimkyndemeyer** [comment]
You don't have to add anything to the star wars example for the plugin to work. Syntax highlighting should work, and the editor gutter should have the orange relay icon to indicate the plugin is active:

![image](https://cloud.githubusercontent.com/assets/15837712/18922349/80ced682-85a8-11e6-8a56-ddefb7ece5fe.png)

If you don't see exactly the same thing, I'd like you to attach the screenshot I requested with the graphql console.

**Comment by dboreham** [comment]
Ok, progress. The secret sauce is that you must open that file (or a file with a reference to Relay.QL). Opening other more plausible files (to me) such as schema.json or schema.js will not trigger the plugin. 
So now (having opened StarWarsApp.js) I have the "Create a graphql.config.json...?" prompt at the top of the window. Should I say yes?

**Comment by jimkyndemeyer** [comment]
Yup. Go ahead and create the graphql.config.json. You can then follow the steps shown in the readme.md animted gifs where you edit "file" to be "data/schema.json". Then you're all set.

**Comment by dboreham** [comment]
Ok, got it going thanks. 
Annimated gif probably isn't the best medium for a tutorial because there is no clear beginning point to the sequence.

**Comment by jimkyndemeyer** [comment]
Just updated the FAQ section based on this issue.

Can you review?

**Comment by dboreham** [comment]
Thanks, the updated faq looks good.

**Comment by richburdon** [comment]
Sorry @jimkyndemeyer I don't understand this.

I've never seen the "Create a graphql.config.json...?" prompt. When I edit files with Relay.QL I see the orange "S" icon in the gutter but it just opens "https://facebook.github.io/relay/docs/api-reference-relay-ql.html" and my types are redlined (i.e., not recognized). The GraphQL console reads:

JS GraphQL listening on http://127.0.0.1:49827/js-graphql-language-service
Setting Project Dir '/Users/burdon/projects/src/alienlaboratories/react-demos'

And in Current Errors, it shows the types that are not interpreted.
Error:(74, 19) Unknown type "User".

Suggestions:
1. Can you outline a process to manually create the graphql.config.json file (where does it go, what is the format?)
2. Probably more work, providing a Preferences panel would be the standard way to configure the plugin?

The plugin looks great. Can't wait to try it out.

Thanks.

**Comment by jimkyndemeyer** [comment]
@richburdon Hi Rich. Thanks for using the plugin.

The graphql.config.json that ships with the product is [available here](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/master/resources/META-INF). Add the config file to your /Users/burdon/projects/src/alienlaboratories/react-demos directory. Then edit the "file" JSON field in the config to point the plugin at your schema.json. You should see the errors go away, and be able to complete on type names, fields, etc.

/Jim.
