### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Narek123** [jimkyndemeyer/js-graphql-intellij-plugin#321]
gql inspection not working on ubuntu 18.04
![IDE Fatal Errors_002](https://user-images.githubusercontent.com/17179184/76081823-653d5080-5fc3-11ea-8aaa-eb8b6c074251.png)

**Comment by jimkyndemeyer** [comment]
Please follow the issue template to make the issue actionable.

Without steps to reproduce this issue cannot be addressed.

**Comment by jimkyndemeyer** [comment]
Not actionable, will reopen if details about how to reproduce are provided.
