### ISSUE TITLE
Autocompletion plugin doesn't work in AppCode

### ISSUE THREAD

**Issue by denys-meloshyn** [jimkyndemeyer/js-graphql-intellij-plugin#331]
## Before you create the issue
- Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions.

## Version and Environment Details
__Operation system__: 
Mac OS 10.15.4

__IDE name and version__: 
AppCode 2019.3.7 
Build #OC-193.6911.31, built on March 25, 2020

__Plugin version__: 
2.4.0

## Expected Behaviour
The same schema in `Android studio`
<img width="728" alt="Screenshot 2020-04-17 at 09 16 54" src="https://user-images.githubusercontent.com/1679724/79542611-3fa86a00-808c-11ea-9ff4-82eebcce127b.png">

## Actual Behaviour
The same schema in `AppCode`
<img width="865" alt="Screenshot 2020-04-17 at 09 04 53" src="https://user-images.githubusercontent.com/1679724/79542373-ce68b700-808b-11ea-8bcf-a466d0d911c1.png">

**Comment by jimkyndemeyer** [comment]
Hi Denys,

Thanks for using the plugin.

Do you have the same issue with the examples in https://github.com/jimkyndemeyer/graphql-config-examples?

Best regards,
Jim.

**Comment by denys-meloshyn** [comment]
Hi Jim,
Sorry, I'm not sure which URL to use from examples. I've tried `http://gdom.graphene-python.org/graphql` but its not available

**Comment by denys-meloshyn** [comment]
@jimkyndemeyer found my issue, I copied `.graphqlconfig` from `Android Studio` where `schemaPath` was `schema.json` but `Appcode` creates `schemaPath: schema.graphql`. So after I change the extension it works fine, I'll close the ticket.
