### ISSUE TITLE
Support for graphql-config v3

### ISSUE THREAD

**Issue by Xample** [jimkyndemeyer/js-graphql-intellij-plugin#335]
Hi, just a note, graphql-config is now in v3

https://github.com/kamilkisiela/graphql-config/releases

I don't know if js-graphql-intellij-plugin parses the config or relies on an engine, so it might be relevant to post it here.

**Comment by jimkyndemeyer** [comment]
Hi Flavian,

Thanks for the heads up.

This is already tracked in #296. See my comment there why it's unlikely that this plugin can adopt v3.

**Comment by Xample** [comment]
Thank you for your quick answer. I actually came to the v3 as an attempt to fix a problem I will open another issue to track it down.
