### ISSUE TITLE
The parent selection or operation does not resolve to a valid schema type

### ISSUE THREAD

**Issue by dandv** [jimkyndemeyer/js-graphql-intellij-plugin#340]
## Before you create the issue
- [x] Please search the existing issues at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc before opening a new issue.
- [ ] Read the FAQ at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq - **no FAQ there**

## Version and Environment Details
__Operation system__: Ubuntu 20

__IDE name and version__: WebStorm 2020.2 EAP, Build #WS-202.4357.21, built on May 26, 2020

__Plugin version__: 2.4.0

## Steps to Reproduce / Link to Repo with Reproduction and Instructions

I use graphql-modules on the server, and in my web app I have a `.tsx` file with this query

```js
gql`
    query($id: ID!) {
      product(id: $ID) {
        id
      }
    }
  `
```

On the server, the schema looks like this:

```ts
export const ProductModule = new GraphQLModule({
  imports: [
    AuthModule,
  ],

  typeDefs: gql`
    scalar DateTime

    input ProductInput {
      ...
    }

    "Alias: Item"
    type Product {
      id: ID!
      "Alias: title"
      name: String!
      ...
    }

    type Query {
      "Find product by id"
      product(id: ID!): Product
      ...
    }
```

I can work on a reproduction repo upon request.

**Comment by jimkyndemeyer** [comment]
Hi Dan,

Thanks for using the plugin.

Using the SDL you've shown I don't get an error. Please add a reproduction.

Thanks.

**Comment by davoam** [comment]
@jimkyndemeyer Hi! 

Thanks for the plugin! 

I also had this error after upgrading to version `2.5.0`. All my queries became invalid, and all had this error `The parent selection or operation does not resolve to a valid schema type`. 

I downgraded to version `2.4.0` and everything works fine

**Comment by vepanimas** [comment]
@davoam hello! I'm trying to reproduce this one, could you please provide a minimal reproducible example? Or if it's not possible, provide any information as described in this comment https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/348#issuecomment-680949314?

**Comment by davoam** [comment]
@vepanimas I read your comment and solved the problem. Thanks! 

I have a script which generates GraphQL schema. When I run it, it uses some files to generate final schema. It complained that some instances are defined in final schema and in these files. For example, `SomeInput` was defined in final schema file and in these files which I use to generate final schema.
```
input SomeInput {
        someNumber: Int!
        someString: String!
    }
```

I have added files which I use to generate final schema to `excludes` section of plugin config file (`.graphqlconfig`). 

Now everything works

**Comment by vepanimas** [comment]
@davoam thank you for the info, that's very helpful! I'm working now on improving the user experience for the case when some types/fields are duplicated. It definitely shouldn't break such features as resolve and autocomplete, and the errors should be more meaningful.

**Comment by vepanimas** [comment]
@dandv it should work better with graphql-modules in the 2.6.0 version, so I'm closing this now. If you encounter any problems, please feel free to report them, it will be very appreciated!
