### ISSUE TITLE
Support highlighting of arbitrary strings in within javascript files

### ISSUE THREAD

**Issue by AdityaAnand1** [jimkyndemeyer/js-graphql-intellij-plugin#342]
More often than not, I have GraphQL queries in my JS code itself (which is a better pattern for solutions like postgraphile, hasura).

Right now, the plugin does not highlight strings such as:

```
export const mutation = email => `mutation insert_email_to_waitlist {
  insert_waitlist(
    objects: {
      email: "${email}"
    }
  ) {
    affected_rows
  }
}`;
```

Highlighting such strings would be a great addition to the plugin 🚀

**Comment by jimkyndemeyer** [comment]
Hi Aditya,

Thanks for using the plugin.

Detecting GraphQL in arbitrary JS strings would require running the GraphQL parser over all strings, resulting in a performance hit in all JS editors.

I recommend you use a language injection comment: `//language=GraphQL`

This comment is picked up in the same way as the graphql/gql tagged templates, causing the editor to consider the next template string as GraphQL.

```JavaScript
//language=GraphQL
export const mutation = email => `mutation insert_email_to_waitlist {
  insert_waitlist(
    objects: {
      email: "${email}"
    }
  ) {
    affected_rows
  }
}`;
```

Best regards,
Jim
