### ISSUE TITLE
Support for Apollo Client "@client" directive

### ISSUE THREAD

**Issue by fromi** [jimkyndemeyer/js-graphql-intellij-plugin#343]
Apollo provides a directive `@client` which is used for local state management, as documented here: https://www.apollographql.com/docs/react/data/local-state/

If I use their example:
```
const GET_VISIBILITY_FILTER = gql`
  {
    visibilityFilter @client
  }
`;
```
The plugins highlights 2 errors:
* Unknown directive "client"
* Unknown field "matchmaking" on object type "Query"

Is there some easy way to configure the plugin so that he understands Apollo's client directive, and that it is normal if visibilityFilter is not described in any schema in that case?

**Comment by jimkyndemeyer** [comment]
Hi Romain,

Thanks for using the plugin.

Please review https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/extend-client-fields-and-directives

Best regards,
Jim.

**Comment by fromi** [comment]
Awesome, thanks for the great work!
