### ISSUE TITLE
Improve semantic highlighting for Monokai theme

### ISSUE THREAD

**Issue by frederikhors** [jimkyndemeyer/js-graphql-intellij-plugin#350]
**Describe the bug**
Syntax colors with `Monokai` theme isn't as expressive and clear as with `Darcula` scheme.

**Expected behavior**
It would be amazing to have different colors to increase readability also with `Monokai`.

**Screenshots**
![image](https://user-images.githubusercontent.com/41120635/85221530-add31b00-b3b4-11ea-8e78-6c45c537a5f4.png)

![image](https://user-images.githubusercontent.com/41120635/85221500-80866d00-b3b4-11ea-97dd-52cfc46c680f.png)

**Version and Environment Details**
Operation system: Windows 10
IDE name and version: Goland 2020.1.3
Plugin version: 2.5.0

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

The syntax highlighting relies on the default language colors shown on the right here to work best across the different IDEs:

![graphql-syntax-colors](https://user-images.githubusercontent.com/15837712/85227816-d9b7c600-b3df-11ea-9337-b4946c4f190e.png)

The API itself for picking the colors is quite simple, and it's my understanding that it can't target specific themes. As such I don't see this as actionable from my side.

You'll need to set those language defaults within the Monkai theme, or override them specifically in the GraphQL settings.

Best regards
Jim

**Comment by frederikhors** [comment]
So, I don't understand, whose fault is it?

**Comment by jimkyndemeyer** [comment]
It's not really a fault, more a set of limitations in the API, combined with the complexity of supporting different IDEs that support different programming languages. This means that for this plugin, the colors that make sense from a syntax highlighting perspective are the ones coming from the "Default Language" set: 

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/d83dad8bc30b528b6cc9928408ea7e77df6b16bb/src/main/com/intellij/lang/jsgraphql/ide/GraphQLSyntaxHighlighter.java#L27-L55

Different themes will use these colors default differently, some may even ignore them completely to provide their own. My point is that even though I would like the colors to make sense for all themes, I don't see how to achieve this with the IntelliJ Platform API for syntax highlighting.

If you're not happy with the GraphQL colors as they appear with the Monokai theme, you'll need to either tweak the "Default Language" colors within the Monkai theme, or override them specifically in the GraphQL color settings.

**Comment by frederikhors** [comment]
I opened this: https://youtrack.jetbrains.com/issue/GO-9528.

**Comment by frederikhors** [comment]
Thanks for your commitment.

**Comment by frederikhors** [comment]
There is an answer here, @jimkyndemeyer: https://youtrack.jetbrains.com/issue/GO-9528#focus=streamItem-27-4210084.0-0,

**Comment by frederikhors** [comment]
Is there a way I can change editor schema only for GraphQL, @jimkyndemeyer?

Can you please see that thread with the answer for you, @jimkyndemeyer? (https://youtrack.jetbrains.com/issue/GO-9528#focus=streamItem-27-4210084.0-0)

**Comment by frederikhors** [comment]
@vepanimas shoud I change them manually? One by one?

Can we copy Monokai colors for Graphql from somewhere and create a PR?

**Comment by vepanimas** [comment]
I looked at the implementation of highlighting and I have a few thoughts on this, I will look at it later, perhaps in the next release.

**Comment by vepanimas** [comment]
@frederikhors what monokai theme do you use exactly? There are many of them in the marketplace.

**Comment by frederikhors** [comment]
![image](https://user-images.githubusercontent.com/41120635/139582880-2bfda7c4-547a-45f8-9160-0b85808b42d0.png)

The default one.

**Comment by vepanimas** [comment]
So, I've finally done it. Will be available in the next release.

Before:

<img width="750" alt="monokai-before" src="https://user-images.githubusercontent.com/10243762/139593385-0b9e77de-86d9-4f30-952f-33bad1a9d9ea.png">

After:

<img width="798" alt="monokai-after" src="https://user-images.githubusercontent.com/10243762/139593391-5e478a5a-470f-4561-b4db-9618ac7b1974.png">
