### ISSUE TITLE
Parse .graphql and convert JSON response to .graphql problems since +- 2.4.0

### ISSUE THREAD

**Issue by Bast1onCZ** [jimkyndemeyer/js-graphql-intellij-plugin#359]
Hello, these are my problems that started since updating to the newest versions 2.4.0 or 2.5.0. Schema is still the same, this plugin used to work properly in past.

- [ ] Special characters (such as regexp braces) in comment cause error
![image](https://user-images.githubusercontent.com/28895562/90312387-5b216580-df04-11ea-816a-b2ba16fb7a89.png)

- [ ] If graphql schema json response contains encoded characters in comments such as `"`, they get converted to real character that breaks comment string

Schema source and graphql format converted version:
[graphql schema.zip](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/5078635/graphql.schema.zip)

**Comment by vepanimas** [comment]
@Bast1onCZ Actually the [GraphQL grammar](http://spec.graphql.org/draft/#StringCharacter) for string characters prohibits using `\` and `"` inside of a string. To get it working you should escape those symbols with `\` like `//^[a-z0-9\\-]{1,64}$//`.

But we could try to improve error handling for these cases though, I'll look into that.

**Comment by vepanimas** [comment]
Hmm, it seems that the open file in the IDE on your screenshot confused me. So it's not handwritten, the real issue is that the schema response is converted to this invalid schema by the plugin itself, right?

**Comment by vepanimas** [comment]
Thanks for the report, I'' look into that.

**Comment by omavi** [comment]
@Bast1onCZ, thanks for reporting. @vepanimas, thanks for addressing this so fast! Any idea when this fix will be released?

**Comment by vepanimas** [comment]
@omavi we plan to fix a few more issues and release it by the end of the week.

**Comment by omavi** [comment]
@vepanimas awesome, thanks so much!
