### ISSUE TITLE
Query execution not working on Fragments

### ISSUE THREAD

**Issue by fforw** [jimkyndemeyer/js-graphql-intellij-plugin#365]
When I go into my query definitions in Javascript and press ALT+Enter to invoke the "Edit GraphQL Fragment" action, the fragment opens but I cannot execute it. This used to work.

The .graphqlconfig that lies in the project root is not regarded. 

![Bildschirmfoto von 2020-08-18 20-54-49](https://user-images.githubusercontent.com/226774/90553680-15c79700-e195-11ea-9556-15b016ab8dee.png)
The dropdown is empty and I cannot execute the query.

Executing queries from scratch files keeps working.

Ubuntu 18.04.5 LTS
IntelliJ current 2020.2
JS GraphQL 2.5.0

 [Minimized reproducing example](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/5092270/gql-bug.zip)

**Comment by vepanimas** [comment]
Hi @fforw! Thank you for the report. This may be related to #356 and may already be fixed, but not released. I'll check it out.
