### ISSUE TITLE
Error running JS GraphQL Language Service using Node.js

### ISSUE THREAD

**Issue by sedubois** [jimkyndemeyer/js-graphql-intellij-plugin#37]
After uninstalling one version of Node, I keep getting this error, don't know how to clear it.
```
Error running JS GraphQL Language Service using Node.js: Cannot run program "/Users/sdubois/.nvm/versions/node/v6.2.2/bin/node" (in directory "/Users/sdubois/Library/Application Support/IntelliJIdea2016.2"): error=2, No such file or directory
```

**Comment by jimkyndemeyer** [comment]
Could be that your Node.js settings need to be updated, specifically the path to the Node.js interpreter:

![image](https://cloud.githubusercontent.com/assets/15837712/19850623/b359dec4-9f59-11e6-872b-1109f5523d8d.png)

**Comment by sedubois** [comment]
No, in that window it displays the right one (and in general I'm able to run things in this project without issue):

<img width="759" alt="screen shot 2016-10-31 at 12 05 42" src="https://cloud.githubusercontent.com/assets/4217871/19850684/70a86c18-9f62-11e6-9223-408e09945de8.png">

**Comment by jimkyndemeyer** [comment]
That setting indicates version 6.9.1 and the path it complains about is "/Users/sdubois/.nvm/versions/node/v6.2.2/bin/node". Maybe IDEA caches the symbolic link, because it's providing the path to run Node.js.

**Comment by sedubois** [comment]
Maybe, although the issue has been there for a few days and I restarted IntelliJ multiple times meanwhile.

**Comment by jimkyndemeyer** [comment]
Can you check your .idea/workspace.xml for the following setting:

```<property name="nodejs_interpreter_path" value="/usr/local/bin/node" />```

**Comment by jimkyndemeyer** [comment]
Ah, might have found it. The plugin uses the default Node.js interpreter. If you click the ".." button next to your node path, make sure the first path in the dialog is correct.

**Comment by sedubois** [comment]
OK it really seems to have been a caching issue or something, because I just went back to open the same screen, and now it properly display that something is fishy:

<img width="743" alt="screen shot 2016-10-31 at 12 21 04" src="https://cloud.githubusercontent.com/assets/4217871/19851039/8e1bcf18-9f64-11e6-8bb9-af841b604400.png">

I selected the proper version, so shouldn't experience the issue any more. Thanks, propose to close.

**Comment by david-benes** [comment]
I have the same issue (reported with stacktrace in #68), but I wasn't as lucky as @sedubois.
I see C:\Program Files (x86)\nodejs\node.exe in the config dialog, but js-graphql calls nodejs at \usr\local\bin\node.exe (this path does not exist in Windows).
I don't know where does \usr\local path come from. It is not in any of my configs.

```    <property name="js-jscs-nodeInterpreter" value="C:\Program Files (x86)\nodejs\node.exe" />```

The only relevant reference I found was in webstorm.jar. If there is some fishy caching issue, I wasn't able to overcome it.

I'm now suspecting webstorm core modules. Maybe my Windows is being confused with Ubuntu because it now contains Windows Subsystem for Linux.

Any help would be appreciated.

**Comment by jimkyndemeyer** [comment]
Hi David. I've added a reply in #68. Let's continue the discussion there.
