### ISSUE TITLE
How to create gql scope?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [jimkyndemeyer/js-graphql-intellij-plugin#370]
I have backend type definitions:
![image](https://user-images.githubusercontent.com/69426460/91254631-88271100-e76b-11ea-80b0-e095398a6658.png)

i have autogenerated schema file:
![image](https://user-images.githubusercontent.com/69426460/91254721-c1f81780-e76b-11ea-81dd-a8ec71680d4a.png)

how can I set that the schema file belongs to a different scope and that it shouldn't conflict with other files?
![image](https://user-images.githubusercontent.com/69426460/91254747-d63c1480-e76b-11ea-8245-72a9e947ff2c.png)

I am generating a `schema.graphql` file to be PRESENT in the project for adding code completion. How to specify that the graphql files in the `/api/src` folder are isolated from the rest of the project and should not conflict with it?

I'll explain easier:
-
 I have two folders `backend` and `frontend`, graphql intersect in them (one is generated based on the other), how can I indicate that these are two different scopes so that the error is not highlighted?

**Comment by MaxmaxmaximusAWS** [comment]
Lol, solution:

We shoud create two `.graphqlconfig` files in two scopes:

```
/backend/.graphqlconfig
/fronteend/.graphqlconfig
```

**Comment by vepanimas** [comment]
@MaxmaxmaximusAWS actually, do you need to generate a separate schema file if you have all type definitions in the same project? They should be used for completion without any additional steps.

**Comment by MaxmaxmaximusAWS** [comment]
@vepanimas no, I'm using a framework that generates a graphql schema based on PostgreSQL tables =) https://www.graphile.org/postgraphile/

**Comment by vepanimas** [comment]
@MaxmaxmaximusAWS oh, ok, I got it. That looks quite promising. I don't do web development anymore, but I will definitely look at this tool.

**Comment by MaxmaxmaximusAWS** [comment]
@vepanimas uh, you mean it accidentally worked? but I configured scopes correctly =) I thought it was done on purpose.

But if you add this to the settings, as well as automatic introspection with a polling interval (and if there is a difference in the scheme, overwrite the file), then it would be perfect =)
