### ISSUE TITLE
Remote schema doesn't refresh (or I don't know how to)

### ISSUE THREAD

**Issue by estaub** [jimkyndemeyer/js-graphql-intellij-plugin#38]
My `graphql.config.json` points at an url.  The schema is rapidly evolving on the server.  The plugin doesn't seem to update its local copy of the schema at all.  

How do you get the plugin to see remote schema changes?  The hack I'm using for now is to edit the  `graphql.config.json` file, which triggers a schema refetch.

**Comment by jimkyndemeyer** [comment]
Hi Ed.

Thanks for using the plugin.

Please see the last section in the [FAQ](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq)

**Comment by jimkyndemeyer** [comment]
Closing based on thumbs up :)
