### ISSUE TITLE
there is an error when using cypher and relation directive

### ISSUE THREAD

**Issue by adogsa** [jimkyndemeyer/js-graphql-intellij-plugin#385]
**Describe the bug**
i use neo4j DB and graphql in intellij. but there is an error with cypher directive in intellij. please fix an error with cypher an relation directive

**To Reproduce**
https://grandstack.io/docs/graphql-custom-logic/#the-cypher-graphql-schema-directive

**Comment by jimkyndemeyer** [comment]
Hi adogsa,

If I understand your issue correctly, you're seeing errors on directives in your schema?

The plugin ships with the built-in directives that are part of the GraphQL specification. Any additional directives you need to declare yourself.

See https://github.com/jimkyndemeyer/graphql-config-examples/blob/b417cbc065f8dbcbbef83cb727b616976f731f7f/extend-client-fields-and-directives/client-schema-extensions.js#L6 for an example of how it's done for the Apollo GraphQL framework.

**Comment by jimkyndemeyer** [comment]
Closing on the basis that this is resolved. Feel free to add a comment if that's not the case.
