### ISSUE TITLE
How to use Lokka's .mutate method

### ISSUE THREAD

**Issue by schickling** [jimkyndemeyer/js-graphql-intellij-plugin#39]
The GraphQL client Lokka provides two abstraction concepts out of the box: `client.query` and `client.mutate`. The latter one automatically injects the `mutation` keyword for you when building the request (I'm not a big fan of this behaviour tbh).

I assume `js-graphql-intellij-plugin` doesn't know when to check for the query vs mutation namespace? 

Here is an example:

```js
  // works
  await client.query(gql`{
    allPosts {
      id
    }
  }`)

  // doesn't work
  await client.mutate(gql`{
    createPost(
      title: "Hello World"
    ) {
      id
    }
  }`)
```

**Comment by jimkyndemeyer** [comment]
Yes, the plugin only transforms `${...}` placeholders. It doesn't attempt to fix "broken/non-standard" GraphQL by adding "mutation MyMutation".

I think the most robust way forward is to update Lokka client to allow a valid GraphQL mutation. If the mutation keyword and name is missing, Lokka can add it automatically to preserve backwards compatibility. This will not break existing client code, but allow for better IDE integration.

**Comment by schickling** [comment]
I agree. @arunoda any thoughts on this? 🙂

**Comment by arunoda** [comment]
We use kind of a customized syntax for mutations for faster usage without the help from libraries like this:

In order to use this, you could simply use .query as a mutation.

```js
await client.query(gql`
   mutation {
      ...
   }
`)
```

**Comment by schickling** [comment]
Thanks @arunoda. That's also what we've went for by now. I'm closing this as this seems to be a reasonable approach.
