### ISSUE TITLE
Add fragment suggestion

### ISSUE THREAD

**Issue by ykad4** [jimkyndemeyer/js-graphql-intellij-plugin#4]
Hi, thank for your awesome plugin, very useful!
It would be nice to suggest fragment after the "...", if it's not too much to ask.
Thank you again.

**Comment by jimkyndemeyer** [comment]
Hi Yasser.

Glad you found the plugin to be useful.

The completion list is powered by https://github.com/graphql/codemirror-graphql that also powers https://github.com/graphql/graphiql by Facebook

If you create the feature request in the codemirror-graphql repo, GraphiQL users will also be able to take advantage of the improvement.

From what I remember of the spec, there are two uses of `...`, namely `...MyFragmentName` and `... on MySchemaType`. They require separate types of completion.

/Jim

**Comment by ykad4** [comment]
Ok, thank you.
I have made a [feature request](https://github.com/graphql/codemirror-graphql/issues/7), hope we will get it

**Comment by jimkyndemeyer** [comment]
As part of the work on #3 I've added completion based on the fragments defined in the current file. 

One limitation is that it doesn't filter on whether the type of that fragment is applicable at the location, but it should hold you over until support lands in codemirror-graphql.

This version should land some time within the next week or so, including find usages and other improvements.

/Jim.

**Comment by ykad4** [comment]
Awesome, Thanks.

**Comment by jimkyndemeyer** [comment]
@ykad4 I just pushed v1.1.0 to the JetBrains repository.

Check for plugin updates in IntelliJ and you'll get the improved completion along with the schema viewer and find usages.

I'll leave this issue open until I can include the improvement from an updated version of codemirror-graphql.

Let me know if you have any issues.

Cheers,
/Jim.

**Comment by ykad4** [comment]
Great job,

It works like a charm so far; I will let you know if a run with any issue. 

Thanks.

**Comment by ykad4** [comment]
Hi Jim,

The [feature request](https://github.com/graphql/codemirror-graphql/issues/7) was fulfilled and released in [v0.2.2](https://github.com/graphql/codemirror-graphql/releases/tag/v0.2.2).

Cheers.

**Comment by jimkyndemeyer** [comment]
Released as 1.1.1 and added to JetBrains Repo.
