### ISSUE TITLE
Template replacement produced invalid token text range

### ISSUE THREAD

**Issue by schickling** [jimkyndemeyer/js-graphql-intellij-plugin#40]
When trying to use literal template interpolation syntax I'm getting the following error and Webstorm freezes so I have to force quit it:

![untitled-1](https://cloud.githubusercontent.com/assets/1567498/20462668/0c7d5b0a-af24-11e6-9461-2f1b71a87699.jpg)

I'm not sure if this is related to Webstorm 2016.3 since I didn't see this happening before

**Comment by jimkyndemeyer** [comment]
Thanks for catching this. I'll attempt to reproduce.

I think the issue may be that there's more than one placeholder on the same line. The challenge is to transform the placeholder text ranges into something that will not trigger a GraphQL validation error. If I remember correctly, the strategy is to use `__typename`, but in this case there's not enough room, so the language service might fall back to inserting a `#` comment token, which clashes with this particular use case.

/Jim.

**Comment by jimkyndemeyer** [comment]
The language service uses a combination of substitution and error marker filtering to support templating in Relay, Apollo, and Lokka environments. The intent is to produce syntactically valid GraphQL and prevent false validation errors. This strategy works for most use-cases, but it has its limits.

I think the only real solution for this kind of GraphQL templating is adding templating to the GraphQL specification and clearly defining the semantics.

Regarding this specific issue, the latest version of the language service no longer appears to lock the UI or produce an invalid token range. It's included in the next plugin release.

/cc @asiandrummer
