### ISSUE TITLE
Release an update for Android Studio version of this great plugin

### ISSUE THREAD

**Issue by mwajeeh** [jimkyndemeyer/js-graphql-intellij-plugin#406]
Can we please have all new goodies in Android Studio version too https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/tree/android-studio. It has been two years since last version.

**Comment by jimkyndemeyer** [comment]
Hi Muhammad,

The 2.x versions of the plugin, which you can find directly in your plugins search dialog, works out of the box with Android Studio. I'll update the Android branch to indicate this.

Best regards,
Jim.
