### ISSUE TITLE
Does .graphql file extension not supported?

### ISSUE THREAD

**Issue by darron1217** [jimkyndemeyer/js-graphql-intellij-plugin#409]
**Before you create the issue**
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions
- Please search the [existing issues](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc) before opening a new issue
- Review the [developer guide](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide)
- Review the [example projects](https://github.com/jimkyndemeyer/graphql-config-examples)

**Describe the bug**
`schema.graphql` file not recognized as graphql file. (Highlighting not applied)
![image](https://user-images.githubusercontent.com/8064923/97847600-38e4fa00-1d33-11eb-8487-650cac908443.png)

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. Install Plugin
2. Create `schema.graphql` file
3. open it

**Expected behavior**
It works when I change file extension as `schema.graphqls`.

`.graphql` and `.graphqls` should work same!

**Screenshots**
![image](https://user-images.githubusercontent.com/8064923/97847871-9ed18180-1d33-11eb-88cf-2d4e7f5bc2a9.png)

**Version and Environment Details**
Operation system: Mac Catalina 10.15.7
IDE name and version: Webstorm 2020.2.3
Plugin version: 2.6.0

**Additional context**

**Comment by darron1217** [comment]
I found that `schema.graphql` rule on `File Type` setting...

I wonder why this rule added to my setting...

Anyway solved

**Comment by OHUSAR** [comment]
@darron1217 Hello. Can you please explain, how exactly did you solve this? Thanks!

**Comment by darron1217** [comment]
@OHUSAR 
I've searched for graphql file type in perferences. Just like below
![image](https://user-images.githubusercontent.com/8064923/99146843-2a95c700-26bf-11eb-82e2-e3d595c9a211.png)

**Comment by OHUSAR** [comment]
@darron1217 Thank you! Did this and then needed to reload the IDE for some reason.
