### ISSUE TITLE
Bug: Ctrl+Tab not working

### ISSUE THREAD

**Issue by gengjiawen** [jimkyndemeyer/js-graphql-intellij-plugin#41]
If you use `ctrl+b` to go to graphql declarateion, then click `ctrl+tab` to switch back the previous file, but this is not working in Webstorm.

**Comment by jimkyndemeyer** [comment]
Hi Jiawen.

Thanks for using the plugin.

I've tried to reproduce this in WebStorm and IntelliJ. But I'm able to switch back and forth between the files as expected. Do you have any additional details on how to reproduce this?

Thanks,
Jim.

**Comment by gengjiawen** [comment]
I am using Webstorm `2016.3.1`.
It's a bug will ocurr every time.And using the `back` and `forth` in toolbar works fine.

**Comment by jimkyndemeyer** [comment]
Thanks, I'll try that specific version.

Can you elaborate on "not working". What did you expect to see/happen. What happens instead?

**Comment by gengjiawen** [comment]
## Steps:
1.In `file A`, use hotkey `ctrl+b` to go to graphql declarateion, now we are in schema `file B`
2.`ctrl+tab` to switch back to `file A`
## What do you expect:
> ctrl+tab to switch back the `file A`

## What happen:
> switch to other `file C`.(`File C` is the file I am in before I am in `File A`)

**Comment by jimkyndemeyer** [comment]
Thanks for the detailed description.

I've tried to reproduce with WebStorm 2016.3.1, but it's working as expected:

![zic2jgbsye](https://cloud.githubusercontent.com/assets/15837712/20626227/9b336518-b318-11e6-9424-50865e99fc9b.gif)

I start in app.js, use ctrl+b to navigate to StarWarsAppHomeroute.js and then onto the schema.

**Comment by gengjiawen** [comment]
Maybe something wrong with my config or Mac, I am closing this issue.Thanks.

**Comment by gengjiawen** [comment]
This is a bug on webstorm, if you choose hide tabs in `Editor>General>Editor Tabs>Tab Appearence`, this will triger this bug.
