### ISSUE TITLE
Unable to resolve .graphqlconfig in project with multiple IntelliJ modules

### ISSUE THREAD

**Issue by tobiasgwaaler** [jimkyndemeyer/js-graphql-intellij-plugin#411]
First, a big thank you to everyone contributing to this plugin, it makes working with GraphQL in IntelliJ a joy :)

**Describe the bug**
I have a project with multiple modules (IntelliJ modules) and two different GraphQL-schemas: `client` and `admin`. Each has an api and a frontend, and I would like the `admin-frontend` to use the GraphQL-schema defined in `admin-api` while `client-frontend` should use the schema from `client-api`:

```text
myproject
 |-- .graphqlconfig                   <- this will never be found from admin-schema.graphql or client-schema.graphql
 |
 |-- backend
 |    |-- admin-api (module)
 |    |   \-- admin-schema.graphql
 |    |
 |    |-- client-api (module)
 |        \-- client-schema.graphql
 |-- frontend
 |    |-- admin-frontend (module)
 |    |   \-- admin-queries.graphql    <-- should use the schema from admin-schema.graphql
 |    |
 |    |-- client-frontend (module)
 |         \-- client-queries.graphql  <-- should use the schema from client-schema.graphql
```

I have a `.graphqlconfig` at the root, with multiple projects as described in [the example](https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/two-schemas-plus-shared-using-projects):

```json
{
  "projects": {
    "admin": {
      "name": "Admin Api GraphQL Schema",
      "includes": ["backend/admin-api/**", "frontend/admin-frontend/**"]
    },
    "client": {
      "name": "Client Api GraphQL Schmema",
      "includes": ["backend/client-api/**", "frontend/client-frontend/**"]
    }
  }
}
```

But the trouble is that the `.graphqlconfig` can not be found when placed outside the current IntelliJ-module. This seems to be intentional, as all the methods that are resposible for finding `.graphqlconfig`-files will stop at the nearest `contentRoot`, as defined in [GraphQLConfigManager::getContentRoots](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/8011e9d9732477be71ec12b607004c62d40e0ceb/src/main/com/intellij/lang/jsgraphql/ide/project/graphqlconfig/GraphQLConfigManager.java#L741). However, that method has a fallback when a module can not be found that simply uses `ProjectUtil::guessProjectDir`. When I use that "project directory" as the `contentRoot`, everything works the way I want it to. Could that be a solution, or would that break in some other cases I have not considered?

Maybe this would solve https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/384 as well?

**Comment by vepanimas** [comment]
@tobiasgwaaler hi! I think it's fixed in https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/423, could you check if this works for you now if you are still using the plugin?

**Comment by tobiasgwaaler** [comment]
@vepanimas Yes, now it works perfectly! Thank you so much  🙏
