### ISSUE TITLE
Support .gql files

### ISSUE THREAD

**Issue by MichaelDeBoey** [jimkyndemeyer/js-graphql-intellij-plugin#413]
At this moment the plugin only supports `.graphql` files, but I would like to see support for `.gql` files too if possible.

**Comment by vepanimas** [comment]
@MichaelDeBoey hi! It's already fixed in #390, but not released yet.

**Comment by MichaelDeBoey** [comment]
Awesome! 👊

Sorry to have missed that btw

**Comment by vepanimas** [comment]
@MichaelDeBoey I hope it will happen next week after I'll fix some more issues.

**Comment by MichaelDeBoey** [comment]
Would be awesome.
Thanks for all your great work! 👊
