### ISSUE TITLE
"Tried to redefine existing type" error in a monorepo setup using Lerna and Yarn Workspaces

### ISSUE THREAD

**Issue by aleksejkozin** [jimkyndemeyer/js-graphql-intellij-plugin#419]
**Describe the bug**
- I'm using the plugin with Webstorm
- I'm using Apollo graphql engine
- I'm working on a monorepo project
- the project is powered by lerna and yarn workspaces
- the project consists of several independent subprojects in `./packages`
- each subproject in `./packages` is a private npm module with a `package.json`
- some of these projects have independent graphql schema files
- each graphql schema file has type definition `type Query` and `type Mutations` 
-  when I open such schema in my Webstorm I get a linting error: "'Query' type [@7:1] tried to redefine existing 'Query' type [@15:1]"
- somehow types defined in one schema files affect types defined in a different schema file. If I delete `type Query` in one file, then I will get rid of the linting error in another. But these files should be completely independent, they belong to different npm packages.

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
https://github.com/aleksejkozin/monorepo-graphql-issue-example

**Expected behavior**
There should be no lining error because the schema files are independent of each other.

**Screenshots**
<img width="587" alt="Screenshot 2020-12-05 at 16 35 00" src="https://user-images.githubusercontent.com/6328300/101244534-2a19aa80-3718-11eb-9d9d-095fb58508f2.png">

**Version and Environment Details**
Operation system: macOS Catalina
IDE name and version: Webstorm 2020.3
Plugin version: 2.7.0

**Additional context**

**Comment by jimkyndemeyer** [comment]
Hi Aleksey,

Thanks for using the plugin.

The plugin makes no assumptions about how you structure your projects, which means that you need to configure schema discovery as stated in the documentation. See https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide and https://github.com/jimkyndemeyer/graphql-config-examples for reference.

Best regards,
Jim

**Comment by jimkyndemeyer** [comment]
Closing this on the basis that your linked repo has no .graphqlconfig files that control schema discovery, but feel free to add comments, questions etc.

**Comment by aleksejkozin** [comment]
@jimkyndemeyer oh, sweet, I didn't know, that you can control the schema discovery. Thank you!
