### ISSUE TITLE
Assertion failed: Caret model is in its update process. All requests are illegal at this point.

### ISSUE THREAD

**Issue by sibelius** [jimkyndemeyer/js-graphql-intellij-plugin#42]
![image](https://cloud.githubusercontent.com/assets/2005841/20603715/ecb994cc-b249-11e6-9a63-45159f3f183d.png)

**Comment by jimkyndemeyer** [comment]
Hi Sibelius.

Thanks for catching this.

Can you describe the steps to reproduce and your IntelliJ/WebStorm version?

Thanks,
Jim.

**Comment by sibelius** [comment]
latest webstorm version 

![image](https://cloud.githubusercontent.com/assets/2005841/20607071/95fc10b6-b25c-11e6-828e-23e6b0470cbf.png)

it stopped working, then I reinstalled and it worked well again

I do not have more information, sorry

**Comment by jimkyndemeyer** [comment]
Ok. From the stack trace this may have happened during query execution. Let me know if you manage to reproduce it.

**Comment by jimkyndemeyer** [comment]
Hi Sibelius.

I've commited a fix that should prevent this assertion error. I'll include it in the next release of the plugin.

/Jim

**Comment by sibelius** [comment]
awesome, thanks for this awesome work in this plugin.

it is really handy 💯

**Comment by sibelius** [comment]
@jimkyndemeyer any release date for the next release?

this is making the plugin stop working on my webstorm, I need to reinstall the plugin to make it work again

**Comment by jimkyndemeyer** [comment]
Released in v1.4.4 and pushed to JetBrains Plugin repository moments ago.

**Comment by sibelius** [comment]
tks
