### ISSUE TITLE
autocomplete is broken in latest phpstorm\webstorm

### ISSUE THREAD

**Issue by oknesar** [jimkyndemeyer/js-graphql-intellij-plugin#420]
**Description**
Parameters autocomplete is broken at query/mutation editing when using language injection.
 
**To Reproduce**
create graphql fragment in js/ts file, start to edit query/mugation (autocomplete doesn't appear)
![image](https://user-images.githubusercontent.com/16972422/101455927-f61ecf00-393b-11eb-8683-7a1edfaed356.png)
if open the same fragment into sepatered graphql tab autocomplete works okay
![image](https://user-images.githubusercontent.com/16972422/101455953-fdde7380-393b-11eb-8e7a-b237f4f80374.png)
![image](https://user-images.githubusercontent.com/16972422/101455969-046ceb00-393c-11eb-8818-94dfa037e520.png)

**Version and Environment Details**
Operation system: Linux 5.4.0-56-generic #62-Ubuntu SMP Mon Nov 23 19:20:19 UTC 2020 x86_64 GNU/Linux
IDE name and version: PhpStorm 2020.3 Build #PS-203.5981.175, built on December 2, 2020
Plugin version: 2.7.0

**Comment by garyro** [comment]
Thought I would add this seems to be webstorm also

**Comment by jean9696** [comment]
Same issue in webstorm :'(

**Comment by oknesar** [comment]
I've noticed that with russian keyboard layout the autocomplete works 
![image](https://user-images.githubusercontent.com/16972422/104716335-7c46e600-5730-11eb-833f-4c8cbe0edcb3.png)
but not with english 
![image](https://user-images.githubusercontent.com/16972422/104716410-94b70080-5730-11eb-949e-dc312ef1cb51.png)

**Comment by vepanimas** [comment]
@oknesar hi! Could you please check it in the recent 2.7.1 release?

**Comment by oknesar** [comment]
@vepanimas hi! It's fixed, thanks very much!
