### ISSUE TITLE
No .graphqlconfig file found in gradle subprojects

### ISSUE THREAD

**Issue by simPod** [jimkyndemeyer/js-graphql-intellij-plugin#423]
**Describe the bug**

I'm in 4th level subfolder where my query resides. 

I clicked plugin gear icon

![image](https://user-images.githubusercontent.com/327717/102875171-bda2e900-4443-11eb-8176-cdab056220e3.png) 

Which produces info: "No .graphqlconfig file found. Searched current and parent directories."

![image](https://user-images.githubusercontent.com/327717/102875091-a237de00-4443-11eb-871a-7fdff4c3f772.png)

The .graphqlconfig file is in project root directory though.

![image](https://user-images.githubusercontent.com/327717/102875148-b4b21780-4443-11eb-89de-f3a194c84735.png)

**To Reproduce**

This is only when gradle project is initialized in IDEA

https://github.com/simPod/js-graphql-gradle-bug

`subproject/src/main/graphql/app/github-query.graphql`

**Comment by vepanimas** [comment]
Hi, thank you for the report! Fixed it, will be released soon.
