### ISSUE TITLE
Random highlights

### ISSUE THREAD

**Issue by rowario** [jimkyndemeyer/js-graphql-intellij-plugin#424]
https://user-images.githubusercontent.com/14127958/103003609-207aaa00-4542-11eb-9751-7f1640e29422.mp4

**Comment by vepanimas** [comment]
@rowario hi! Unfortunately, this is a platform issue and it is present in the 2020.3 version. It's already fixed but still is not released. https://youtrack.jetbrains.com/issue/IDEA-253378
