### ISSUE TITLE
Plugin cannot handle gzip response

### ISSUE THREAD

**Issue by petja** [jimkyndemeyer/js-graphql-intellij-plugin#427]
**Describe the bug**
Plugin cannot handle gzip response

**To Reproduce**
1. Create `.graphqlconfig` file
2. Set endpoint as `https://rata.digitraffic.fi/api/v2/graphql/graphql`
3. Set header `accept-encoding` to value `gzip` (mandated by the API)
4. Run introspection query
5. See garbage in Query result tab (gzipped data)

**Expected behavior**
Plugin is able to handle gzip response

**Version and Environment Details**
Operation system: macOS 11.2
IDE name and version: WebStorm 2020.3.1 EAP **and** WebStorm 2020.2.4
Plugin version: 2.7.1

**Comment by vepanimas** [comment]
@petja hi, thank you for the report! It's fixed and will be released soon.
