### ISSUE TITLE
AWS types (appsync) not recognized 

### ISSUE THREAD

**Issue by ziutus** [jimkyndemeyer/js-graphql-intellij-plugin#429]
Plugin is reporting error when I'm using using AWS types like AWSDate, AWSPhone etc. see [https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html](https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html)

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

The plugin ships with the schema type definitions that are part of the GraphQL standard. New GraphQL frameworks arrive all the time, and they change their schema definitions, so it's not feasible to maintain in this project.

Framework-specific scalars and other types have to be defined in your project using GraphQL SDL. See https://graphql.org/learn/schema/#scalar-types

Typically framework types such as custom scalars are placed in a .graphql file in the project, but you can also defined them using tagged templates like in Apollo: https://github.com/jimkyndemeyer/graphql-config-examples/blob/master/extend-client-fields-and-directives/client-schema-extensions.js
