### ISSUE TITLE
Question: Use project variables for .graphqlconfig

### ISSUE THREAD

**Issue by Bombo** [jimkyndemeyer/js-graphql-intellij-plugin#432]
Hey,

Thanks for this great plugin! Makes using GraphQL in Android Studio quite enjoyable! :)

One question:
Our GraphQL endpoint require authentication, and I've set up the .graphqlconfig file accordingly, but I don't want to commit my personal token to git (obviously). I saw the sample where an environment variable is used for this, but would it also be possible to have a local properties file or something which would just store such information and I could reference in the config file?

Something like this:

```properties
// /path/to/schema/local.properties (not in git)
authToken1=abcdef
```

```JSON
// /path/to/schema/.graphqlconfig (in git)
{
  "extensions": {
    "system1": {
      "headers": {
        "Autorization": "Bearer ${authToken1}"
      }
    }
  }
}
```

Thanks!

**Comment by vepanimas** [comment]
@Bombo hi! We've just released support for `.env` files. More details could be found here https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/285.
