### ISSUE TITLE
Issue with self-signed certificate

### ISSUE THREAD

**Issue by marcinjagielnicki** [jimkyndemeyer/js-graphql-intellij-plugin#435]
Hello,
after update to latest version I'm facing with error: 
`
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
`
Certificate of local domain is properly handled by e.g. chrome browser and other PHPStorm tools. Seems like problem is related to this plugin only.

**Comment by oneserv-heuser** [comment]
Can confirm that this issue exists.

**Comment by vepanimas** [comment]
@marcinjagielnicki thank you for the report! Sorry for the inconvenience, didn't test it with SSL after rework unfortunately. Will release one more hotfix update ASAP.

**Comment by marcinjagielnicki** [comment]
Thank you :)

**Comment by ugurcany** [comment]
I've encountered the same issue. Needed to downgrade my plugin version to 2.7.1. Waiting for fix.

**Comment by shayani** [comment]
Same here with version 2.9.0. Waiting for fix. Thanks for the amazing plugin.

**Comment by oneserv-heuser** [comment]
The plugin update is still pending on jetbrains side, see https://plugins.jetbrains.com/plugin/8097-js-graphql. Don't know why it's taking so long.

**Comment by vepanimas** [comment]
Fixed in the 2.9.1.
