### ISSUE TITLE
Schema directives file cannot be read by the plugin

### ISSUE THREAD

**Issue by canatufkansu** [jimkyndemeyer/js-graphql-intellij-plugin#436]
**Describe the bug**
When I create attached directives trough Lighthouse PHP package artisan command, JS Graphql add-on doesn't accept the file.

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. Use this file to in the project -> [schema-directives.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/6061512/schema-directives.txt)
2. Check schema.graphql -> [schema.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/6061523/schema.txt)
3. See that JS Graphql addon cannot check schema with given directives file.
4. Change the contents of the schema-directives file this given content -> [schema-directives.txt](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/files/6061542/schema-directives.txt)
5. See that this time JS Graphql can check schema against given directives file.

**Expected behavior**
When I create directives.graphql file through Lighthouse Php package JS Graphql should recognize the file and check my schema.graphql file according to it.

**Screenshots**

**Version and Environment Details**
Operation system: Macos 11.2.2
IDE name and version: PhpStorm 2020.3
Plugin version: 2.9.0

**Additional context**
I understand this issue is also related to Lighthouse Php package but I couldn't find any error on their directives file that is generated. Thus I open an issue on your side.

**Comment by tzkmx** [comment]
Same bug in Windows 10 with PhpStorm 2020.3.2, plugin version 2.9.0, downgrading plugin (tried 2.8 and 2.7) does not help, graphql files are not recognized anymore.

**Comment by vepanimas** [comment]
Hi @canatufkansu! I think it's because of repeatable directives (https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/351), they are not supported yet, but I'm currently working on it. I'm going to finish a complete redesign of the schema within this month.

As a quick fix, you could remove "repeatable" from the directives and check if it starts working.

**Comment by canatufkansu** [comment]
> Hi @canatufkansu! I think it's because of repeatable directives (#351), they are not supported yet, but I'm currently working on it. I'm going to finish a complete redesign of the schema building process within this month.
> 
> As a quick fix, you could remove "repeatable" from the directives and check if it starts working.

Hi, @vepanimas 

I tried the quick fix, it solved most of the issues but there is still an error. 

![image](https://user-images.githubusercontent.com/58461177/110443583-20b02d80-80cd-11eb-8dec-cd0d3ea43380.png)

![image](https://user-images.githubusercontent.com/58461177/110443852-6cfb6d80-80cd-11eb-8ffa-2aafac310bca.png)

**Comment by vepanimas** [comment]
@canatufkansu hi! Sorry for the late response. The error message says that the type with the name `_` is not defined, but it should be. I'm not sure what are you trying to achieve exactly, but you could try to define it manually like this
```
scalar _

# or

input _ {
    empty: String
}

type Query {
    id(orderBy: _): String
}
``` 

Repeatable directives support will be available soon.
