### ISSUE TITLE
template string ${variable} in gql template strings

### ISSUE THREAD

**Issue by Mischi** [jimkyndemeyer/js-graphql-intellij-plugin#44]
Hi,

we get a Syntax Error [0] when we try the following example [1] from [https://github.com/apollostack/graphql-fragments](graphql-fragments) 

Are there any plan to supprt template string variables within gql queries?

Thanks,
Fabian

[0]
```
Error:(25, 3) Syntax Error GraphQL (25:3) Unexpected Name "__typename"
```

[1]
```js
import gql from 'graphql-tag';
const query = gql`
  query {
    field {
      ...MyFragmentName
    }
  }
  ${fragment}
`;
```

**Comment by jimkyndemeyer** [comment]
Hi Mischi.

Thanks for using the plugin.

There is support for gql fragments as described in http://dev.apollodata.com/core/fragments.html

Will that work for you?

**Comment by Mischi** [comment]
Yes, that worked perfectly in the past 👍. But if i understand [https://github.com/apollostack/graphql-fragments](https://github.com/apollostack/graphql-fragments) correctly, they recommend the use of [graphql-anwhere](https://github.com/apollostack/graphql-anywhere) and to inline fragments directly with template string variables. So i'm wondering if that's something we can add support for too?

CC: @tmeasday

**Comment by jimkyndemeyer** [comment]
@stubailo Can you clarify whether this use case is the recommend approach for fragments going forward?

**Comment by SevInf** [comment]
@jimkyndemeyer Updated [guides](http://dev.apollodata.com/react/fragments.html#reusing-fragments) and [GitHunt example](https://github.com/apollostack/GitHunt-React/blob/master/ui/components/FeedEntry.js#L73-L91) recommend this approach.

**Comment by stubailo** [comment]
@jimkyndemeyer that's right - basically we didn't want people to have to use an additional function, and the interpolation approach allowed us to essentially pass "arguments" into `gql`.

**Comment by jimkyndemeyer** [comment]
This is fixed by https://github.com/jimkyndemeyer/js-graphql-language-service/issues/13 for the next release.
