### ISSUE TITLE
Errors not showing on schema errors panel

### ISSUE THREAD

**Issue by stephenjason89** [jimkyndemeyer/js-graphql-intellij-plugin#449]
**Before you create the issue**
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions
- Please search the [existing issues](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc) before opening a new issue
- Review the [developer guide](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide)
- Review the [example projects](https://github.com/jimkyndemeyer/graphql-config-examples)

**Describe the bug**

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. create a js file
2.  import graphql-tag
3.  create an incorrect query

**Expected behavior**
I expect the error to show on the graphql panel under schema errors

**Version and Environment Details**
Operation system:win10
IDE name and version: 2020.3.3 webstorm
Plugin version: 2.9.1

**Screenshots**

![image](https://user-images.githubusercontent.com/3810177/114085895-8cf89980-98e4-11eb-8374-4ac47780c2ab.png)

.graphqlconfig
```
{
  "name": "GraphQL Schema",
  "schemaPath": "schema.graphql",
  "extensions": {
    "endpoints": {
      "Default GraphQL Endpoint": {
        "url": "http://localhost:8000/graphql",
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "introspect": true
      }
    }
  }
}
```

**Comment by jimkyndemeyer** [comment]
Hi,

Thanks for using the plugin.

The GraphQL "Schemas and Project Structure" tool view is limited to schema errors, which doesn't include queries, fragments and mutations.

To see errors in queries and other places where you're using the schema, you can click the top-right error icon which shows "25" in your screenshot. This will bring up the "Problems" tool window.

Hope that's helpful.

Best regards,
Jim.

**Comment by stephenjason89** [comment]
Thank you for the reply :)
