### ISSUE TITLE
String descpritons should be valid

### ISSUE THREAD

**Issue by maraisr** [jimkyndemeyer/js-graphql-intellij-plugin#454]
**Before you create the issue**
- If you're using an EAP, try with a stable version. If that works, please mention it in the issue along with both versions
- Please search the [existing issues](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues?q=sort%3Aupdated-desc) before opening a new issue
- Review the [developer guide](https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide)
- Review the [example projects](https://github.com/jimkyndemeyer/graphql-config-examples)

**Describe the bug**

https://github.com/graphql/graphql-spec/issues/861#issuecomment-828132493

`""""""` before a field should make it break

**To Reproduce**
Link to Repo with Reproduction or Steps to Reproduce:
1. sdl with `""""""` as a description 
2. see failure

**Expected behavior**

Don't see failure

**Comment by vepanimas** [comment]
@maraisr hi! Unfortunately, I can't reproduce it with fields, only with types like here https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/408 (it's fixed already). Could you provide an invalid SDL pls?

**Comment by vepanimas** [comment]
Comments parsing reworked in 3.0, so it shouldn't be a problem anymore.
