### ISSUE TITLE
Sponsor request from CodeStream

### ISSUE THREAD

**Issue by mellson** [jimkyndemeyer/js-graphql-intellij-plugin#457]
I've received an email from CodeStream who'd like to sponsor this extension.
I don't feel like I'm the right person to handle this request, and I guess that maybe @jimkyndemeyer or @vepanimas already received the same email?

**Comment by jimkyndemeyer** [comment]
Hi Anders,

No email received on my side.

@vepanimas and JetBrains are driving the development at this point in time, so not sure how sponsorship fits into that setup.

While support is appreciated, I'd suggest that CodeStream donate to a charity, e.g. one that helps kids get into the joys of coding, but that's just my 2 cents :)

**Comment by mellson** [comment]
Thanks @jimkyndemeyer that sounds like a good idea.

@vepanimas what are your thoughts on this? If you agree with Jim I will send our suggestion to CodeStream.

**Comment by vepanimas** [comment]
Hi all, sorry for being silent, I had several long mandatory vacations and just recently returned to work. I don't think we need any kind of support, but in any case, it looks like this is no longer relevant now.
