### ISSUE TITLE
Set the Project Directory manually in WebStorm

### ISSUE THREAD

**Issue by kesemdavid** [jimkyndemeyer/js-graphql-intellij-plugin#46]
Hey, i've just ran into this AWESOME plugin and installed it right away.
Got a minor issue with the default project directory.

When u install the plugin and the 'Create config' pops up, it creates it automatically in the root directory of the project, in my case i got two projects there, backend and frontend.. and the plugin is relevant for the frontend only.
Manually moving the config file wont do it since it is set by default to the root project

![js graphql default dir](https://cloud.githubusercontent.com/assets/21152044/20980748/785de2a6-bcba-11e6-9b50-a55926417564.png)  
I want the project dir to be _/kesem-shel-bank/bank-client_ and not only _/kesem-shel-bank_ (assuming the 'watching config' part is relative to the project dir)

Any help on configuring the project directory by myself would be amazing, thanks in advance!

**Comment by jimkyndemeyer** [comment]
Hey.

Thanks for using the plugin.

In my team we're using the plugin with a very large product that has multiple modules in a project.

For that use case, the plugin will ask you which module to place the graphql.config.json in. From what I see in your screenshot, you appear to have a single module with two folders. Take a look at "File" -> "New" -> "Module from existing sources". You should be able to divide your project into two modules that way.

/Jim.

**Comment by kesemdavid** [comment]
Hey Jim, Thanks for that super quick reply!

Unfortunately, I cant seem to find the "Module from existing source" you're suggesting.
From my understand, what makes a directory a module is having a package.json file in it. (just like the `npm init` command does) but maybe i got it all wrong (?)

![module for existing source](https://cloud.githubusercontent.com/assets/21152044/20982068/b35e3d2e-bcbf-11e6-9cbb-7b12a748c9d6.png)

**Comment by jimkyndemeyer** [comment]
Ah, it looks like the multi-module feature is in IntelliJ IDEA but not in WebStorm. From the plugin point of view, they share the same API for project and modules, but it must be a deliberate limitation in WebStorm.

For now this means that in WebStorm the graphql.config.json file has to be in the project root. What you can do though, is to place the schema in the client directory, and point to it from the config file in the root. Then you avoid clutter in the project root.

I'll keep this issue open as an enhancement. Might be able to find a solution at some point.

**Comment by kesemdavid** [comment]
Actually what i've done is keeping the config in the root and getting the schema from the server endpoint and not a file, so the schema is still only in the server, but yeah, both solutions will do it.

Glad i could point that out :)

**Comment by jimkyndemeyer** [comment]
Closing this in favor of graphcool/graphql-config#16
