### ISSUE TITLE
Lighthouse Php "_" blank argument error.

### ISSUE THREAD

**Issue by asolopovas** [jimkyndemeyer/js-graphql-intellij-plugin#462]
Hi,
I am receiving a tiny error (`The field input type '_' is not present when resolving type 'Query' [@1:1]` and `Unknown type "_"`)  for "_" blank argument, which is used like in here https://lighthouse-php.com/master/api-reference/directives.html#orderby
```
type Query {
  posts(orderBy: _ @orderBy(columns: ["posted_at", "title"])): [Post!]! @all
}
```
Is there a way to ignore this error?

**Comment by vepanimas** [comment]
Hi! In your case `_` is a type reference that should be resolved to a type definition. So I think you could try defining your own type with the name `_` somewhere. For example, you could create a file like `declarations.graphql` and put there this text: 
```
scalar _
```
