### ISSUE TITLE
Add support for `schema` graphql config entry.

### ISSUE THREAD

**Issue by amir-zahedi** [jimkyndemeyer/js-graphql-intellij-plugin#467]
Feature request for v2.9.1

Thanks for the great work saving us hours team.
GraphGL Config standard now expects schema path to be defined under 'schema' entry as opposed to 'schemaPath' as used to be the standard.
https://graphql-config.com/usage#schema

To aid adopting this change it'd be great to support both entries (as GraphGL Config does right now).

<img width="240" alt="Screen Shot 2021-05-31 at 9 58 41 am" src="https://user-images.githubusercontent.com/1334204/120124669-ccfb3f00-c1f8-11eb-8169-2517f750a832.png">

**Comment by vepanimas** [comment]
Hi, thank you for the report! This plugin is using a [legacy](https://github.com/kamilkisiela/graphql-config/tree/legacy#graphql-config) version of the graphql-config. Migration to the v3 is the top priority. We already have such task https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/296, so I'm closing this one.
