### ISSUE TITLE
Add support for new relay directives @prependEdge @deleteEdge, and so on

### ISSUE THREAD

**Issue by ronaldcurtis** [jimkyndemeyer/js-graphql-intellij-plugin#468]
**Describe the bug**
First of all, really appreciate the work put into this package as it saves so much time writing graphql queries 🙏 . And this is not so much a bug, but a feature request. TLDR: Would be nice to have this plugin recognize the following new relay directives.

`@prependEdge`
`@prependNode`
`@appendEdge`
`@appendNode`
`@deleteEdge`

https://relay.dev/docs/guided-tour/list-data/updating-connections/#adding-edges
https://relay.dev/docs/guided-tour/list-data/updating-connections/#removing-edges

All the other relay directives seem to be recognized perfectly.

**Screenshots**
<img width="594" alt="Screen Shot 2021-06-06 at 13 01 34" src="https://user-images.githubusercontent.com/1256477/120912096-5b733300-c6c7-11eb-892c-1e1fe50a37c4.png">

**Comment by vepanimas** [comment]
@ronaldcurtis hi! It's already done and would be released in the next update.
