### ISSUE TITLE
Doesn't respect graphql-config possible places?

### ISSUE THREAD

**Issue by Anahkiasen** [jimkyndemeyer/js-graphql-intellij-plugin#47]
The [graphql-config](https://github.com/graphcool/graphql-config) says this plugin is compliant to it. But it seems it only works when in a `graphql.config.json` file, and that the plugin does _not_ look for a `.graphqlrc` nor inside the `package.json`. Is my assumption correct?

**Comment by jimkyndemeyer** [comment]
Hi Maxime.

Thanks for using the plugin.

It's not easy to spot, but support is listed as "(pending)" on the graphql-config page. In other words, no this plugin doesn't support graphql-config at this time.

The bottom line is that agreeing on a shared format that makes sense in all the various GraphQL enviroments is complicated. A few examples of the ongoing discussions: 
https://github.com/graphcool/graphql-config/issues/9 and https://github.com/facebookincubator/create-react-app/issues/462 and  https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/31.

So there's various technical constraints and feature requests at play. Not to mention migration paths between the different config file formats.

Let me know if you have any questions.

/Jim

/cc @schickling

**Comment by schickling** [comment]
Thanks for looping me in @jimkyndemeyer. I'd be happy to push this forward over the coming weeks. I'll reach out to you to discuss next steps.

**Comment by jimkyndemeyer** [comment]
@schickling sure. Wanted to keep you posted.

Although, between designing a new house and https://github.com/jimkyndemeyer/js-graphql-language-service/issues/11 I doubt that I can find the time to move this forward any time soon.

Let's talk further down the line.

/Jim

**Comment by jimkyndemeyer** [comment]
Closing this in favor of https://github.com/graphcool/graphql-config/issues/16
