### ISSUE TITLE
No visible way to set endpoint

### ISSUE THREAD

**Issue by dllx** [jimkyndemeyer/js-graphql-intellij-plugin#48]
Hi, I installed v1.4.4 of the plugin to edit a graphql request in an IntelliJ scratch buffer.
I created a new scratch buffer and set the language to GraphQL. Now I can edit with syntax checking, but there is no schema set and I can not set/select an endpoint URL.

The tool windows title bar with "Edit the GraphQL endpoints in graphql.config.json" etc is greyed out.

Maybe I need to create a graphql.config.json, but I don't know where or what to put into it. I cannot find any way to create one by using the plugin.

So: there should be a way to specify an endpoint after installing the plugin so that the plugin can fetch the schema and issue requests.

**Comment by jimkyndemeyer** [comment]
Hi Dirk.

Thanks for using the plugin.

It might be the case that a scratch file doesn't trigger the editor notification that should help you create the graphql.config.json. Here's an excerpt from the FAQ in the README.md:

> How do I configure the plugin in a project
> 
> The plugin is activated as soon as you view or edit GraphQL in the editor. This includes GraphQL inside Relay.QL and gql templates in JavaScript and TypeScript. You can also use .graphql physical files and scratch files. These files allow you to query your endpoint directly from your IDE.
> 
> An editor notification bar should prompt you to "Create a graphql.config.json". Accept and edit this config file to point the plugin at your local schema.json or your endpoint for introspection. The plugin uses the schema to provide completion and error highlighting.
> 

I suggest you try and create a physical .graphql file or use "Relay.QL" or "gql" tagged templates in .js files.

Let me know how it goes.

/Jim

**Comment by dllx** [comment]
Hi Jim,

thanks for the reply!

I managed to get the editor title bar prompt to create a graphql.config.json by creating a regular graphql file. I then could customize the config to my needs. Thanks!

It seems you're right, creating a scratch file or scratch buffer and switching its language to graphql doesn't trigger this prompt.

While experimenting, I deleted the graphql.config.json again, but then did not get the editor prompt even when creating a new .graphql file. Only after restarting the IDE would again give me this prompt.

I think it would be a good idea to be able to trigger the graphql.config.json creation by a user action (button or menu).

Also, a UI element to trigger re-loading the schema would be great. I had an error in my schema (which apparently is undetected by graphiql!) To reload the modified schema, I modified the graphql.config.json file by inserting a blank somewhere and saving it. That's a bit awkward.

Otherwise, so far as I can judge from the short usage now, you plugin seems great! Thank you!

**Comment by jimkyndemeyer** [comment]
Hi Dirk.

Thanks for the update.

You can reload schema as outlined in the FAQ:

> In the the GraphQL tool window, select the "Current Errors" tab and click the "Restart JS GraphQL Language Service" button.

I'll see if the scratch file detection and action to create the config can find it's way into a future release.

/Jim

**Comment by dllx** [comment]
Ah. I did read the readme, but somehow missed that last FAQ to reload the schema. Thanks again!

**Comment by jimkyndemeyer** [comment]
Hi Dirk.

The 2.0 release features a GraphQL Schemas tool panel that allows you re-run introspection queries to update your schema. See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-2

Let me know if you have any issues.

Best regards,
Jim.
