### ISSUE TITLE
Can not see/install 3.0 version in Android Studio

### ISSUE THREAD

**Issue by m-sabeeh** [jimkyndemeyer/js-graphql-intellij-plugin#483]
In Android Studio, searching for this plugin only shows old version 2.9.1.
While trying to manually install it from disk gives error;
> Plugin 'JS GraphQL' (version '3.0.0') is not compatible with the current version of the IDE, because it requires build 211.0 or newer but the current build is AI-203.7717.56

![Screenshot 2021-08-04 at 1 57 19 AM](https://user-images.githubusercontent.com/12383855/128085404-c789e703-b16d-44a8-8332-62916598ef4a.png)
IDE version

**Comment by vepanimas** [comment]
Hi! API incompatibilities require creating a specific build for 2020.* versions, I'll prepare a specific build for 2020.3 a bit later.

**Comment by vepanimas** [comment]
Release a new version compatible with 2020.3, should be available to update soon.
