### ISSUE TITLE
type X is not present when resolving type Y

### ISSUE THREAD

**Issue by mehhras** [jimkyndemeyer/js-graphql-intellij-plugin#488]
Hello guys, 

I use Intellij idea version 2021.2 and js graphql intellij plugin.

I develop a Spring boot project and this is my graphql structure in the resources.

![image](https://user-images.githubusercontent.com/11364267/130401267-a2b80d82-ed64-4974-bc67-65031f6c9ded.png)

This is my .graphqlconfig

![image](https://user-images.githubusercontent.com/11364267/130401606-af4926e8-41bb-4152-a3e6-10f46481f948.png)

Now, when I start my application I face with this problem:

graphql.schema.idl.errors.SchemaProblem: errors=[The field type 'LoginResponse' is not present when resolving type 'Mutation' [@1:1], The field input type 'LoginRequest' is not present when resolving type 'Mutation' [@1:1], The field type 'StudentDto' is not present when resolving type 'Query' [@2:1]]

and there is no error in graphql tab.

![image](https://user-images.githubusercontent.com/11364267/130401835-c8d4808e-d1f9-4e78-a225-16d192bd4ac4.png)

Thank you in advance.

**Comment by jimkyndemeyer** [comment]
Hi mehhras,

Thanks for using the plugin.

The plugin doesn't know about the server framework that you're using to implement your GraphQL endpoint, meaning that it can't tell you whether there's a runtime issue there. So in your case it looks like the plugin has done schema discovery as you'd expect (5 schema types), but your GraphQL server framework doesn't agree that you have a working GraphQL endpoint.

Please consult the docs on the framework you're using to resolve the problem. I'm closing this issue as it doesn't appear to be actionable for us.

Best regards,
Jim.
