### ISSUE TITLE
Refetch GraphQL schema based on graphql.config.json last modified time

### ISSUE THREAD

**Issue by blakegong** [jimkyndemeyer/js-graphql-intellij-plugin#49]
Hi Jim,

May I know is it possible to watch the mtime of `graphql.config.json` instead of the file content to decide whether to refetch GraphQL schema from endpoint?

The situation is like, say, I have a `graphql.config.json` as:
```json
{
  "schema": {
    "request": {
      "url": "http://localhost:8888/graphql",
      "method": "POST",
      "postIntrospectionQuery": true
    }
  }
}
```

Whenever I make some changes to the backend API, I have to come back to `graphql.config.json` to first mess with the file a little bit, like change the URL to:

```
"url": "http://messedlocalhost:8888/graphql"
```

Save it, then change it back to what it should be, then save again. And if I do this too fast, chances are the local cached schema would stay at the messed state.

I am hoping that by listening to mtime of `graphql.config.json`, we can simply do `touch ./graphql.config.json` or just open it up and save again to trigger a refetch of the remote schema. This should save a lot of time when you are doing full-stack development and you have loads of changes simultaneously happening in both front and back-end everyday.

Looking forward for your reply and thanks for this awesome project!!

**Comment by jimkyndemeyer** [comment]
Hi Yue Gong.

Thanks for using the plugin.

There is an action to refetch the schema from a URL, per the readme::

> **How do I reload a GraphQL Schema that was loaded from a URL?**
> 
> In the the GraphQL tool window, select the "Current Errors" tab and click the "Restart JS GraphQL Language Service" button. 

That should save you some time.

I'll keep this issue open as an enhancement since the mtime check would be a nice addition.

/Jim

**Comment by blakegong** [comment]
Hi Jim,

Thanks for the tip! Did not notice that since changing back-end code does not make it an error in your plugin. Definitely this would do for now and makes implementing reloading by mtime trivial.

Again thanks for the prompt reply!

Yue

**Comment by Gregoor** [comment]
@jimkyndemeyer could we have a shortcut for that? I have some projects where I simultaneously work on client and server side and always opening up the panel, navigating to the right tab and clicking refresh is a few steps too many for me. If you want, I can also look into it and make a PR.

**Comment by jimkyndemeyer** [comment]
The restart action now appears in the keymap dialog, making it possible to assign a keyboard shortcut. I'll close this issue based on that change since a new language service and configuration format is underway in collaboration with Facebook.

Will include this in the upcoming v1.5.0 of the plugin.

**Comment by Toilal** [comment]
What about adding a button for this restart action in the graphql view toolbar ?

**Comment by jimkyndemeyer** [comment]
@Toilal You can already customize your toolbars to show the action. See this attached screenshot where I've added the restart action next to the run actions:

![image](https://user-images.githubusercontent.com/15837712/32703163-13294e40-c7f2-11e7-9a1e-4faa5299adc6.png)
