### ISSUE TITLE
Compatibility with 2021.3

### ISSUE THREAD

**Issue by juergenzimmermann** [jimkyndemeyer/js-graphql-intellij-plugin#494]
**Describe the bug**
3.0.0 cannot be installed with IJ 2021.3

**To Reproduce**
Install IJ 2021.3 EAP, and then try to install 3.0.0.

**Expected behavior**
It would be nice if 3.0.0 can also be installed with IJ 2021.3

**Version and Environment Details**
Operation system: Windows 10 Enterprise 21H1
IDE name and version: IntelliJ 2021.3 EAP
Plugin version: 3.0.0

**Comment by juergenzimmermann** [comment]
@jimkyndemeyer The pretty outdated `2.5.0` (May 2020) is labelled with `2018.2+` and can be installed. Maybe you can just produce a new release and use `2021.3`.

**Comment by vepanimas** [comment]
Hi! I updated the compatibility range on the Marketplace, 3.0.0 should be available for install now.

**Comment by olivernybroe** [comment]
Awesome, so far no bugs happening for me in 3.0.0 with 2021.3 👍

**Comment by juergenzimmermann** [comment]
Thank you @vepanimas . The plugin works fine - just as with 2021.2.
