### ISSUE TITLE
Change background color of light green

### ISSUE THREAD

**Issue by Aranir** [jimkyndemeyer/js-graphql-intellij-plugin#50]
Great plugin.

I just have one concern, the background of an inline `gql` string receives a green background color.

I did not manage to find a way to remove the background color in any settings.

Is there a way to customize that background color?

**Comment by jimkyndemeyer** [comment]
Hi Roger.

Thanks for using the plugin.

The color comes from a feature called language injection. You can customize it as shown here:

![image](https://cloud.githubusercontent.com/assets/15837712/21569281/cbbb6780-cebb-11e6-82fb-9821fa495f0f.png)

/Jim
