### ISSUE TITLE
config.json is missing, how to bring it back?

### ISSUE THREAD

**Issue by aikonplus** [jimkyndemeyer/js-graphql-intellij-plugin#52]
As the plugin asked me to configure graphql.config.json, I said no, now the json file is missing, how do I set it up again, i tried to reinstall the plugin and delete my .idea folder, the plugin still do not create a new config.json.

Thank you

**Comment by aikonplus** [comment]
just created my own config.json and it worked. But as I see, this plugin is not compatible to apollo?

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for using the plugin.

It should be compatible with Apollo's gql tagged templates. Can you elaborate on the issue you're seeing?

/Jim.

**Comment by aikonplus** [comment]
well it is compatible with the gpl tag, but all the functions of the plugin are not?

Every query within the gpl tag in WebStorm are tagged as "cannot query field ..." though those queries are correct and working.

**Comment by jimkyndemeyer** [comment]
It sounds like the plugin has not been configured to use your specific schema yet.

Have you edited your `graphql.config.json` file to point it at your schema? See the readme fields in that file for the various options.

Let me know if you have any additional questions.

**Comment by aikonplus** [comment]
yes, probably, but I am using react-apollo with graphql and it looks like it has another format for the schema, as your plugin needs... i have a schema.js and it looks like this:
`export default typeDefs = [`

...
type Query{
...`]`

**Comment by jimkyndemeyer** [comment]
For that use case, the request field in the config can be used to send an introspection query which fetches the schema types. Make sure your graphql server is up and running, and you've configured the request url to be the same as your client uses, then fetch the schema types as follows:

> How do I reload a GraphQL Schema that was loaded from a URL?
> 
> In the the GraphQL tool window, select the "Current Errors" tab and click the "Restart JS GraphQL Language Service" button.

**Comment by jimkyndemeyer** [comment]
Closing this issue and marked as question. Feel free to ask any additional questions.

/Jim

**Comment by aikonplus** [comment]
Thank you for the fast respond, sadly it tells me the following:

> Unable to load schema from "...myProject/graphql.schema.json". Expected {data:{__schema:...}} or {__schema:...} from a schema introspection query. Got root keys: 

My client is sending the requests to `http://localhost:3000/graphql`

My I edited the config json to:
`"request": {
      "url" : "http://localhost:3000/graphql",
      "method" : "POST",...`

My schema.json is empty, since I do not use it. Am I doing something wrong?

**Comment by aikonplus** [comment]
had to remove `"file": "graphql.schema.json",`   now it works, thx
