### ISSUE TITLE
Add "Navigate to Declaration" across files

### ISSUE THREAD

**Issue by andheiberg** [jimkyndemeyer/js-graphql-intellij-plugin#56]
First off thanks for putting this plugin together. It's absolutely amazing and have most likely saved me hours of work already.

I do have one feature request though. It's amazing that you support "Navigate to Declaration" (CMD+Click) in GQL. However we have our schema split up into multiple files to make it easier to navigate. It would be amazing if the plugin could search across all .graphqls files in the project and not just the current file.

Don't have any experience with Intellij Plugins but might have a look around the code base to see if it's an easy fix. But would love to hear from you either way.

Thanks again,
Andreas

**Comment by AndreasHeiberg** [comment]
Hmm can't seem to find it :(

**Comment by jimkyndemeyer** [comment]
Hi Andreas.

Thanks for using a plugin.

Modules and scopes in IntelliJ are one of the more advanced features, and underpins other features such as find usages and go to declaration.

Right now, the GraphQL ecosystem is growing at an explosive rate, and with that follows a million different ways of structuring a project. So while your suggestions makes sense for your use case, it might be considered a bug for other projects. For example, Apollo very recently introduced imports in comments.

I'd like to see more of a consensus form, maybe even as part of the spec, before applying the efforts that this kind of tooling requires. But I'll keep this issue open an enhancement.

Best regards,
Jim.

**Comment by ph55** [comment]
Same here.
As example, apollographql and it's schemas that often combined from different files.
https://www.apollographql.com/docs/graphql-tools/schema-stitching.html

**Comment by jimkyndemeyer** [comment]
The 2.0 alpha makes it possible to have multiple schemas in a single project using IntelliJ/WebStorm "Scopes". You can configure them for the project in the IDE Settings dialog. The scopes also apply to resolving fragments. By default the entire project is searched.

See [2.0.0-alpha-2](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-alpha-2) if you'd like to try it and help test it.

**Comment by jimkyndemeyer** [comment]
The 2.0 release supports this by discovering your schema files on the fly. See https://jimkyndemeyer.github.io/js-graphql-intellij-plugin/docs/developer-guide

Best regards,
Jim.
