### ISSUE TITLE
Introspection Query not compatible with latest GraphQL Working Draft

### ISSUE THREAD

**Issue by xsc** [jimkyndemeyer/js-graphql-intellij-plugin#58]
Hey there,

it seems that the query sent for introspection of a remote GraphQL endpoint requests fields that have been removed in [April 2016](https://github.com/facebook/graphql/releases/tag/April2016), namely `onOperation`, `onFragment` and `onField` on the `__Directive` type.

Since our backend is implementing the October 2016 version of the working draft, it's as of now seemingly incompatible with this plugin (which our client developers would love to use).

Please tell me if I can supply more information on this topic (or if I'm just missing something).
Thank you!
Yannick

**Comment by jimkyndemeyer** [comment]
Hi Yannick.

If I understand correctly, you're using the request option in graphql.config.json in combination with postIntrospectionQuery: true?

As a temporary workaround you can perform the introspection query yourself, and use the file config option in graphql.config.json to point at the query result.

See https://github.com/jimkyndemeyer/js-graphql-language-service/blob/bc683684ae922ce7dd4f17a283a2dad125c86bf6/src/project.js#L14 for where the introspection query can be found in graphql-js.

The trouble with updating to use the latest introspection query is that it might render other endpoints incompatible. I'll give this some thought.

**Comment by jimkyndemeyer** [comment]
For how to script the use of a local schema.json file, see https://github.com/relayjs/relay-examples/blob/master/star-wars/package.json#L5 from the relay examples. This setup works with the plugin.

**Comment by xsc** [comment]
@jimkyndemeyer Thanks for the response, I'll check your suggestions out!

Feel free to close this issue, unless you want to keep it around until you've made a decision on how this should be handled in future.

Thanks again!

**Comment by jimkyndemeyer** [comment]
Merging this into #121
