### ISSUE TITLE
Not compatible with latest version

### ISSUE THREAD

**Issue by jimartinmoreno** [jimkyndemeyer/js-graphql-intellij-plugin#606]
Hi,

It seems the latest version of the IntelliJ IDE (IntelliJ IDEA 2022.1 (Ultimate Edition, Build #IU-221.5080.210, built on April 12, 2022) is incompatible with the plugin. Is there any alternative or workaround?

Thx!

**Comment by icypig** [comment]
We met the same problem here, how do u fix this problem?

**Comment by icypig** [comment]
Need manually installation
