### ISSUE TITLE
Java implementation of GraphQL Language Service

### ISSUE THREAD

**Issue by asiandrummer** [jimkyndemeyer/js-graphql-intellij-plugin#61]
@jimkyndemeyer - I finally got around to this and did some more researching. If I understood correctly, the server/client communication for this plugin uses NodeJS plugin support, which isn't available in IntelliJ Community Edition, right?

Nonetheless, I was wondering whether a Java implementation of GraphQL language service would be a good thing to have. Eclipse team has developed [a Java binding for the Language Server Protocol](https://github.com/eclipse/lsp4j) and I wanted to ask your opinion on extending the GraphQL language service with this Java implementation.

What do you think?

**Comment by jimkyndemeyer** [comment]
I assume you're not talking about having a separate implementation of https://github.com/graphql/graphql-language-service written in Java?

I checked the JetBrains plugin repository, and you're correct that Community Edition doesn't list the Node.js plugin.

**Comment by asiandrummer** [comment]
Sorry, I misunderstood what this plugin does. Let me close this issue and create another one with a clearer question ;)
