### ISSUE TITLE
Support for .js files with graphql-tag npm module

### ISSUE THREAD

**Issue by Alex-Mann** [jimkyndemeyer/js-graphql-intellij-plugin#63]
It would be great to be able to see the query result when working with the query or mutation as a .js file. For example, in my apollo react project, this would be my current user query:
```
import gql from 'graphql-tag';

export default gql`
  {
    user {
      id
      email
    }
  }
`;
```
Alternatively, as a quick workflow fix it would be great to execute these queries within webstorm.

**Comment by hmontes** [comment]
http://imgur.com/a/DODtF

With Apollo.

**Comment by Draccoz** [comment]
Any response on that? My team moved from angular webpack starter to angular-cli and can no longer import `.graphql` files. It would be very handy for us to have the similar execute options for `graphql-tag` as there is for `.graphql` files.

**Comment by jimkyndemeyer** [comment]
I don't have any spare time left to work on new features for the plugin. A PR would be very welcome.

Best regards,
Jim.

**Comment by Draccoz** [comment]
I've never done any plugin to Intellij, but will try if I get some free time, unless somebody does that before me :P.
Nevertheless, good job with the current plugin :).

**Comment by LawJolla** [comment]
This would be a huge and welcome enhancement. Unfortunately, my java knowledge is zero.

Thanks for the hard work, and I'll continue using your great plugin and riding coattails. 👍

**Comment by jimkyndemeyer** [comment]
This is possible in the upcoming 2.0 release. See https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/164#issuecomment-479756614

Best regards,
Jim.
