### ISSUE TITLE
Pass "variables" in payload to GraphQL server as Json.

### ISSUE THREAD

**Issue by zvorygin** [jimkyndemeyer/js-graphql-intellij-plugin#64]
Thanks for your wonderful plugin.

I'm implementing custom GraphQL server, and made it "compatible" with GraphiQL chrome plugin, which I used to debug and develop my server.

I've recently found this plugin, but it sends variables as string as opposed to GraphiQL behavior. Is there anything we can do with that?

In example from "http://graphql.org/learn/serving-over-http/" they serve variables as JSON object when being executed through POST.

**Comment by jimkyndemeyer** [comment]
Hi Dmitry.

Thank you for taking the time to contribute. I'll see if I can get to this on Sunday.

Best regards,
Jim.

**Comment by jimkyndemeyer** [comment]
Fixed in v1.5.2, pending JetBrains approval.

Once again thanks for contributing.

Best regards,
Jim.
