### ISSUE TITLE
Non-standard file extension expected.

### ISSUE THREAD

**Issue by richburdon** [jimkyndemeyer/js-graphql-intellij-plugin#66]
According to Facebook, the preferred extension is .graphql (not .graphqls):

https://github.com/facebook/graphql/issues/203

So these, warnings are a bit annoying:

Warning:(19, 1) Schema definitions should be written in GraphQL Schema files (.graphqls)

Also, at odds with your generated config file?

"README_endpoints": "A list of GraphQL endpoints that can be queried from '.graphql' files in the IDE",

**Comment by piotrd** [comment]
Those warnings are annoying, indeed.

**Comment by jimkyndemeyer** [comment]
Please see my comment: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/85#issuecomment-307818650

Closing this in favor of #85
