### ISSUE TITLE
(A) link in code not useful

### ISSUE THREAD

**Issue by richburdon** [jimkyndemeyer/js-graphql-intellij-plugin#67]
The (A) link in the left source code gutter would be **so much more** useful if it linked to the GraphQL file, rather than the home page for the Apollo web site.

**Comment by jimkyndemeyer** [comment]
Hi Rich.

Which GraphQL file do you mean?

Thanks,
Jim.

**Comment by jimkyndemeyer** [comment]
Closing due to missing reply.
