### ISSUE TITLE
Allow `.graphqls` file setting in `graphql.config.json`

### ISSUE THREAD

**Issue by jamiter** [jimkyndemeyer/js-graphql-intellij-plugin#70]
Thanks for the awesome plugin!

It would be nice if this plugin would recognise `.graphql` and `.graphqls` files instead of only `.json` files when configuring `file`. Now I have to parse my `.graphqls` file first or start up a server.

This is what my `graphql.config.json` would look like if supported:
```json
{
  "schema": {
    "file": "data/example.graphqls"
  }
}
```

Or is there an another way to point this plugin to a `.graphqls` file instead of `graphql.schema.json`?

Multiple schema files would also be great of course.

**Comment by SPAHI4** [comment]
+1 
also, would be great multiple schemas as pattern:
```
schema: "./graphql/modules/*/*.graphqls"
```

**Comment by amitport** [comment]
Seems to work in version 1.6.1, can be closed?

**Comment by jimkyndemeyer** [comment]
Thanks @amitport, yeah this was added to support Relay Modern projects.
