### ISSUE TITLE
Support dynamic endpoint options

### ISSUE THREAD

**Issue by piotrd** [jimkyndemeyer/js-graphql-intellij-plugin#72]
I am working with a GraphQL API that requires authorization with a token (`authorization` header option passed with each request). With each session the token changes, and I have to manually update it in `graphql.config.json`. I have not yet found a way to pass e.g. `process.env.ACCESS_TOKEN`, but maybe there is some way to achieve that? If not, then it would be great to have node env variables to override at least `headers` in `graphql.config.json`, although it may not be possible, because the app and the plugin work in separate node environments...

**Comment by piotrd** [comment]
So far the only thing that works for me is a node script updating the auth header in `graphql.config.json` on app start.

**Comment by skyjia** [comment]
+1

**Comment by jimkyndemeyer** [comment]
See [remote-schema-introspection](https://github.com/jimkyndemeyer/graphql-config-examples/tree/master/remote-schema-introspection) for how v2 of the plugin supports this use case. You can specific API tokens via environment variables in the `.graphqlconfig` file as described in the  [graphql-config documentation](https://github.com/prisma/graphql-config/blob/master/specification.md#configuring-graphql-endpoint).

If you'd like to help test v2 the releases are found at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases

Best regards,
Jim.
