### ISSUE TITLE
Android Setup + Remote Schema

### ISSUE THREAD

**Issue by jpshelley** [jimkyndemeyer/js-graphql-intellij-plugin#8]
Awesome idea for a plugin, and was able to download and install. Still confused on the setup and how to validate my query against my schema. Do I need to download and run the https://github.com/jimkyndemeyer/js-graphql-language-service service?

**Comment by jimkyndemeyer** [comment]
Hi John.

Thanks for trying out the plugin.

The language service is included in the plugin.

Android Studio version isn't as easy to get started with as the JavaScript version in master. What you'll need to do is create a file with a `.graphql` extension in your project, e.g. "query.graphql". This activates the graphql parser, and it should display an editor notification bar with a link to add a `graphql.config.json`to your project. If you don't have a JSON file with the graphql introspection query result on your disk, you can point at a URL instead. See my comments in  https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/5 for how to do this.

**Comment by jpshelley** [comment]
Awesome work! I'll close this ticket. Would you recommend writing queries in `*.graphql` files or in java then? I suppose if there is a variable in the query I can use an I/O procedure to open the file and replace the variable such as  `{$limit}` with the correct limit?

**Comment by jimkyndemeyer** [comment]
I haven't used GraphQL in a Java project yet, but I think having the queries in `.graphql` files that are loaded as resources using the class loader would make sense.

Regarding variables, you send them to the GraphQL endpoint as JSON:

```
{
  "query": "query MyQuery($myVariable: String) { ... }",
  "variables": { "myVariable": "my-value" }
}
```

This gives you the same kind of security as with SQL parameters, e.g. avoiding injection etc.

**Comment by jpshelley** [comment]
Awesome thanks for the help! I'll close this issue now.
