### ISSUE TITLE
No Syntax Highlighting in .graphqls file 

### ISSUE THREAD

**Issue by amirhakim** [jimkyndemeyer/js-graphql-intellij-plugin#81]
Great work, loving the plugin, it is exactly what was missing from my Dev environment 

I am facing the same issue in Intellij on Ubuntu (Apollo), this is my observation so far:
1 - if i copy the generated .graphqls schema to a new file with the same extension inside the project then it will not recognise it ...until...
2 - i press enter/new line ..then it works
I have the following settings 
![screenshot from 2017-05-29 08-20-41](https://cloud.githubusercontent.com/assets/6634984/26549592/c46bd1ac-4447-11e7-97ef-f3b7dddceb71.png)

(related to [issue#77 ](https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/issues/77#issuecomment-304437687))

**Comment by jimkyndemeyer** [comment]
Hi.

Thanks for using the plugin.

Please give the 2.0 release a go: https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/releases/tag/2.0.0-beta-2

Let me know if you have any issues.

Best regards,
Jim.
