### ISSUE TITLE
cannot query schema in corporate-firewall network

### ISSUE THREAD

**Issue by pso-aeb** [jimkyndemeyer/js-graphql-intellij-plugin#82]
When the plugin queries the Schema from my endpoint I get this error:

> Error loading schema from 'https://api.graph.cool/simple/v1/cj32zhn6tpd740122q5hwx1pe' { Error: self signed certificate in certificate chain

The likely cause is the corporate-firewall of my company.
When calling something from outside the local network (in this case the external GraphQL-Server), the firewall will replace the foreign certificate with an internal one. This leads to the above error.

Could you please either
- add a possibility to register a custom certificate for SSL
- add a config parameter to disable SSL all together

**Comment by mattias800** [comment]
Why not fetch it with another tool and then point the plugin to that schema, instead of fetching it?

**Comment by vepanimas** [comment]
Should be fixed in #435.
