### ISSUE TITLE
"Plugin "JS GraphQL" was not loaded: required plugin "NodeJS" not installed."

### ISSUE THREAD

**Issue by poyannabati** [jimkyndemeyer/js-graphql-intellij-plugin#88]
Upon install I get.
```Plugin "JS GraphQL" was not loaded: required plugin "NodeJS" not installed.```

The NodeJS plugin IS loaded.

And pressing the link "Enable NodeJS" and then restarting just brings you back to square one (square zero I guess). 

![image](https://user-images.githubusercontent.com/1499050/27578534-b1a731d0-5b24-11e7-964c-ea15485cf99b.png)

Running;
IntelliJ IDEA 2017.1.4
Build #IU-171.4694.23, built on June 6, 2017

**Comment by jimkyndemeyer** [comment]
Hi Poyan.

I think you may have a version of the Node.js plugin that is incompatible with your IntelliJ.

Try uninstalling both Node.js and this plugin. Then reinstall, starting with Node.js.

**Comment by jimkyndemeyer** [comment]
Closing this for now. Let me know if the reinstall doesn't work.
