### ISSUE TITLE
graphql.config.json: reference schema.graphqls as schema definition

### ISSUE THREAD

**Issue by davideberlein** [jimkyndemeyer/js-graphql-intellij-plugin#89]
How can I reference my `*.graphqls`file as the schema?
If I simply point the file to it like this:
```json
"schema": {
    "file": "./server/src/schema.graphqls"
  },
```
I get a json parse exception.
I don't have the json definition of the schema so I'm no sure how to integrate it this way.

**Comment by jimkyndemeyer** [comment]
Hi David.

See the relay example for a script that achieves this: https://github.com/relayjs/relay-examples/blob/master/star-wars/scripts/updateSchema.js

See the package.json in that repo.

**Comment by davideberlein** [comment]
Thanks
