### ISSUE TITLE
Specify .graphqls file, not json

### ISSUE THREAD

**Issue by rdrey** [jimkyndemeyer/js-graphql-intellij-plugin#9]
Hi there!

Awesome packages, thanks! 👍 

Is there a way to configure a .graphqls file instead of a json file in the config?

I'm using the "request" option at the moment, but it seems to reload everytime my file watcher is busy restarting my webserver. I've tried specifying
```.json
      "options" : {
        "headers": {
          "user-agent": "JS GraphQL"
        },
        "retry": true,
        "retryDelay": 300,
        "maxRetries": 5
      }
```
but the service still seems to hit my webserver in a bad moment (`[Error: connect ECONNREFUSED 127.0.0.1:8080]`). It does refresh the schema correctly sometimes. The query buffer seems to always get correct responses when I try, though.

**Comment by jimkyndemeyer** [comment]
Hey.

Thanks for using the plugin.

Using a .graphqls file isn't currently supported. This plugin has a dependency on `codemirror-graphql` which requires the JSON result from an introspection query.

The request option was originally intended to work with existing stable servers. If you're auto-restarting your server I would suggest that you go back to using the file option and write the schema JSON file when your server starts in dev mode.

What you'd need to do is similar to what the language service does if it's configured to send an introspection query. If the query succeeds you can the use the file system to update the schema.json file. The relevant code is at https://github.com/jimkyndemeyer/js-graphql-language-service/blob/master/src/project.js#L134-L155 -- simply write the schemaBody variable to schema.json.

On a related note. If the plugin gets an error from the url you can restart it from the IDE to retry the request. See the last item in the faq at https://github.com/jimkyndemeyer/js-graphql-intellij-plugin#faq

**Comment by rdrey** [comment]
Ah perfect, I had missed that last FAQ item, thanks!

Thanks, I will try implementing that tonight!

**Comment by rdrey** [comment]
Just wanted to check back and say that this works amazingly well. The only issue I have left is that modifying my .graphqls file pops open the console with errors while I'm writing it. But hitting save restarts my webserver, which rewrites the .json file on startup, so that part works perfectly.

Is there an easy way to keep the benefit of the syntax highlighting, but stop the plugin from sending every keystroke in the schema file for evaluation?

**Comment by jimkyndemeyer** [comment]
As it stands, the .graphqls support is considered read-only and requires that a valid parse tree can be created for syntax highlighting. It was added as a means of showing the currently loaded schema that the plugin uses for completion, error highlighting, and for providing find usages etc.

I logged https://github.com/graphql/codemirror-graphql/issues/14 a short while ago since schema editing would be a useful addition. Until that issue is implemented, you should edit your schema file with another file extension to prevent the errors-as-you-type from popping up the console.

**Comment by rdrey** [comment]
Cool, will do, thanks!
