### ISSUE TITLE
Only attempt to run introspection query once; or stop console from logging

### ISSUE THREAD

**Issue by bw** [jimkyndemeyer/js-graphql-intellij-plugin#90]
Thanks for building this plugin! It has been super helpful.

Quick request-- we develop locally, so we point the GraphQL endpoint to `localhost`. When the development server is not running, your plugin unfortunately renders WebStorm impossible to use. 

Every single file save and basically every key stroke will trigger `ECONNREFUSED` errors into the console, which always takes precedence over anything else that's done. For example, actually starting up the GraphQL server via the terminal is often difficult to do, since any change causes the console to kick up. This happens even if no GraphQL file has been opened, of course.

Is there a way to show this error _once_, perhaps via a popup at the bottom right as many other plugins do? Something like "We were unable to run the GraphQL introspection query (ECONNREFUSED). Click to try again."? Or alternatively, only run the introspection query when a .graphql file is opened.

Again, really appreciate your work. Cheers!

**Comment by jimkyndemeyer** [comment]
Hi Brandon.

Thanks for using the plugin.

I might be able to take a look at this sometime during the weekend.

The introspection feature was initially intended for externally running servers, so until this is fixed you might be better of with the "file" option which points to a `schema.json` you can update using a scripted introspection query.

/Jim

**Comment by jimkyndemeyer** [comment]
Hi Brandon.

I've just tried to reproduce this, but I only see the console pop up once during project start when I point at a non-running endpoint for introspection. Working and saving files (other than graphql.config.json) doesn't trigger any additional GraphQL Error output or focus steals.

Can you describe your setup in more detail, the exact steps you take to reproduce, and include your graphql.config.json file.

Thanks,
Jim.

**Comment by bw** [comment]
Sure.

My `graphql.config.json` file, located in the root of our project directory, is as follows:
```json
{
  "schema": {
    "request": {
      "url": "http://localhost:8000/graphql",
      "method": "POST",
      "postIntrospectionQuery": true
    }
  },
  "endpoints": [
    {
      "name": "Local dev (:8000)",
      "url": "http://localhost:8000/graphql",
      "options": {
        "headers": {
          "user-agent": "JS GraphQL"
        }
      }
    }
  ]
}
```

With the development server not running (i.e. `localhost:8000` does not resolve), if I open up WebStorm then I get the console logs on startup. This is expected.

But I close the console log, then modify a file that is not related to GraphQL (in the case I just attempted, a JSX file located in the scope of our project). There are no file watchers configured or anything (our development server compiles when it detects file changes, and in this case it is not running). When I do this the console opens up again.

This will happen every time I change a file in project scope, regardless of which one it is. And sometimes it will just pop up on its own even when a file is not saved, although I could just be imagining this part.

Here is the error in the console that shows each time:

```
Error loading schema from 'http://localhost:8000/graphql' { Error: connect ECONNREFUSED 127.0.0.1:8000
    at Object.exports._errnoException (util.js:1016:11)
    at exports._exceptionWithHostPort (util.js:1039:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1138:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000 } { url: 'http://localhost:8000/graphql',
  method: 'POST',
  postIntrospectionQuery: true,
  options: 
   { headers: 
      { 'Content-Type': 'application/json',
        'Content-Length': 1550,
        'Accept-Encoding': 'gzip,deflate' },
     body: '{"query":"\\n  query IntrospectionQuery {\\n    __schema {\\n      queryType { name }\\n      mutationType { name }\\n      subscriptionType { name }\\n      types {\\n        ...FullType\\n      }\\n      directives {\\n        name\\n        description\\n        locations\\n        args {\\n          ...InputValue\\n        }\\n      }\\n    }\\n  }\\n\\n  fragment FullType on __Type {\\n    kind\\n    name\\n    description\\n    fields(includeDeprecated: true) {\\n      name\\n      description\\n      args {\\n        ...InputValue\\n      }\\n      type {\\n        ...TypeRef\\n      }\\n      isDeprecated\\n      deprecationReason\\n    }\\n    inputFields {\\n      ...InputValue\\n    }\\n    interfaces {\\n      ...TypeRef\\n    }\\n    enumValues(includeDeprecated: true) {\\n      name\\n      description\\n      isDeprecated\\n      deprecationReason\\n    }\\n    possibleTypes {\\n      ...TypeRef\\n    }\\n  }\\n\\n  fragment InputValue on __InputValue {\\n    name\\n    description\\n    type { ...TypeRef }\\n    defaultValue\\n  }\\n\\n  fragment TypeRef on __Type {\\n    kind\\n    name\\n    ofType {\\n      kind\\n      name\\n      ofType {\\n        kind\\n        name\\n        ofType {\\n          kind\\n          name\\n          ofType {\\n            kind\\n            name\\n            ofType {\\n              kind\\n              name\\n              ofType {\\n                kind\\n                name\\n                ofType {\\n                  kind\\n                  name\\n                }\\n              }\\n            }\\n          }\\n        }\\n      }\\n    }\\n  }\\n"}' } }
```

Thanks for all your work looking into this! Let me know how else I can help.

**Comment by jimkyndemeyer** [comment]
I've tried to reproduce using the exact same config, but no luck.

Something must be triggering the introspection query. A new query should only be triggered by:

- Project startup
- The "Restart JS GraphQL Language Service" action
- Modifications to graphql.config.json

Can you check whether you've somehow bound a key to the restart action, or whether the modify/created date on graphql.config.json changes as you work on the JSX file?

**Comment by bw** [comment]
Hmm, neither of those things is happening. I run WebStorm with Git integration but I can't imagine that having any effect...

**Comment by jimkyndemeyer** [comment]
Seeing as the underlying cause for this issue is unclear, and I'm unable to reproduce, I've included a fix in 1.5.4 that only shows the console automatically on the first project error.

Just released to the plugin repository, and pending JetBrains approval (typically 1-2 business days).

Feel free to add a comment if you find additional info to help reproduce.

**Comment by bw** [comment]
Jim, I hope this will fix the problem-- thanks so much for all your hard work maintaining this plugin. Have a great week!

**Comment by jimkyndemeyer** [comment]
Thanks, you too :)
