### ISSUE TITLE
Add tab indentation support

### ISSUE THREAD

**Issue by roballsopp** [jimkyndemeyer/js-graphql-intellij-plugin#92]
I use tab indentation for most of my code. It would be great to add tabs to the Code Format section

**Comment by dontsave** [comment]
I'd also like to see this!

**Comment by snolangps** [comment]
Same here, this would be nice for sure.

**Comment by jimkyndemeyer** [comment]
Fixed in 2.2.0 pending JetBrains approval: Added Code Style settings page to control indentation
