### ISSUE TITLE
Find Usage dialog broken 

### ISSUE THREAD

**Issue by joshcanfield** [jimkyndemeyer/js-graphql-intellij-plugin#93]
With the plugin installed the "Find Usages" dialog is missing options when searching Java methods/classes.

https://intellij-support.jetbrains.com/hc/en-us/community/posts/206195489-Find-Usage-missing-options

<img width="543" alt="screen shot 2017-08-19 at 4 52 57 am" src="https://user-images.githubusercontent.com/157231/29486442-94b911de-849a-11e7-8a8c-fcf2096e586b.png">

<img width="631" alt="screen shot 2017-08-19 at 4 51 01 am" src="https://user-images.githubusercontent.com/157231/29486444-9877635c-849a-11e7-80d4-cec5d12f9fc2.png">

**Comment by joshcanfield** [comment]
This looks like the problem. All named elements are given an empty FindUsagesHandler.

https://github.com/jimkyndemeyer/js-graphql-intellij-plugin/blob/55e3bb41cd116e76d6b1e74ac11e9f8407644624/src/main/com/intellij/lang/jsgraphql/endpoint/ide/findUsages/JSGraphQLEndpointFindUsagesHandlerFactory.java#L28

**Comment by jimkyndemeyer** [comment]
Version 1.6 with this fix has been uploaded to the plugin repository and is now pending approval by Jetbrains.
