### ISSUE TITLE
Problems found loading plugins: required plugin not installed

### ISSUE THREAD

**Issue by BorzdeG** [jimkyndemeyer/js-graphql-intellij-plugin#95]
YT issue: https://youtrack.jetbrains.com/issue/IDEA-178624

**Comment by jimkyndemeyer** [comment]
I've seen this happen myself, but only after upgrades of IntelliJ. I believe this points to an issue with the plugin manager and not the plugin itself.

As you write in the YT issue, once the Node.js plugin shows as having an update and you apply that, it becomes compatible and the problem goes away. There's nothing actionable here, so closing the issue.
